"""Closed Cash Register domain catalogs."""
from enum import Enum


class DeviceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    MAINTENANCE = "MAINTENANCE"
    BLOCKED = "BLOCKED"
    RETIRED = "RETIRED"


class CashShiftStatus(str, Enum):
    OPENING = "OPENING"
    OPEN = "OPEN"
    SUSPENDED = "SUSPENDED"
    PENDING_COUNT = "PENDING_COUNT"
    COUNTING = "COUNTING"
    COUNTED = "COUNTED"
    PENDING_REVIEW = "PENDING_REVIEW"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    FORCE_CLOSED = "FORCE_CLOSED"
    CANCELLED = "CANCELLED"


class CashMovementDirection(str, Enum):
    INFLOW = "INFLOW"
    OUTFLOW = "OUTFLOW"


class CashMovementType(str, Enum):
    OPENING_FLOAT = "OPENING_FLOAT"
    CASH_SALE = "CASH_SALE"
    CASH_REFUND = "CASH_REFUND"
    CASH_IN = "CASH_IN"
    CASH_OUT = "CASH_OUT"
    MANUAL_INCOME = "MANUAL_INCOME"
    MANUAL_WITHDRAWAL = "MANUAL_WITHDRAWAL"
    SAFE_DROP = "SAFE_DROP"
    CASH_PICKUP = "CASH_PICKUP"
    CASH_HANDOVER = "CASH_HANDOVER"
    CASH_RECEIPT = "CASH_RECEIPT"
    CHANGE_ADDITION = "CHANGE_ADDITION"
    AUTHORIZED_PAID_OUT = "AUTHORIZED_PAID_OUT"
    REVERSAL = "REVERSAL"
    ADJUSTMENT = "ADJUSTMENT"


class BlindCountStatus(str, Enum):
    OPEN = "OPEN"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"


class CashDifferenceStatus(str, Enum):
    DETECTED = "DETECTED"
    EXPLAINED = "EXPLAINED"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"


class CashDifferenceClassification(str, Enum):
    SHORTAGE = "SHORTAGE"
    OVERAGE = "OVERAGE"


class CashDifferenceSeverity(str, Enum):
    WITHIN_TOLERANCE = "WITHIN_TOLERANCE"
    REVIEW = "REVIEW"
    CRITICAL = "CRITICAL"


class CashHandoverStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    PREPARED = "PREPARED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    RECEIVED = "RECEIVED"
    DISPUTED = "DISPUTED"
    CANCELLED = "CANCELLED"


class CashPaymentMethodType(str, Enum):
    CASH = "CASH"
    BANK_CARD = "BANK_CARD"
    BANK_TRANSFER = "BANK_TRANSFER"
    PAYMENT_LINK = "PAYMENT_LINK"
    PAYMENT_PROCESSOR = "PAYMENT_PROCESSOR"
    CUSTOMER_CREDIT = "CUSTOMER_CREDIT"
    STORE_CREDIT = "STORE_CREDIT"
    REFUND_VOUCHER = "REFUND_VOUCHER"
    PROMOTIONAL_VOUCHER = "PROMOTIONAL_VOUCHER"
    GIFT_CARD = "GIFT_CARD"
    LOYALTY_POINTS = "LOYALTY_POINTS"
    MIXED = "MIXED"


class CashRefundMethod(str, Enum):
    ORIGINAL_PAYMENT_METHOD = "ORIGINAL_PAYMENT_METHOD"
    CASH = "CASH"
    REFUND_VOUCHER = "REFUND_VOUCHER"
    STORE_CREDIT = "STORE_CREDIT"
    BANK_TRANSFER = "BANK_TRANSFER"
    NO_CASH_REFUND = "NO_CASH_REFUND"


class DrawerOpenReason(str, Enum):
    SALE = "SALE"
    REFUND = "REFUND"
    CASH_MOVEMENT = "CASH_MOVEMENT"
    SAFE_DROP = "SAFE_DROP"
    OPENING = "OPENING"
    CLOSING = "CLOSING"
    MANAGER_OVERRIDE = "MANAGER_OVERRIDE"
    HARDWARE_TEST = "HARDWARE_TEST"
    NO_SALE_AUTHORIZED = "NO_SALE_AUTHORIZED"
