"""CRM role → permission matrix (CRM-2, master prompt §59, §72).

This is **seed/reference data**, not an authorization mechanism. Roles in
this codebase are rows in the ``roles``/``permisos``/``roles_permisos``
tables (see ``migrations/m000_base_schema.py``), resolved at runtime through
``SessionContext.tiene_permiso(codigo)`` — never through
``if role == "..."`` in application code (that is exactly what
``test_customers_crm_permissions_are_not_role_names.py`` forbids). This
module exists so a future seed migration (wired when the CRM module goes
live, CRM-14+) has one canonical source for "what does each suggested CRM
role grant" instead of every seed script inventing its own list.

Segregation of duties is baked into the matrix itself where §73 requires it:
credit analyst gets ``CREDIT_REVIEW`` but not ``CREDIT_APPROVE``; the
importer role gets ``IMPORT`` but not ``IMPORT_APPROVE``; the merge
proposer (data steward) gets ``DUPLICATES_MERGE`` but approval of a
*sensitive* merge still goes through hot authorization
(``CustomerAuthorizationGrant``), not a role grant alone.
"""

from __future__ import annotations

from backend.application.crm.permissions import CRMPermissions as _CRM
from backend.application.customers.permissions import CustomerPermissions as _CUST

# ── base grants shared by every CRM role (module access + own-scope search) ──
_BASE = (
    _CUST.ACCESS,
    _CUST.DASHBOARD_VIEW,
    _CUST.SEARCH,
)

CRM_VIEWER = _BASE + (
    _CUST.VIEW, _CUST.VIEW_COMPANY,
    _CRM.LEADS_VIEW, _CRM.OPPORTUNITIES_VIEW, _CRM.PIPELINE_VIEW,
    _CRM.ACTIVITIES_VIEW, _CRM.TASKS_VIEW, _CRM.NOTES_VIEW,
    _CRM.CASES_VIEW, _CRM.SLA_VIEW,
    _CRM.SEGMENTS_VIEW, _CRM.TAGS_VIEW,
)

CRM_AGENT = _BASE + (
    _CUST.VIEW, _CUST.VIEW_OWN,
    _CRM.LEADS_VIEW, _CRM.LEADS_VIEW_OWN,
    _CRM.ACTIVITIES_VIEW, _CRM.ACTIVITIES_CREATE, _CRM.ACTIVITIES_COMPLETE,
    _CRM.TASKS_VIEW, _CRM.TASKS_CREATE, _CRM.TASKS_COMPLETE,
    _CRM.NOTES_VIEW, _CRM.NOTES_CREATE,
)

CRM_SALES_REPRESENTATIVE = _BASE + (
    _CUST.VIEW, _CUST.VIEW_OWN, _CUST.CREATE, _CUST.EDIT_OWN,
    _CUST.CONTACT_VIEW, _CUST.CONTACT_CREATE, _CUST.CONTACT_EDIT,
    _CUST.ADDRESS_VIEW, _CUST.ADDRESS_CREATE, _CUST.ADDRESS_EDIT,
    _CRM.LEADS_VIEW_OWN, _CRM.LEADS_CREATE, _CRM.LEADS_EDIT,
    _CRM.LEADS_QUALIFY, _CRM.LEADS_DISQUALIFY, _CRM.LEADS_CONVERT,
    _CRM.OPPORTUNITIES_VIEW_OWN, _CRM.OPPORTUNITIES_CREATE, _CRM.OPPORTUNITIES_EDIT,
    _CRM.OPPORTUNITIES_CHANGE_STAGE, _CRM.OPPORTUNITIES_MARK_WON,
    _CRM.OPPORTUNITIES_MARK_LOST,
    _CRM.ACTIVITIES_VIEW, _CRM.ACTIVITIES_CREATE, _CRM.ACTIVITIES_EDIT,
    _CRM.ACTIVITIES_COMPLETE, _CRM.ACTIVITIES_CANCEL,
    _CRM.TASKS_VIEW, _CRM.TASKS_CREATE, _CRM.TASKS_COMPLETE,
    _CRM.NOTES_VIEW, _CRM.NOTES_CREATE, _CRM.NOTES_EDIT_OWN, _CRM.NOTES_DELETE_OWN,
    # sin crédito, sin privacidad, sin merge (§72)
)

CRM_SALES_SUPERVISOR = CRM_SALES_REPRESENTATIVE + (
    _CUST.VIEW_TEAM,
    _CRM.LEADS_VIEW_TEAM, _CRM.LEADS_ASSIGN, _CRM.LEADS_REASSIGN,
    _CRM.OPPORTUNITIES_VIEW_TEAM, _CRM.OPPORTUNITIES_ASSIGN, _CRM.OPPORTUNITIES_REASSIGN,
    _CRM.PIPELINE_VIEW, _CRM.FORECAST_VIEW, _CRM.FORECAST_VIEW_TEAM,
    _CRM.ACTIVITIES_REASSIGN, _CRM.TASKS_ASSIGN, _CRM.TASKS_REASSIGN,
)

CRM_SALES_MANAGER = CRM_SALES_SUPERVISOR + (
    _CUST.VIEW_BRANCH, _CUST.VIEW_TERRITORY, _CUST.VIEW_PORTFOLIO,
    _CRM.FORECAST_VIEW_COMPANY,
    _CRM.SEGMENTS_VIEW, _CRM.SEGMENTS_CREATE, _CRM.SEGMENTS_EDIT,
    _CRM.SEGMENTS_ASSIGN, _CRM.SEGMENTS_REMOVE,
    _CRM.TERRITORIES_VIEW, _CRM.TERRITORIES_MANAGE,
    _CRM.PORTFOLIOS_VIEW, _CRM.PORTFOLIOS_MANAGE,
    _CRM.CUSTOMER_OWNER_VIEW, _CRM.CUSTOMER_OWNER_ASSIGN, _CRM.CUSTOMER_OWNER_REASSIGN,
)

CRM_ACCOUNT_MANAGER = _BASE + (
    _CUST.VIEW, _CUST.VIEW_PORTFOLIO, _CUST.EDIT_OWN,
    _CUST.CONTACT_VIEW, _CUST.CONTACT_CREATE, _CUST.CONTACT_EDIT,
    _CUST.CREDIT_VIEW_SUMMARY,
    _CRM.OPPORTUNITIES_VIEW_OWN, _CRM.OPPORTUNITIES_CREATE, _CRM.OPPORTUNITIES_EDIT,
    _CRM.ACTIVITIES_VIEW, _CRM.ACTIVITIES_CREATE, _CRM.ACTIVITIES_COMPLETE,
    _CRM.CUSTOMER_OWNER_VIEW,
)

CRM_CUSTOMER_SERVICE_AGENT = _BASE + (
    _CUST.VIEW, _CUST.VIEW_OWN,
    _CRM.CASES_VIEW, _CRM.CASES_VIEW_OWN, _CRM.CASES_CREATE, _CRM.CASES_EDIT,
    _CRM.CASES_RESOLVE,
    _CRM.SLA_VIEW,
    _CRM.NOTES_VIEW, _CRM.NOTES_CREATE,
    # sin crédito sensible (§72)
)

CRM_CUSTOMER_SERVICE_SUPERVISOR = CRM_CUSTOMER_SERVICE_AGENT + (
    _CUST.VIEW_TEAM,
    _CRM.CASES_VIEW_TEAM, _CRM.CASES_ASSIGN, _CRM.CASES_REASSIGN,
    _CRM.CASES_ESCALATE, _CRM.CASES_CLOSE, _CRM.CASES_REOPEN,
    _CRM.SLA_MANAGE, _CRM.SLA_OVERRIDE,
)

CRM_CREDIT_ANALYST = _BASE + (
    _CUST.VIEW,
    _CUST.CREDIT_VIEW, _CUST.CREDIT_VIEW_SUMMARY,
    _CUST.CREDIT_REQUEST, _CUST.CREDIT_REVIEW, _CUST.CREDIT_HISTORY_VIEW,
    # sin credito.aprobar / credito.limite.editar (§73: analista no aprueba)
)

CRM_CREDIT_MANAGER = CRM_CREDIT_ANALYST + (
    _CUST.CREDIT_VIEW_SENSITIVE,
    _CUST.CREDIT_APPROVE, _CUST.CREDIT_REJECT,
    _CUST.CREDIT_LIMIT_EDIT, _CUST.CREDIT_LIMIT_OVERRIDE,
    _CUST.CREDIT_SUSPEND, _CUST.CREDIT_BLOCK, _CUST.CREDIT_REOPEN,
    _CUST.CREDIT_EXPORT,
)

CRM_DATA_STEWARD = _BASE + (
    _CUST.VIEW, _CUST.VIEW_COMPANY,
    _CUST.DATA_QUALITY_VIEW, _CUST.DATA_QUALITY_RESOLVE,
    _CUST.DUPLICATES_VIEW, _CUST.DUPLICATES_REVIEW, _CUST.DUPLICATES_DISMISS,
    _CUST.DUPLICATES_MERGE,
    _CUST.IMPORT, _CUST.BULK_UPDATE,
    # sin importar.aprobar cuando la importación es sensible (§73)
)

CRM_PRIVACY_OFFICER = _BASE + (
    _CUST.VIEW,
    _CUST.CONSENT_VIEW, _CUST.CONSENT_CAPTURE, _CUST.CONSENT_WITHDRAW,
    _CUST.CONSENT_EVIDENCE_VIEW,
    _CUST.PRIVACY_REQUEST_VIEW, _CUST.PRIVACY_REQUEST_CREATE,
    _CUST.PRIVACY_REQUEST_PROCESS, _CUST.PRIVACY_REQUEST_APPROVE,
    _CUST.ANONYMIZE,
    _CUST.SENSITIVE_DATA_VIEW,
)

CRM_MARKETING_OPERATOR = _BASE + (
    _CUST.VIEW, _CUST.VIEW_COMPANY,
    _CRM.SEGMENTS_VIEW, _CRM.SEGMENTS_CREATE, _CRM.SEGMENTS_EDIT,
    _CRM.SEGMENTS_ASSIGN, _CRM.SEGMENTS_REMOVE,
    _CRM.TAGS_VIEW, _CRM.TAGS_CREATE, _CRM.TAGS_EDIT,
    _CRM.TAGS_ASSIGN, _CRM.TAGS_REMOVE,
    _CUST.CONSENT_VIEW,  # nunca envía sin consentimiento vigente
)

CRM_AUDITOR = _BASE + (
    _CUST.VIEW, _CUST.VIEW_COMPANY, _CUST.AUDIT_VIEW,
    _CUST.CREDIT_VIEW, _CUST.CREDIT_HISTORY_VIEW,
    _CUST.CONSENT_VIEW, _CUST.CONSENT_EVIDENCE_VIEW,
    _CUST.PRIVACY_REQUEST_VIEW,
    _CUST.DATA_QUALITY_VIEW, _CUST.DUPLICATES_VIEW,
    _CRM.LEADS_VIEW, _CRM.OPPORTUNITIES_VIEW, _CRM.PIPELINE_VIEW, _CRM.FORECAST_VIEW,
    _CRM.CASES_VIEW, _CRM.SLA_VIEW,
    # sin ninguna mutación (§72)
)

CRM_ADMINISTRATOR = _BASE + (
    _CUST.SETTINGS_VIEW, _CUST.SETTINGS_MANAGE,
    _CRM.SLA_MANAGE,
    _CRM.TERRITORIES_MANAGE, _CRM.PORTFOLIOS_MANAGE,
    # sin acceso automático a datos sensibles (§72) — sensible.ver /
    # credito.ver_sensible / consentimiento.evidencia.ver se otorgan aparte.
)

CRM_ROLE_MATRIX: dict[str, tuple[str, ...]] = {
    "CRM_VIEWER": CRM_VIEWER,
    "CRM_AGENT": CRM_AGENT,
    "CRM_SALES_REPRESENTATIVE": CRM_SALES_REPRESENTATIVE,
    "CRM_SALES_SUPERVISOR": CRM_SALES_SUPERVISOR,
    "CRM_SALES_MANAGER": CRM_SALES_MANAGER,
    "CRM_ACCOUNT_MANAGER": CRM_ACCOUNT_MANAGER,
    "CRM_CUSTOMER_SERVICE_AGENT": CRM_CUSTOMER_SERVICE_AGENT,
    "CRM_CUSTOMER_SERVICE_SUPERVISOR": CRM_CUSTOMER_SERVICE_SUPERVISOR,
    "CRM_CREDIT_ANALYST": CRM_CREDIT_ANALYST,
    "CRM_CREDIT_MANAGER": CRM_CREDIT_MANAGER,
    "CRM_DATA_STEWARD": CRM_DATA_STEWARD,
    "CRM_PRIVACY_OFFICER": CRM_PRIVACY_OFFICER,
    "CRM_MARKETING_OPERATOR": CRM_MARKETING_OPERATOR,
    "CRM_AUDITOR": CRM_AUDITOR,
    "CRM_ADMINISTRATOR": CRM_ADMINISTRATOR,
}
