"""Canonical domain event names for the gradual EventBus transition."""

from __future__ import annotations

from enum import Enum


class EventName(str, Enum):
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_CANCELLED = "SALE_CANCELLED"
    SALE_REFUNDED = "SALE_REFUNDED"
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    CUSTOMER_CREDIT_LIMIT_CHANGED = "CUSTOMER_CREDIT_LIMIT_CHANGED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED"
    INVENTORY_MOVEMENT_RECORDED = "INVENTORY_MOVEMENT_RECORDED"
    INVENTORY_STOCK_UPDATED = "INVENTORY_STOCK_UPDATED"
    INVENTORY_STOCK_LOW = "INVENTORY_STOCK_LOW"
    INVENTORY_RESERVED = "INVENTORY_RESERVED"
    INVENTORY_RELEASED = "INVENTORY_RELEASED"
    WASTE_REGISTERED = "WASTE_REGISTERED"
    WASTE_HIGH_VALUE_REGISTERED = "WASTE_HIGH_VALUE_REGISTERED"
    MEAT_PRODUCTION_COMPLETED = "MEAT_PRODUCTION_COMPLETED"
    MEAT_YIELD_VARIANCE_DETECTED = "MEAT_YIELD_VARIANCE_DETECTED"
    TRANSFER_DISPATCHED = "TRANSFER_DISPATCHED"
    TRANSFER_RECEIVED = "TRANSFER_RECEIVED"
    TRANSFER_DIFFERENCE_DETECTED = "TRANSFER_DIFFERENCE_DETECTED"
    DELIVERY_ORDER_CREATED = "DELIVERY_ORDER_CREATED"
    DELIVERY_DRIVER_ASSIGNED = "DELIVERY_DRIVER_ASSIGNED"
    DELIVERY_WEIGHT_ADJUSTED = "DELIVERY_WEIGHT_ADJUSTED"
    DELIVERY_ORDER_DELIVERED = "DELIVERY_ORDER_DELIVERED"
    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_APPROVED = "QUOTE_APPROVED"
    QUOTE_CONVERTED_TO_SALE = "QUOTE_CONVERTED_TO_SALE"
    LOYALTY_POINTS_EARNED = "LOYALTY_POINTS_EARNED"
    LOYALTY_POINTS_REDEEMED = "LOYALTY_POINTS_REDEEMED"
    LOYALTY_CARD_ASSIGNED = "LOYALTY_CARD_ASSIGNED"
    PURCHASE_PLAN_GENERATED = "PURCHASE_PLAN_GENERATED"
    PURCHASE_ORDER_CREATED = "PURCHASE_ORDER_CREATED"
    PURCHASE_RECEIVED = "PURCHASE_RECEIVED"
    CASH_SHIFT_OPENED = "CASH_SHIFT_OPENED"
    CASH_MOVEMENT_RECORDED = "CASH_MOVEMENT_RECORDED"
    CASH_Z_CUT_GENERATED = "CASH_Z_CUT_GENERATED"
    CASH_DIFFERENCE_DETECTED = "CASH_DIFFERENCE_DETECTED"
    ASSET_CREATED = "ASSET_CREATED"
    MAINTENANCE_SCHEDULED = "MAINTENANCE_SCHEDULED"
    MAINTENANCE_COMPLETED = "MAINTENANCE_COMPLETED"
    NOTIFICATION_REQUESTED = "NOTIFICATION_REQUESTED"
    TICKET_PRINT_REQUESTED = "TICKET_PRINT_REQUESTED"
    USER_PERMISSIONS_UPDATED = "USER_PERMISSIONS_UPDATED"
    ROLE_PERMISSIONS_UPDATED = "ROLE_PERMISSIONS_UPDATED"
    MODULE_ACCESS_UPDATED = "MODULE_ACCESS_UPDATED"

    # ── Finance bounded context (canonical) ─────────────────────────────
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    JOURNAL_ENTRY_CREATED = "JOURNAL_ENTRY_CREATED"
    JOURNAL_ENTRY_POSTED = "JOURNAL_ENTRY_POSTED"
    JOURNAL_ENTRY_REVERSED = "JOURNAL_ENTRY_REVERSED"

    FISCAL_PERIOD_OPENED = "FISCAL_PERIOD_OPENED"
    FISCAL_PERIOD_SOFT_CLOSED = "FISCAL_PERIOD_SOFT_CLOSED"
    FISCAL_PERIOD_CLOSED = "FISCAL_PERIOD_CLOSED"
    FISCAL_PERIOD_REOPENED = "FISCAL_PERIOD_REOPENED"

    RECEIVABLE_CREATED = "RECEIVABLE_CREATED"
    COLLECTION_REGISTERED = "COLLECTION_REGISTERED"
    COLLECTION_APPLIED = "COLLECTION_APPLIED"
    RECEIVABLE_SETTLED = "RECEIVABLE_SETTLED"

    PAYABLE_CREATED = "PAYABLE_CREATED"
    SUPPLIER_PAYMENT_SCHEDULED = "SUPPLIER_PAYMENT_SCHEDULED"
    SUPPLIER_PAYMENT_AUTHORIZED = "SUPPLIER_PAYMENT_AUTHORIZED"
    SUPPLIER_PAYMENT_EXECUTED = "SUPPLIER_PAYMENT_EXECUTED"

    TREASURY_TRANSFER_REGISTERED = "TREASURY_TRANSFER_REGISTERED"
    BANK_STATEMENT_IMPORTED = "BANK_STATEMENT_IMPORTED"
    BANK_TRANSACTION_RECONCILED = "BANK_TRANSACTION_RECONCILED"

    BUDGET_CREATED = "BUDGET_CREATED"
    BUDGET_APPROVED = "BUDGET_APPROVED"
    BUDGET_COMMITTED = "BUDGET_COMMITTED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"

    CAPITAL_CONTRIBUTION_REGISTERED = "CAPITAL_CONTRIBUTION_REGISTERED"
    FIXED_ASSET_CAPITALIZED = "FIXED_ASSET_CAPITALIZED"
    DEPRECIATION_POSTED = "DEPRECIATION_POSTED"

    COMMERCIAL_OBLIGATION_RECOGNIZED = "COMMERCIAL_OBLIGATION_RECOGNIZED"
    COMMERCIAL_OBLIGATION_REDEEMED = "COMMERCIAL_OBLIGATION_REDEEMED"
    COMMERCIAL_OBLIGATION_RELEASED = "COMMERCIAL_OBLIGATION_RELEASED"
    COMMERCIAL_OBLIGATION_REVERSED = "COMMERCIAL_OBLIGATION_REVERSED"
    COMMERCIAL_RECONCILIATION_DIFFERENCE_DETECTED = (
        "COMMERCIAL_RECONCILIATION_DIFFERENCE_DETECTED"
    )

    FINANCIAL_STATEMENTS_GENERATED = "FINANCIAL_STATEMENTS_GENERATED"

    # ── Operational events consumed by Finance ──────────────────────────
    SUPPLIER_INVOICE_REGISTERED = "SUPPLIER_INVOICE_REGISTERED"
    INVENTORY_ADJUSTMENT_REGISTERED = "INVENTORY_ADJUSTMENT_REGISTERED"
    CASH_SHIFT_CLOSED = "CASH_SHIFT_CLOSED"
    PAYROLL_PAID = "PAYROLL_PAID"

    LOYALTY_POINTS_ISSUED = "LOYALTY_POINTS_ISSUED"
    LOYALTY_POINTS_EXPIRED = "LOYALTY_POINTS_EXPIRED"
    LOYALTY_REWARD_GRANTED = "LOYALTY_REWARD_GRANTED"
    LOYALTY_TRANSACTION_REVERSED = "LOYALTY_TRANSACTION_REVERSED"

    COUPON_ISSUED = "COUPON_ISSUED"
    COUPON_REDEEMED = "COUPON_REDEEMED"
    COUPON_EXPIRED = "COUPON_EXPIRED"
    COUPON_CANCELLED = "COUPON_CANCELLED"

    VOUCHER_ISSUED = "VOUCHER_ISSUED"
    VOUCHER_REDEEMED = "VOUCHER_REDEEMED"
    VOUCHER_EXPIRED = "VOUCHER_EXPIRED"
    VOUCHER_CANCELLED = "VOUCHER_CANCELLED"

    GIFT_CARD_SOLD = "GIFT_CARD_SOLD"
    GIFT_CARD_RELOADED = "GIFT_CARD_RELOADED"
    GIFT_CARD_REDEEMED = "GIFT_CARD_REDEEMED"
    GIFT_CARD_REFUNDED = "GIFT_CARD_REFUNDED"
    GIFT_CARD_EXPIRED = "GIFT_CARD_EXPIRED"

    STORE_CREDIT_CREATED = "STORE_CREDIT_CREATED"
    STORE_CREDIT_APPLIED = "STORE_CREDIT_APPLIED"
    STORE_CREDIT_EXPIRED = "STORE_CREDIT_EXPIRED"

    PROMOTIONAL_BALANCE_GRANTED = "PROMOTIONAL_BALANCE_GRANTED"
    PROMOTIONAL_BALANCE_USED = "PROMOTIONAL_BALANCE_USED"
    PROMOTIONAL_BALANCE_EXPIRED = "PROMOTIONAL_BALANCE_EXPIRED"

    STORED_VALUE_ADJUSTED = "STORED_VALUE_ADJUSTED"

    # ── Human Resources bounded context (canonical) ─────────────────────
    EMPLOYEE_CREATED = "EMPLOYEE_CREATED"
    EMPLOYEE_UPDATED = "EMPLOYEE_UPDATED"
    EMPLOYEE_DEACTIVATED = "EMPLOYEE_DEACTIVATED"

    ATTENDANCE_PUNCH_REGISTERED = "ATTENDANCE_PUNCH_REGISTERED"
    ATTENDANCE_ENTRY_REGISTERED = "ATTENDANCE_ENTRY_REGISTERED"
    ATTENDANCE_EXIT_REGISTERED = "ATTENDANCE_EXIT_REGISTERED"
    ATTENDANCE_INCIDENT_CREATED = "ATTENDANCE_INCIDENT_CREATED"
    ATTENDANCE_ADJUSTMENT_REQUESTED = "ATTENDANCE_ADJUSTMENT_REQUESTED"
    ATTENDANCE_ADJUSTMENT_APPROVED = "ATTENDANCE_ADJUSTMENT_APPROVED"

    WORK_SHIFT_CREATED = "WORK_SHIFT_CREATED"
    WORK_SHIFT_ASSIGNED = "WORK_SHIFT_ASSIGNED"

    LEAVE_REQUESTED = "LEAVE_REQUESTED"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"

    PAYROLL_RUN_GENERATED = "PAYROLL_RUN_GENERATED"
    PAYROLL_RUN_AUTHORIZED = "PAYROLL_RUN_AUTHORIZED"
    PAYROLL_CANCELLED = "PAYROLL_CANCELLED"


CRITICAL_EVENT_NAMES = frozenset(EventName)
