"""Canonical domain event names for the gradual EventBus transition."""

from __future__ import annotations

from enum import Enum


class EventName(str, Enum):
    SALE_COMPLETED = "SALE_COMPLETED"
    SALE_CANCELLED = "SALE_CANCELLED"
    SALE_REFUNDED = "SALE_REFUNDED"
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    CUSTOMER_CREDIT_LIMIT_CHANGED = "CUSTOMER_CREDIT_LIMIT_CHANGED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_PRICE_CHANGED = "PRODUCT_PRICE_CHANGED"
    INVENTORY_MOVEMENT_RECORDED = "INVENTORY_MOVEMENT_RECORDED"
    INVENTORY_STOCK_LOW = "INVENTORY_STOCK_LOW"
    INVENTORY_RESERVED = "INVENTORY_RESERVED"
    INVENTORY_RELEASED = "INVENTORY_RELEASED"
    WASTE_REGISTERED = "WASTE_REGISTERED"
    WASTE_HIGH_VALUE_REGISTERED = "WASTE_HIGH_VALUE_REGISTERED"
    MEAT_PRODUCTION_COMPLETED = "MEAT_PRODUCTION_COMPLETED"
    MEAT_YIELD_VARIANCE_DETECTED = "MEAT_YIELD_VARIANCE_DETECTED"
    TRANSFER_DISPATCHED = "TRANSFER_DISPATCHED"
    TRANSFER_RECEIVED = "TRANSFER_RECEIVED"
    TRANSFER_DIFFERENCE_DETECTED = "TRANSFER_DIFFERENCE_DETECTED"
    DELIVERY_ORDER_CREATED = "DELIVERY_ORDER_CREATED"
    DELIVERY_DRIVER_ASSIGNED = "DELIVERY_DRIVER_ASSIGNED"
    DELIVERY_WEIGHT_ADJUSTED = "DELIVERY_WEIGHT_ADJUSTED"
    DELIVERY_ORDER_DELIVERED = "DELIVERY_ORDER_DELIVERED"
    QUOTE_CREATED = "QUOTE_CREATED"
    QUOTE_APPROVED = "QUOTE_APPROVED"
    QUOTE_CONVERTED_TO_SALE = "QUOTE_CONVERTED_TO_SALE"
    LOYALTY_POINTS_EARNED = "LOYALTY_POINTS_EARNED"
    LOYALTY_POINTS_REDEEMED = "LOYALTY_POINTS_REDEEMED"
    LOYALTY_CARD_ASSIGNED = "LOYALTY_CARD_ASSIGNED"
    PURCHASE_PLAN_GENERATED = "PURCHASE_PLAN_GENERATED"
    PURCHASE_ORDER_CREATED = "PURCHASE_ORDER_CREATED"
    PURCHASE_RECEIVED = "PURCHASE_RECEIVED"
    CASH_SHIFT_OPENED = "CASH_SHIFT_OPENED"
    CASH_MOVEMENT_RECORDED = "CASH_MOVEMENT_RECORDED"
    CASH_Z_CUT_GENERATED = "CASH_Z_CUT_GENERATED"
    CASH_DIFFERENCE_DETECTED = "CASH_DIFFERENCE_DETECTED"
    ASSET_CREATED = "ASSET_CREATED"
    MAINTENANCE_SCHEDULED = "MAINTENANCE_SCHEDULED"
    MAINTENANCE_COMPLETED = "MAINTENANCE_COMPLETED"
    NOTIFICATION_REQUESTED = "NOTIFICATION_REQUESTED"
    TICKET_PRINT_REQUESTED = "TICKET_PRINT_REQUESTED"


CRITICAL_EVENT_NAMES = frozenset(EventName)
