"""Repository ports for the Document Output bounded context — SET-11.
Protocols only — implementations land in
``backend/infrastructure/db/repositories/document_output/``. Every id is
a UUIDv7 string. Mirrors backend/domain/settings/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.document_output.entities.document_number_sequence import DocumentNumberSequence
from backend.domain.document_output.entities.document_template import DocumentTemplate
from backend.domain.document_output.entities.document_template_version import DocumentTemplateVersion
from backend.domain.document_output.entities.marketing_campaign import MarketingCampaign
from backend.domain.document_output.entities.print_job import PrintJob
from backend.domain.document_output.enums import DocumentType, MarketingMessageCategory, PrintJobStatus
from backend.domain.document_output.value_objects.document_number import DocumentNumber


class DocumentTemplateRepositoryPort(Protocol):
    def save(self, template: DocumentTemplate) -> None: ...
    def get(self, template_id: str) -> DocumentTemplate | None: ...
    def list_by_document_type(self, document_type: DocumentType) -> list[DocumentTemplate]: ...
    def list_active(self) -> list[DocumentTemplate]: ...
    def list_all(self) -> list[DocumentTemplate]: ...


class DocumentTemplateVersionRepositoryPort(Protocol):
    def save(self, version: DocumentTemplateVersion) -> None: ...
    def get(self, version_id: str) -> DocumentTemplateVersion | None: ...
    def list_for_template(self, template_id: str) -> list[DocumentTemplateVersion]: ...
    def get_active_for_template(self, template_id: str) -> DocumentTemplateVersion | None: ...


class PrintJobRepositoryPort(Protocol):
    def save(self, job: PrintJob, *, operation_id: str | None = None) -> None: ...
    def get(self, job_id: str) -> PrintJob | None: ...
    def list_by_status(self, status: PrintJobStatus) -> list[PrintJob]: ...
    def get_by_operation_id(self, operation_id: str) -> PrintJob | None: ...
    def list_by_source(self, source_module: str, source_document_id: str) -> list[PrintJob]: ...


class MarketingCampaignRepositoryPort(Protocol):
    def save(self, campaign: MarketingCampaign) -> None: ...
    def get(self, campaign_id: str) -> MarketingCampaign | None: ...
    def get_by_code(self, code: str) -> MarketingCampaign | None: ...
    def list_active(self) -> list[MarketingCampaign]: ...
    def list_active_by_category(self, category: MarketingMessageCategory) -> list[MarketingCampaign]: ...
    def list_all(self) -> list[MarketingCampaign]: ...


class DocumentNumberSequenceRepositoryPort(Protocol):
    def save(self, sequence: DocumentNumberSequence) -> None: ...
    def get(self, sequence_id: str) -> DocumentNumberSequence | None: ...
    def get_by_prefix(self, prefix: str) -> DocumentNumberSequence | None: ...


class DocumentNumberReservationRepositoryPort(Protocol):
    def save(self, sequence_id: str, operation_id: str, document_number: DocumentNumber) -> None: ...
    def get_by_operation_id(self, sequence_id: str, operation_id: str) -> DocumentNumber | None: ...
