"""Granular permission catalog for Losses.

Read access never implies mutation or approval. The legacy ``MERMA.*`` codes are
intentionally absent and remain explicit migration debt until the desktop cutover.
"""


class LossPermissions:
    ACCESS = "LOSSES_ACCESS"
    VIEW = "LOSSES_VIEW"
    VIEW_OWN_BRANCH = "LOSSES_VIEW_OWN_BRANCH"
    VIEW_ASSIGNED_BRANCHES = "LOSSES_VIEW_ASSIGNED_BRANCHES"
    VIEW_ALL_BRANCHES = "LOSSES_VIEW_ALL_BRANCHES"
    VIEW_COST = "LOSSES_VIEW_COST"
    VIEW_AUDIT = "LOSSES_VIEW_AUDIT"
    EXPORT = "LOSSES_EXPORT"

    REPORT = "LOSSES_REPORT"
    EDIT_DRAFT = "LOSSES_EDIT_DRAFT"
    SUBMIT = "LOSSES_SUBMIT"
    REVIEW = "LOSSES_REVIEW"
    APPROVE = "LOSSES_APPROVE"
    REJECT = "LOSSES_REJECT"
    POST_INVENTORY = "LOSSES_POST_INVENTORY"
    REVERSE_INVENTORY = "LOSSES_REVERSE_INVENTORY"
    CLOSE = "LOSSES_CLOSE"
    REOPEN = "LOSSES_REOPEN"

    APPROVE_OVER_LIMIT = "LOSSES_APPROVE_OVER_LIMIT"
    AUTHORIZE_DISPOSAL = "LOSSES_AUTHORIZE_DISPOSAL"
    COMPLETE_DISPOSAL = "LOSSES_COMPLETE_DISPOSAL"
    RECORD_RECOVERY = "LOSSES_RECORD_RECOVERY"
    APPROVE_RECOVERY = "LOSSES_APPROVE_RECOVERY"

    OPEN_INVESTIGATION = "LOSSES_OPEN_INVESTIGATION"
    INVESTIGATE = "LOSSES_INVESTIGATE"
    CONCLUDE_INVESTIGATION = "LOSSES_CONCLUDE_INVESTIGATION"
    MANAGE_ROOT_CAUSE = "LOSSES_MANAGE_ROOT_CAUSE"
    CREATE_CORRECTIVE_ACTION = "LOSSES_CREATE_CORRECTIVE_ACTION"
    VERIFY_CORRECTIVE_ACTION = "LOSSES_VERIFY_CORRECTIVE_ACTION"

    MANAGE_CLASSIFICATIONS = "LOSSES_MANAGE_CLASSIFICATIONS"
    MANAGE_REASONS = "LOSSES_MANAGE_REASONS"
    MANAGE_POLICIES = "LOSSES_MANAGE_POLICIES"
    MANAGE_NOTIFICATIONS = "LOSSES_MANAGE_NOTIFICATIONS"


ALL_LOSS_PERMISSIONS = frozenset(
    value for name, value in vars(LossPermissions).items()
    if not name.startswith("_") and isinstance(value, str)
)
