"""Granular permission catalog for Losses.

Read access never implies mutation or approval. The legacy ``MERMA.*`` codes are
intentionally absent and remain explicit migration debt until the desktop cutover.
"""


class LossPermissions:
    ACCESS = "LOSSES_ACCESS"
    VIEW = "LOSSES_VIEW"
    VIEW_OWN_BRANCH = "LOSSES_VIEW_OWN_BRANCH"
    VIEW_ASSIGNED_BRANCHES = "LOSSES_VIEW_ASSIGNED_BRANCHES"
    VIEW_ALL_BRANCHES = "LOSSES_VIEW_ALL_BRANCHES"
    VIEW_COST = "LOSSES_VIEW_COST"
    VIEW_AUDIT = "LOSSES_VIEW_AUDIT"
    EXPORT = "LOSSES_EXPORT"

    OVERVIEW_VIEW = "LOSSES_OVERVIEW_VIEW"
    REGISTRATION_VIEW = "LOSSES_REGISTRATION_VIEW"
    PENDING_VIEW = "LOSSES_PENDING_VIEW"
    PRODUCTION_VIEW = "LOSSES_PRODUCTION_VIEW"
    INVENTORY_VIEW = "LOSSES_INVENTORY_VIEW"
    EXPIRY_DAMAGE_VIEW = "LOSSES_EXPIRY_DAMAGE_VIEW"
    QUALITY_VIEW = "LOSSES_QUALITY_VIEW"
    YIELD_VIEW = "LOSSES_YIELD_VIEW"
    RECOVERY_VIEW = "LOSSES_RECOVERY_VIEW"
    DISPOSITION_VIEW = "LOSSES_DISPOSITION_VIEW"
    INVESTIGATION_VIEW = "LOSSES_INVESTIGATION_VIEW"
    CORRECTIVE_ACTION_VIEW = "LOSSES_CORRECTIVE_ACTION_VIEW"
    ALERT_VIEW = "LOSSES_ALERT_VIEW"
    ANALYTICS_VIEW = "LOSSES_ANALYTICS_VIEW"
    SETTINGS_VIEW = "LOSSES_SETTINGS_VIEW"

    REPORT = "LOSSES_REPORT"
    EDIT_DRAFT = "LOSSES_EDIT_DRAFT"
    SUBMIT = "LOSSES_SUBMIT"
    REVIEW = "LOSSES_REVIEW"
    APPROVE = "LOSSES_APPROVE"
    REJECT = "LOSSES_REJECT"
    POST_INVENTORY = "LOSSES_POST_INVENTORY"
    REVERSE_INVENTORY = "LOSSES_REVERSE_INVENTORY"
    VALUE_LOSS = "LOSSES_VALUE_LOSS"
    CLOSE = "LOSSES_CLOSE"
    REOPEN = "LOSSES_REOPEN"

    APPROVE_OVER_LIMIT = "LOSSES_APPROVE_OVER_LIMIT"
    PLAN_DISPOSAL = "LOSSES_PLAN_DISPOSAL"
    AUTHORIZE_DISPOSAL = "LOSSES_AUTHORIZE_DISPOSAL"
    COMPLETE_DISPOSAL = "LOSSES_COMPLETE_DISPOSAL"
    RECORD_RECOVERY = "LOSSES_RECORD_RECOVERY"
    APPROVE_RECOVERY = "LOSSES_APPROVE_RECOVERY"
    QUALITY_REJECT = "LOSSES_QUALITY_REJECT"
    QUALITY_CONDEMN = "LOSSES_QUALITY_CONDEMN"
    TRANSFER_LINK = "LOSSES_TRANSFER_LINK"
    MANAGE_CLAIMS = "LOSSES_MANAGE_CLAIMS"

    OPEN_INVESTIGATION = "LOSSES_OPEN_INVESTIGATION"
    INVESTIGATE = "LOSSES_INVESTIGATE"
    CONCLUDE_INVESTIGATION = "LOSSES_CONCLUDE_INVESTIGATION"
    MANAGE_ROOT_CAUSE = "LOSSES_MANAGE_ROOT_CAUSE"
    CREATE_CORRECTIVE_ACTION = "LOSSES_CREATE_CORRECTIVE_ACTION"
    VERIFY_CORRECTIVE_ACTION = "LOSSES_VERIFY_CORRECTIVE_ACTION"

    MANAGE_CLASSIFICATIONS = "LOSSES_MANAGE_CLASSIFICATIONS"
    MANAGE_REASONS = "LOSSES_MANAGE_REASONS"
    MANAGE_POLICIES = "LOSSES_MANAGE_POLICIES"
    MANAGE_NOTIFICATIONS = "LOSSES_MANAGE_NOTIFICATIONS"


ALL_LOSS_PERMISSIONS = frozenset(
    value for name, value in vars(LossPermissions).items()
    if not name.startswith("_") and isinstance(value, str)
)
