"""Repository ports for the Assets / EAM bounded context.

Protocols only — implementations land in
``backend/infrastructure/db/repositories/assets/`` in a later ASSET phase.
Every id is a UUIDv7 string.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.assets.entities.asset import Asset
from backend.domain.assets.entities.asset_assignment import AssetAssignment
from backend.domain.assets.entities.asset_capitalization_proposal import (
    AssetCapitalizationProposal,
)
from backend.domain.assets.entities.asset_category import AssetCategory
from backend.domain.assets.entities.asset_disposal import AssetDisposal
from backend.domain.assets.entities.asset_disposal_request import AssetDisposalRequest
from backend.domain.assets.entities.asset_document import AssetDocument
from backend.domain.assets.entities.asset_improvement import AssetImprovement
from backend.domain.assets.entities.asset_inspection import AssetInspection
from backend.domain.assets.entities.asset_insurance_policy import AssetInsurancePolicy
from backend.domain.assets.entities.asset_loan import AssetLoan
from backend.domain.assets.entities.asset_location import AssetLocation
from backend.domain.assets.entities.asset_meter import AssetMeter
from backend.domain.assets.entities.asset_meter_reading import AssetMeterReading
from backend.domain.assets.entities.asset_physical_discrepancy import AssetPhysicalDiscrepancy
from backend.domain.assets.entities.asset_physical_inventory import AssetPhysicalInventory
from backend.domain.assets.entities.asset_physical_inventory_line import (
    AssetPhysicalInventoryLine,
)
from backend.domain.assets.entities.asset_sync_conflict import AssetSyncConflict
from backend.domain.assets.entities.asset_tag import AssetTag
from backend.domain.assets.entities.asset_transfer import AssetTransfer
from backend.domain.assets.entities.asset_warranty import AssetWarranty
from backend.domain.assets.entities.inspection_checklist_template import (
    InspectionChecklistTemplate,
)
from backend.domain.assets.entities.maintenance_plan import MaintenancePlan
from backend.domain.assets.entities.maintenance_work_order import MaintenanceWorkOrder


class AssetRepositoryPort(Protocol):
    def save(self, asset: Asset) -> None: ...
    def update(self, asset: Asset) -> None: ...
    def get(self, asset_id: str) -> Asset | None: ...
    def get_by_asset_number(self, asset_number: str) -> Asset | None: ...
    def find_by_operation_id(self, operation_id: str) -> Asset | None: ...
    def list_by_branch(self, branch_id: str) -> list[Asset]: ...
    def list_by_custodian(self, user_id: str) -> list[Asset]: ...
    def list_all(self) -> list[Asset]: ...


class AssetCategoryRepositoryPort(Protocol):
    def save(self, category: AssetCategory) -> None: ...
    def update(self, category: AssetCategory) -> None: ...
    def get(self, category_id: str) -> AssetCategory | None: ...
    def get_by_code(self, code: str) -> AssetCategory | None: ...
    def list_active(self) -> list[AssetCategory]: ...
    def list_all(self) -> list[AssetCategory]: ...


class AssetLocationRepositoryPort(Protocol):
    def save(self, location: AssetLocation) -> None: ...
    def update(self, location: AssetLocation) -> None: ...
    def get(self, location_id: str) -> AssetLocation | None: ...
    def list_by_branch(self, branch_id: str) -> list[AssetLocation]: ...
    def list_children(self, parent_location_id: str) -> list[AssetLocation]: ...


class AssetAssignmentRepositoryPort(Protocol):
    def save(self, assignment: AssetAssignment) -> None: ...
    def update(self, assignment: AssetAssignment) -> None: ...
    def get(self, assignment_id: str) -> AssetAssignment | None: ...
    def get_active_for_asset(self, asset_id: str) -> AssetAssignment | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetAssignment]: ...
    def list_active_by_employee(self, employee_id: str) -> list[AssetAssignment]: ...


class AssetLoanRepositoryPort(Protocol):
    def save(self, loan: AssetLoan) -> None: ...
    def update(self, loan: AssetLoan) -> None: ...
    def get(self, loan_id: str) -> AssetLoan | None: ...
    def list_active(self) -> list[AssetLoan]: ...
    def list_overdue(self) -> list[AssetLoan]: ...


class AssetTransferRepositoryPort(Protocol):
    def save(self, transfer: AssetTransfer) -> None: ...
    def update(self, transfer: AssetTransfer) -> None: ...
    def get(self, transfer_id: str) -> AssetTransfer | None: ...
    def find_by_operation_id(self, operation_id: str) -> AssetTransfer | None: ...
    def list_pending_for_branch(self, branch_id: str) -> list[AssetTransfer]: ...


class MaintenancePlanRepositoryPort(Protocol):
    def save(self, plan: MaintenancePlan) -> None: ...
    def update(self, plan: MaintenancePlan) -> None: ...
    def get(self, plan_id: str) -> MaintenancePlan | None: ...
    def list_active(self) -> list[MaintenancePlan]: ...
    def list_due(self, *, as_of: str) -> list[MaintenancePlan]: ...


class MaintenanceWorkOrderRepositoryPort(Protocol):
    def save(self, work_order: MaintenanceWorkOrder) -> None: ...
    def update(self, work_order: MaintenanceWorkOrder) -> None: ...
    def get(self, work_order_id: str) -> MaintenanceWorkOrder | None: ...
    def get_by_work_order_number(self, work_order_number: str) -> MaintenanceWorkOrder | None: ...
    def find_by_operation_id(self, operation_id: str) -> MaintenanceWorkOrder | None: ...
    def list_open_for_asset(self, asset_id: str) -> list[MaintenanceWorkOrder]: ...
    def list_by_status(self, status: str) -> list[MaintenanceWorkOrder]: ...
    def list_all_open(self, *, branch_id: str | None = None) -> list[MaintenanceWorkOrder]: ...


class InspectionChecklistTemplateRepositoryPort(Protocol):
    def save(self, template: InspectionChecklistTemplate) -> None: ...
    def update(self, template: InspectionChecklistTemplate) -> None: ...
    def get(self, template_id: str) -> InspectionChecklistTemplate | None: ...
    def list_active(self, *, inspection_type: str | None = None) -> list[InspectionChecklistTemplate]: ...


class AssetInspectionRepositoryPort(Protocol):
    def save(self, inspection: AssetInspection) -> None: ...
    def update(self, inspection: AssetInspection) -> None: ...
    def get(self, inspection_id: str) -> AssetInspection | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetInspection]: ...
    def list_failed(self) -> list[AssetInspection]: ...


class AssetMeterRepositoryPort(Protocol):
    def save(self, meter: AssetMeter) -> None: ...
    def update(self, meter: AssetMeter) -> None: ...
    def get(self, meter_id: str) -> AssetMeter | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetMeter]: ...


class AssetMeterReadingRepositoryPort(Protocol):
    def save(self, reading: AssetMeterReading) -> None: ...
    def get(self, reading_id: str) -> AssetMeterReading | None: ...
    def list_by_meter(self, meter_id: str) -> list[AssetMeterReading]: ...
    def get_latest(self, meter_id: str) -> AssetMeterReading | None: ...


class AssetDocumentRepositoryPort(Protocol):
    def save(self, document: AssetDocument) -> None: ...
    def get(self, document_id: str) -> AssetDocument | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetDocument]: ...
    def delete(self, document_id: str) -> None: ...


class AssetWarrantyRepositoryPort(Protocol):
    def save(self, warranty: AssetWarranty) -> None: ...
    def update(self, warranty: AssetWarranty) -> None: ...
    def get(self, warranty_id: str) -> AssetWarranty | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetWarranty]: ...
    def list_expiring(self, *, within_days: int = 30) -> list[AssetWarranty]: ...


class AssetInsurancePolicyRepositoryPort(Protocol):
    def save(self, policy: AssetInsurancePolicy) -> None: ...
    def update(self, policy: AssetInsurancePolicy) -> None: ...
    def get(self, policy_id: str) -> AssetInsurancePolicy | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetInsurancePolicy]: ...


class AssetImprovementRepositoryPort(Protocol):
    def save(self, improvement: AssetImprovement) -> None: ...
    def update(self, improvement: AssetImprovement) -> None: ...
    def get(self, improvement_id: str) -> AssetImprovement | None: ...
    def list_by_asset(self, asset_id: str) -> list[AssetImprovement]: ...


class AssetCapitalizationProposalRepositoryPort(Protocol):
    def save(self, proposal: AssetCapitalizationProposal) -> None: ...
    def update(self, proposal: AssetCapitalizationProposal) -> None: ...
    def get(self, proposal_id: str) -> AssetCapitalizationProposal | None: ...
    def find_by_operation_id(self, operation_id: str) -> AssetCapitalizationProposal | None: ...
    def list_pending_review(self) -> list[AssetCapitalizationProposal]: ...


class AssetPhysicalInventoryRepositoryPort(Protocol):
    def save(self, count: AssetPhysicalInventory) -> None: ...
    def update(self, count: AssetPhysicalInventory) -> None: ...
    def get(self, count_id: str) -> AssetPhysicalInventory | None: ...
    def list_open_for_branch(self, branch_id: str) -> list[AssetPhysicalInventory]: ...


class AssetPhysicalInventoryLineRepositoryPort(Protocol):
    def save(self, line: AssetPhysicalInventoryLine) -> None: ...
    def list_by_inventory(self, physical_inventory_id: str) -> list[AssetPhysicalInventoryLine]: ...


class AssetPhysicalDiscrepancyRepositoryPort(Protocol):
    def save(self, discrepancy: AssetPhysicalDiscrepancy) -> None: ...
    def update(self, discrepancy: AssetPhysicalDiscrepancy) -> None: ...
    def get(self, discrepancy_id: str) -> AssetPhysicalDiscrepancy | None: ...
    def list_open(self) -> list[AssetPhysicalDiscrepancy]: ...


class AssetDisposalRequestRepositoryPort(Protocol):
    def save(self, request: AssetDisposalRequest) -> None: ...
    def update(self, request: AssetDisposalRequest) -> None: ...
    def get(self, request_id: str) -> AssetDisposalRequest | None: ...
    def find_by_operation_id(self, operation_id: str) -> AssetDisposalRequest | None: ...
    def list_pending_review(self) -> list[AssetDisposalRequest]: ...


class AssetDisposalRepositoryPort(Protocol):
    def save(self, disposal: AssetDisposal) -> None: ...
    def get(self, disposal_id: str) -> AssetDisposal | None: ...
    def get_by_request(self, disposal_request_id: str) -> AssetDisposal | None: ...


class AssetTagRepositoryPort(Protocol):
    def save(self, tag: AssetTag) -> None: ...
    def update(self, tag: AssetTag) -> None: ...
    def get(self, tag_id: str) -> AssetTag | None: ...
    def get_by_qr_token(self, qr_public_token: str) -> AssetTag | None: ...
    def get_by_tag_number(self, tag_number: str) -> AssetTag | None: ...
    def list_active_for_asset(self, asset_id: str) -> list[AssetTag]: ...


class AssetSyncConflictRepositoryPort(Protocol):
    """No implementation exists — see asset_sync_conflict.py's module
    docstring. Declared for the same forward-looking reason every other
    Protocol port in this file was declared before infrastructure existed."""

    def save(self, conflict: AssetSyncConflict) -> None: ...
    def update(self, conflict: AssetSyncConflict) -> None: ...
    def get(self, conflict_id: str) -> AssetSyncConflict | None: ...
    def list_open(self) -> list[AssetSyncConflict]: ...


class ProcessedEventRepositoryPort(Protocol):
    """Idempotency registry for consumed operational events (§88)."""

    def was_processed(self, event_id: str) -> bool: ...
    def mark_processed(self, event_id: str, event_name: str, operation_id: str) -> None: ...


class OutboxRepositoryPort(Protocol):
    """Transactional outbox for events Assets publishes (§87)."""

    def enqueue(self, event_id: str, event_name: str, payload_json: str, operation_id: str) -> None: ...
    def list_pending(self, limit: int = 100) -> list[dict]: ...
    def mark_dispatched(self, outbox_id: str) -> None: ...
