"""Granular permission catalog.  Use cases must validate these server-side."""
class TransferPermissions:
    ACCESS = "TRANSFERS_ACCESS"; DASHBOARD_VIEW = "TRANSFERS_DASHBOARD_VIEW"
    VIEW_OWN_BRANCH = "TRANSFERS_VIEW_OWN_BRANCH"; VIEW_ASSIGNED_BRANCHES = "TRANSFERS_VIEW_ASSIGNED_BRANCHES"; VIEW_ALL_BRANCHES = "TRANSFERS_VIEW_ALL_BRANCHES"; EXPORT = "TRANSFERS_EXPORT"; AUDIT_VIEW = "TRANSFERS_AUDIT_VIEW"
    REQUEST_VIEW = "TRANSFERS_REQUEST_VIEW"; REQUEST_CREATE = "TRANSFERS_REQUEST_CREATE"; REQUEST_EDIT = "TRANSFERS_REQUEST_EDIT"; REQUEST_SUBMIT = "TRANSFERS_REQUEST_SUBMIT"; REQUEST_CANCEL = "TRANSFERS_REQUEST_CANCEL"
    APPROVE = "TRANSFERS_APPROVE"; REJECT = "TRANSFERS_REJECT"; PARTIAL_APPROVE = "TRANSFERS_PARTIAL_APPROVE"; OVERRIDE_LIMIT = "TRANSFERS_OVERRIDE_LIMIT"
    RESERVE = "TRANSFERS_RESERVE"; ALLOCATE = "TRANSFERS_ALLOCATE"; PICK = "TRANSFERS_PICK"; PICK_OVERRIDE_LOT = "TRANSFERS_PICK_OVERRIDE_LOT"; PICK_CONFIRM = "TRANSFERS_PICK_CONFIRM"
    DISPATCH_VIEW = "TRANSFERS_DISPATCH_VIEW"; DISPATCH = "TRANSFERS_DISPATCH"; PARTIAL_DISPATCH = "TRANSFERS_PARTIAL_DISPATCH"; CANCEL_SHIPMENT = "TRANSFERS_CANCEL_SHIPMENT"
    RECEIVE_VIEW = "TRANSFERS_RECEIVE_VIEW"; RECEIVE = "TRANSFERS_RECEIVE"; PARTIAL_RECEIVE = "TRANSFERS_PARTIAL_RECEIVE"; BLIND_RECEIVE = "TRANSFERS_BLIND_RECEIVE"; RECEIVE_OVER_TOLERANCE = "TRANSFERS_RECEIVE_OVER_TOLERANCE"; MANUAL_WEIGHT_OVERRIDE = "TRANSFERS_MANUAL_WEIGHT_OVERRIDE"
    DIFFERENCE_VIEW = "TRANSFERS_DIFFERENCE_VIEW"; DIFFERENCE_REVIEW = "TRANSFERS_DIFFERENCE_REVIEW"; DIFFERENCE_RESOLVE = "TRANSFERS_DIFFERENCE_RESOLVE"; DIFFERENCE_ACCEPT = "TRANSFERS_DIFFERENCE_ACCEPT"; DIFFERENCE_REJECT = "TRANSFERS_DIFFERENCE_REJECT"
    RETURN_CREATE = "TRANSFERS_RETURN_CREATE"; RETURN_APPROVE = "TRANSFERS_RETURN_APPROVE"; RETURN_DISPATCH = "TRANSFERS_RETURN_DISPATCH"; REVERSE = "TRANSFERS_REVERSE"
    PRINT = "TRANSFERS_PRINT"; REPRINT = "TRANSFERS_REPRINT"
    SETTINGS_VIEW = "TRANSFERS_SETTINGS_VIEW"; SETTINGS_MANAGE = "TRANSFERS_SETTINGS_MANAGE"; NOTIFICATIONS_MANAGE = "TRANSFERS_NOTIFICATIONS_MANAGE"; WHATSAPP_ALERTS_MANAGE = "TRANSFERS_WHATSAPP_ALERTS_MANAGE"


ALL_TRANSFER_PERMISSIONS = frozenset(value for name, value in vars(TransferPermissions).items() if name.isupper())
