"""Repository ports for the HR bounded context (Protocols only)."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from backend.domain.hr.entities import (
    AttendanceAdjustment,
    AttendancePunch,
    AttendanceWorkday,
    Department,
    Employee,
    LeaveRequest,
    PayrollPayment,
    PayrollRun,
    Position,
    ShiftAssignment,
    WorkShift,
)


class EmployeeRepositoryPort(Protocol):
    def save(self, employee: Employee) -> None: ...
    def update(self, employee: Employee) -> None: ...
    def get(self, employee_id: str) -> Employee | None: ...
    def get_by_code(self, employee_code: str) -> Employee | None: ...
    def get_by_user_id(self, user_id: str) -> Employee | None: ...
    def list_active(self, *, branch_id: str | None = None) -> list[Employee]: ...
    def list_all(self, *, limit: int = 200, offset: int = 0) -> list[Employee]: ...
    def link_user(self, user_id: str, employee_id: str) -> None: ...


class DepartmentRepositoryPort(Protocol):
    def save(self, department: Department) -> None: ...
    def get(self, department_id: str) -> Department | None: ...
    def list_active(self) -> list[Department]: ...


class PositionRepositoryPort(Protocol):
    def save(self, position: Position) -> None: ...
    def get(self, position_id: str) -> Position | None: ...
    def list_active(self) -> list[Position]: ...


class AttendanceRepositoryPort(Protocol):
    def save_punch(self, punch: AttendancePunch) -> None: ...
    def find_punch_by_operation_id(self, operation_id: str) -> AttendancePunch | None: ...
    def find_punch_by_source_reference(
        self, source: str, source_reference_id: str, punch_type: str,
    ) -> AttendancePunch | None: ...
    def list_punches_for_workday(self, workday_id: str) -> list[AttendancePunch]: ...
    def save_workday(self, workday: AttendanceWorkday) -> None: ...
    def update_workday(self, workday: AttendanceWorkday) -> None: ...
    def get_workday(self, workday_id: str) -> AttendanceWorkday | None: ...
    def find_workday(self, employee_id: str, work_date: date) -> AttendanceWorkday | None: ...
    def attach_punch_to_workday(self, punch_id: str, workday_id: str) -> None: ...
    def list_workdays(
        self, *, work_date: date | None = None, branch_id: str | None = None,
    ) -> list[AttendanceWorkday]: ...


class AttendanceAdjustmentRepositoryPort(Protocol):
    def save(self, adjustment: AttendanceAdjustment) -> None: ...
    def update(self, adjustment: AttendanceAdjustment) -> None: ...
    def get(self, adjustment_id: str) -> AttendanceAdjustment | None: ...
    def find_by_operation_id(self, operation_id: str) -> AttendanceAdjustment | None: ...
    def list_pending(self) -> list[AttendanceAdjustment]: ...


class WorkShiftRepositoryPort(Protocol):
    def save(self, shift: WorkShift) -> None: ...
    def get(self, shift_id: str) -> WorkShift | None: ...
    def list_active(self, *, branch_id: str | None = None) -> list[WorkShift]: ...
    def save_assignment(self, assignment: ShiftAssignment) -> None: ...
    def find_assignment_for(self, employee_id: str, on_date: date) -> ShiftAssignment | None: ...


class LeaveRepositoryPort(Protocol):
    def save(self, request: LeaveRequest) -> None: ...
    def update(self, request: LeaveRequest) -> None: ...
    def get(self, leave_id: str) -> LeaveRequest | None: ...
    def find_by_operation_id(self, operation_id: str) -> LeaveRequest | None: ...
    def list_by_employee(self, employee_id: str) -> list[LeaveRequest]: ...
    def list_pending(self) -> list[LeaveRequest]: ...


class PayrollRepositoryPort(Protocol):
    def save(self, run: PayrollRun) -> None: ...
    def update(self, run: PayrollRun) -> None: ...
    def get(self, run_id: str) -> PayrollRun | None: ...
    def find_by_operation_id(self, operation_id: str) -> PayrollRun | None: ...
    def list_runs(self, *, status: str | None = None) -> list[PayrollRun]: ...


class PayrollPaymentRepositoryPort(Protocol):
    def save(self, payment: PayrollPayment) -> None: ...
    def get(self, payment_id: str) -> PayrollPayment | None: ...
    def find_by_operation_id(self, operation_id: str) -> PayrollPayment | None: ...
    def find_by_run(self, payroll_run_id: str) -> PayrollPayment | None: ...


class HRProcessedEventRepositoryPort(Protocol):
    def was_processed(self, event_id: str) -> bool: ...
    def mark_processed(self, event_id: str, event_name: str, operation_id: str) -> None: ...


class HROutboxRepositoryPort(Protocol):
    def enqueue(self, event_id: str, event_name: str, payload_json: str, operation_id: str) -> None: ...
    def list_pending(self, limit: int = 100) -> list[dict]: ...
    def mark_dispatched(self, outbox_id: str) -> None: ...


class HRAuditRepositoryPort(Protocol):
    def record(self, *, action: str, actor_user_id: str | None, entity_type: str,
               entity_id: str | None, detail: str, operation_id: str | None = None) -> None: ...
