"""Repository ports for HR persistence implementations."""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import Protocol

from .enums import LeaveStatus, LeaveType
from .entities import (
    AttendanceAdjustment,
    AttendanceIncident,
    AttendancePunch,
    AttendanceWorkday,
    ContractTypeCatalogItem,
    Department,
    Employee,
    LeaveRequest,
    PayrollConcept,
    PayrollLine,
    PayrollPayment,
    PayrollRun,
    PaymentFrequencyCatalogItem,
    Position,
    RestDay,
    ShiftAssignment,
    ShiftTemplate,
    WorkShift,
)


class EmployeeRepositoryPort(Protocol):
    def get(self, employee_id: str) -> Employee | None: ...
    def save(self, employee: Employee) -> None: ...


class DepartmentRepositoryPort(Protocol):
    def save(self, department: Department) -> None: ...


class PositionRepositoryPort(Protocol):
    def save(self, position: Position) -> None: ...


class ContractTypeRepositoryPort(Protocol):
    def save(self, contract_type: ContractTypeCatalogItem) -> None: ...


class PaymentFrequencyRepositoryPort(Protocol):
    def save(self, payment_frequency: PaymentFrequencyCatalogItem) -> None: ...


class AttendanceRepositoryPort(Protocol):
    def add_punch(self, punch: AttendancePunch) -> None: ...
    def get_punch(self, punch_id: str) -> AttendancePunch | None: ...
    def get_punch_by_operation_id(self, operation_id: str) -> AttendancePunch | None: ...
    def get_punch_by_source_reference(
        self, source: str, source_reference_id: str, punch_type: str
    ) -> AttendancePunch | None: ...
    def list_punches_for_workday(
        self, *, employee_id: str, branch_id: str, work_date: date
    ) -> list[AttendancePunch]: ...
    def save_workday(self, workday: AttendanceWorkday) -> None: ...
    def get_workday(self, *, employee_id: str, branch_id: str, work_date: date) -> AttendanceWorkday | None: ...
    def add_incident(self, incident: AttendanceIncident) -> None: ...
    def list_incidents(self, *, employee_id: str, branch_id: str, work_date: date) -> list[AttendanceIncident]: ...


class AttendanceAdjustmentRepositoryPort(Protocol):
    def save(self, adjustment: AttendanceAdjustment) -> None: ...
    def get(self, adjustment_id: str) -> AttendanceAdjustment | None: ...
    def update_status(self, adjustment: AttendanceAdjustment) -> None: ...


class WorkShiftRepositoryPort(Protocol):
    def save(self, shift: WorkShift) -> None: ...
    def get(self, shift_id: str) -> WorkShift | None: ...
    def list_active(self, *, branch_id: str | None = None) -> list[WorkShift]: ...
    def assign(self, assignment: ShiftAssignment) -> None: ...
    def list_assignments(self, *, employee_id: str | None = None, branch_id: str | None = None) -> list[ShiftAssignment]: ...
    def save_template(self, template: ShiftTemplate) -> None: ...
    def list_templates(self, *, branch_id: str | None = None) -> list[ShiftTemplate]: ...
    def save_rest_day(self, rest_day: RestDay) -> None: ...
    def list_rest_days(self, *, employee_id: str | None = None, branch_id: str | None = None) -> list[RestDay]: ...


class LeaveRepositoryPort(Protocol):
    def save(self, leave_request: LeaveRequest) -> None: ...
    def update(self, leave_request: LeaveRequest) -> None: ...
    def get(self, leave_request_id: str) -> LeaveRequest | None: ...
    def get_by_operation_id(self, operation_id: str) -> LeaveRequest | None: ...
    def list_overlapping(self, *, employee_id: str, start_date: date, end_date: date, statuses: tuple[LeaveStatus, ...]) -> list[LeaveRequest]: ...
    def get_available_days(self, *, employee_id: str, branch_id: str, leave_type: LeaveType) -> Decimal: ...
    def debit_balance(self, *, employee_id: str, branch_id: str, leave_type: LeaveType, days: Decimal) -> None: ...
    def add_history(self, *, leave_request_id: str, previous_status: LeaveStatus | None, new_status: LeaveStatus, actor_user_id: str | None, reason: str | None, operation_id: str) -> str: ...


class PayrollRepositoryPort(Protocol):
    def save_run(self, payroll_run: PayrollRun) -> None: ...
    def update_run(self, payroll_run: PayrollRun) -> None: ...
    def get_run(self, payroll_run_id: str) -> PayrollRun | None: ...
    def get_run_by_operation_id(self, operation_id: str) -> PayrollRun | None: ...
    def save_line(self, payroll_line: PayrollLine) -> None: ...
    def list_lines(self, payroll_run_id: str) -> list[PayrollLine]: ...
    def save_concept(self, payroll_concept: PayrollConcept) -> None: ...
    def list_concepts(self, payroll_line_id: str) -> list[PayrollConcept]: ...


class PayrollPaymentRepositoryPort(Protocol):
    def save(self, payroll_payment: PayrollPayment) -> None: ...
    def get_by_operation_id(self, operation_id: str) -> PayrollPayment | None: ...
    def get_by_run_id(self, payroll_run_id: str) -> PayrollPayment | None: ...
