"""Repository ports for the Notifications bounded context — SET-20.
Protocols only — implementations land in
``backend/infrastructure/db/repositories/notifications/``. Every id is a
UUIDv7 string. Mirrors backend/domain/integrations/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.notifications.entities.notification_account import NotificationAccount
from backend.domain.notifications.entities.notification_route import NotificationRoute
from backend.domain.notifications.entities.notification_template import NotificationTemplate
from backend.domain.notifications.enums import NotificationChannel


class NotificationAccountRepositoryPort(Protocol):
    def save(self, account: NotificationAccount) -> None: ...
    def get(self, account_id: str) -> NotificationAccount | None: ...
    def list_by_channel(self, channel: NotificationChannel) -> list[NotificationAccount]: ...
    def list_active(self) -> list[NotificationAccount]: ...


class NotificationTemplateRepositoryPort(Protocol):
    def save(self, template: NotificationTemplate) -> None: ...
    def get(self, template_id: str) -> NotificationTemplate | None: ...
    def get_by_code(self, code: str) -> NotificationTemplate | None: ...
    def list_active(self) -> list[NotificationTemplate]: ...


class NotificationRouteRepositoryPort(Protocol):
    def save(self, route: NotificationRoute) -> None: ...
    def get(self, route_id: str) -> NotificationRoute | None: ...
    def list_by_event_code(self, event_code: str) -> list[NotificationRoute]: ...
    def list_active(self) -> list[NotificationRoute]: ...
