"""Repository ports for the Device Management bounded context — SET-7.

Protocols only — implementations land in
``backend/infrastructure/db/repositories/device_management/``. Every id
is a UUIDv7 string. Mirrors backend/domain/settings/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.device_management.entities.device import Device
from backend.domain.device_management.entities.device_profile import DeviceProfile
from backend.domain.device_management.entities.device_test_result import DeviceTestResult
from backend.domain.device_management.entities.print_route import PrintRoute
from backend.domain.device_management.entities.printer_test_result import PrinterTestResult
from backend.domain.device_management.entities.workstation_device_assignment import (
    WorkstationDeviceAssignment,
)
from backend.domain.device_management.enums import AssignmentRole


class DeviceProfileRepositoryPort(Protocol):
    def save(self, profile: DeviceProfile) -> None: ...
    def get(self, profile_id: str) -> DeviceProfile | None: ...
    def list_active(self) -> list[DeviceProfile]: ...


class DeviceRepositoryPort(Protocol):
    def save(self, device: Device) -> None: ...
    def get(self, device_id: str) -> Device | None: ...
    def get_by_code(self, code: str) -> Device | None: ...
    def list_by_branch(self, branch_id: str) -> list[Device]: ...
    def list_active(self) -> list[Device]: ...
    def list_all(self) -> list[Device]: ...


class WorkstationDeviceAssignmentRepositoryPort(Protocol):
    def save(self, assignment: WorkstationDeviceAssignment) -> None: ...
    def get(self, assignment_id: str) -> WorkstationDeviceAssignment | None: ...
    def get_active_for_role(
        self, workstation_id: str, role: AssignmentRole,
    ) -> WorkstationDeviceAssignment | None: ...
    def list_active_for_workstation(self, workstation_id: str) -> list[WorkstationDeviceAssignment]: ...
    def list_for_device(self, device_id: str) -> list[WorkstationDeviceAssignment]: ...


class PrintRouteRepositoryPort(Protocol):
    def save(self, route: PrintRoute) -> None: ...
    def get(self, route_id: str) -> PrintRoute | None: ...
    def list_candidates(self, document_type: str) -> list[PrintRoute]: ...
    def list_active(self) -> list[PrintRoute]: ...
    def list_all(self) -> list[PrintRoute]: ...


class PrinterTestResultRepositoryPort(Protocol):
    def save(self, result: PrinterTestResult) -> None: ...
    def list_for_device(self, device_id: str) -> list[PrinterTestResult]: ...


class DeviceTestResultRepositoryPort(Protocol):
    def save(self, result: DeviceTestResult) -> None: ...
    def list_for_device(self, device_id: str) -> list[DeviceTestResult]: ...
