"""Repository ports for the Customer Privacy bounded context (§10).
Protocols only — implementations live in
``backend/infrastructure/db/repositories/customer_privacy/``. Mirrors
backend/domain/customer_service/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.customer_privacy.entities.customer_communication_preference import (
    CustomerCommunicationPreference,
)
from backend.domain.customer_privacy.entities.customer_consent import CustomerConsent
from backend.domain.customer_privacy.entities.customer_data_retention_policy import (
    CustomerDataRetentionPolicy,
)
from backend.domain.customer_privacy.entities.customer_privacy_request import (
    CustomerPrivacyRequest,
)
from backend.domain.customer_privacy.value_objects.privacy_request_code import (
    PrivacyRequestCode,
)


class CustomerConsentRepositoryPort(Protocol):
    def save(self, consent: CustomerConsent, *, operation_id: str | None = None) -> None: ...
    def update(self, consent: CustomerConsent) -> None: ...
    def get(self, consent_id: str) -> CustomerConsent | None: ...
    def get_by_operation_id(self, operation_id: str) -> CustomerConsent | None: ...
    def get_latest(self, customer_id: str, consent_type: str) -> CustomerConsent | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerConsent]: ...


class CustomerCommunicationPreferenceRepositoryPort(Protocol):
    def save(self, preference: CustomerCommunicationPreference) -> None: ...
    def update(self, preference: CustomerCommunicationPreference) -> None: ...
    def get_by_customer_id(self, customer_id: str) -> CustomerCommunicationPreference | None: ...


class CustomerPrivacyRequestRepositoryPort(Protocol):
    def next_code(self) -> PrivacyRequestCode: ...
    def save(self, request: CustomerPrivacyRequest, *,
             operation_id: str | None = None) -> None: ...
    def update(self, request: CustomerPrivacyRequest) -> None: ...
    def get(self, request_id: str) -> CustomerPrivacyRequest | None: ...
    def get_by_operation_id(self, operation_id: str) -> CustomerPrivacyRequest | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerPrivacyRequest]: ...
    def list_by_status(self, status: str, *,
                        limit: int = 200, offset: int = 0) -> list[CustomerPrivacyRequest]: ...


class CustomerDataRetentionPolicyRepositoryPort(Protocol):
    def save(self, policy: CustomerDataRetentionPolicy) -> None: ...
    def get(self, policy_id: str) -> CustomerDataRetentionPolicy | None: ...
    def list_active(self) -> list[CustomerDataRetentionPolicy]: ...
