# domain/whatsapp/repository_ports.py — WA-2
"""
Puertos (interfaces) de persistencia para las entidades de WA-2. Solo
contratos — ninguna implementación concreta vive aquí (eso es
`infrastructure/persistence/` en WA-3/WA-4). Definidos con `typing.Protocol`
para que la capa de aplicación dependa de estos puertos, nunca de SQLite/
FastAPI directamente (regla 5-6 del skill de refactor).
"""
from __future__ import annotations

from typing import List, Optional, Protocol

from domain.whatsapp.entities.business_account import (
    WhatsAppBusinessAccount,
    WhatsAppProviderConfiguration,
)
from domain.whatsapp.entities.channel_number import WhatsAppChannelNumber
from domain.whatsapp.entities.conversation import ConversationSession, WhatsAppConversation
from domain.whatsapp.entities.identity import WhatsAppIdentity
from domain.whatsapp.entities.message import WhatsAppMessage, WhatsAppMessageDelivery


class WhatsAppAccountRepository(Protocol):
    def get_by_id(self, account_id: str) -> Optional[WhatsAppBusinessAccount]: ...
    def get_by_external_id(self, external_id: str) -> Optional[WhatsAppBusinessAccount]: ...
    def save(self, account: WhatsAppBusinessAccount) -> None: ...
    def list_active(self) -> List[WhatsAppBusinessAccount]: ...


class WhatsAppProviderConfigurationRepository(Protocol):
    def get_by_account_id(self, account_id: str) -> Optional[WhatsAppProviderConfiguration]: ...
    def save(self, configuration: WhatsAppProviderConfiguration) -> None: ...


class WhatsAppNumberRepository(Protocol):
    def get_by_id(self, number_id: str) -> Optional[WhatsAppChannelNumber]: ...
    def get_by_external_id(self, phone_number_external_id: str) -> Optional[WhatsAppChannelNumber]: ...
    def get_by_branch(self, branch_id: str) -> List[WhatsAppChannelNumber]: ...
    def get_global_numbers(self) -> List[WhatsAppChannelNumber]: ...
    def save(self, number: WhatsAppChannelNumber) -> None: ...


class WhatsAppIdentityRepository(Protocol):
    def get_by_id(self, identity_id: str) -> Optional[WhatsAppIdentity]: ...
    def get_by_wa_id(self, wa_id: str) -> Optional[WhatsAppIdentity]: ...
    def get_by_normalized_phone(self, e164_phone: str) -> Optional[WhatsAppIdentity]: ...
    def save(self, identity: WhatsAppIdentity) -> None: ...


class WhatsAppConversationRepository(Protocol):
    def get_by_id(self, conversation_id: str) -> Optional[WhatsAppConversation]: ...
    def get_open_for_identity(
        self, identity_id: str, channel_number_id: str
    ) -> Optional[WhatsAppConversation]: ...
    def save(self, conversation: WhatsAppConversation) -> None: ...
    def save_session(self, session: ConversationSession) -> None: ...


class WhatsAppMessageRepository(Protocol):
    def get_by_id(self, message_id: str) -> Optional[WhatsAppMessage]: ...
    def get_by_provider_message_id(self, provider_message_id: str) -> Optional[WhatsAppMessage]: ...
    def save(self, message: WhatsAppMessage) -> None: ...
    def get_delivery(self, delivery_id: str) -> Optional[WhatsAppMessageDelivery]: ...
    def get_delivery_for_message(self, message_id: str) -> Optional[WhatsAppMessageDelivery]: ...
    def save_delivery(self, delivery: WhatsAppMessageDelivery) -> None: ...
