# domain/whatsapp/repository_ports.py — WA-2
"""
Puertos (interfaces) de persistencia para las entidades de WA-2. Solo
contratos — ninguna implementación concreta vive aquí (eso es
`infrastructure/persistence/` en WA-3/WA-4). Definidos con `typing.Protocol`
para que la capa de aplicación dependa de estos puertos, nunca de SQLite/
FastAPI directamente (regla 5-6 del skill de refactor).
"""
from __future__ import annotations

from typing import List, Optional, Protocol

from domain.whatsapp.entities.business_account import (
    WhatsAppBusinessAccount,
    WhatsAppProviderConfiguration,
)
from domain.whatsapp.entities.channel_number import WhatsAppChannelNumber
from domain.whatsapp.entities.conversation import ConversationSession, WhatsAppConversation
from domain.whatsapp.entities.business_operation import BusinessOperationIdempotencyRecord
from domain.whatsapp.entities.delivery_request import DeliveryRequest
from domain.whatsapp.entities.handoff_request import HandoffRequest
from domain.whatsapp.entities.identity import WhatsAppIdentity
from domain.whatsapp.entities.inbox_job import InboundMessageJob
from domain.whatsapp.entities.message import WhatsAppMessage, WhatsAppMessageDelivery
from domain.whatsapp.entities.order_draft import OrderDraft
from domain.whatsapp.entities.outbox_message import OutboxMessage
from domain.whatsapp.entities.quote_draft import QuoteDraft


class WhatsAppAccountRepository(Protocol):
    def get_by_id(self, account_id: str) -> Optional[WhatsAppBusinessAccount]: ...
    def get_by_external_id(self, external_id: str) -> Optional[WhatsAppBusinessAccount]: ...
    def save(self, account: WhatsAppBusinessAccount) -> None: ...
    def list_active(self) -> List[WhatsAppBusinessAccount]: ...


class WhatsAppProviderConfigurationRepository(Protocol):
    def get_by_account_id(self, account_id: str) -> Optional[WhatsAppProviderConfiguration]: ...
    def save(self, configuration: WhatsAppProviderConfiguration) -> None: ...


class WhatsAppNumberRepository(Protocol):
    def get_by_id(self, number_id: str) -> Optional[WhatsAppChannelNumber]: ...
    def get_by_external_id(self, phone_number_external_id: str) -> Optional[WhatsAppChannelNumber]: ...
    def get_by_branch(self, branch_id: str) -> List[WhatsAppChannelNumber]: ...
    def get_global_numbers(self) -> List[WhatsAppChannelNumber]: ...
    def save(self, number: WhatsAppChannelNumber) -> None: ...


class WhatsAppIdentityRepository(Protocol):
    def get_by_id(self, identity_id: str) -> Optional[WhatsAppIdentity]: ...
    def get_by_wa_id(self, wa_id: str) -> Optional[WhatsAppIdentity]: ...
    def get_by_normalized_phone(self, e164_phone: str) -> Optional[WhatsAppIdentity]: ...
    def save(self, identity: WhatsAppIdentity) -> None: ...


class WhatsAppConversationRepository(Protocol):
    def get_by_id(self, conversation_id: str) -> Optional[WhatsAppConversation]: ...
    def get_open_for_identity(
        self, identity_id: str, channel_number_id: str
    ) -> Optional[WhatsAppConversation]: ...
    def save(self, conversation: WhatsAppConversation) -> None: ...
    def save_session(self, session: ConversationSession) -> None: ...


class WhatsAppMessageRepository(Protocol):
    def get_by_id(self, message_id: str) -> Optional[WhatsAppMessage]: ...
    def get_by_provider_message_id(self, provider_message_id: str) -> Optional[WhatsAppMessage]: ...
    def save(self, message: WhatsAppMessage) -> None: ...
    def get_delivery(self, delivery_id: str) -> Optional[WhatsAppMessageDelivery]: ...
    def get_delivery_for_message(self, message_id: str) -> Optional[WhatsAppMessageDelivery]: ...
    def save_delivery(self, delivery: WhatsAppMessageDelivery) -> None: ...


class WhatsAppInboxRepository(Protocol):
    """WA-6 (§20-21) — jobs de procesamiento asíncrono de mensajes entrantes."""

    def get_by_id(self, job_id: str) -> Optional[InboundMessageJob]: ...
    def get_by_message_id(self, message_id: str) -> Optional[InboundMessageJob]: ...
    def claim_pending(self, limit: int = 10) -> List[InboundMessageJob]: ...
    def save(self, job: InboundMessageJob) -> None: ...


class WhatsAppOrderDraftRepository(Protocol):
    """WA-10 — el carrito conversacional (§34), nunca el pedido canónico."""

    def get_by_id(self, draft_id: str) -> Optional[OrderDraft]: ...
    def get_active_for_conversation(self, conversation_id: str) -> Optional[OrderDraft]: ...
    def save(self, draft: OrderDraft) -> None: ...


class WhatsAppIdempotencyRepository(Protocol):
    """WA-10 — respalda `whatsapp_business_operation_idempotency` (§19)."""

    def get_by_fingerprint(self, fingerprint: str) -> Optional[BusinessOperationIdempotencyRecord]: ...
    def save(self, record: BusinessOperationIdempotencyRecord) -> None: ...


class WhatsAppQuoteDraftRepository(Protocol):
    """WA-11 — el equivalente de `WhatsAppOrderDraftRepository` para cotizaciones."""

    def get_by_id(self, draft_id: str) -> Optional[QuoteDraft]: ...
    def get_active_for_conversation(self, conversation_id: str) -> Optional[QuoteDraft]: ...
    def save(self, draft: QuoteDraft) -> None: ...


class WhatsAppDeliveryRequestRepository(Protocol):
    """WA-13 — el rastro conversacional de solicitudes de entrega."""

    def get_by_id(self, request_id: str) -> Optional[DeliveryRequest]: ...
    def get_by_order_external_id(self, order_external_id: str) -> Optional[DeliveryRequest]: ...
    def save(self, request: DeliveryRequest) -> None: ...


class WhatsAppHandoffRequestRepository(Protocol):
    """WA-16 — solicitudes de traspaso a un agente humano."""

    def get_by_id(self, request_id: str) -> Optional[HandoffRequest]: ...
    def get_open_for_conversation(self, conversation_id: str) -> Optional[HandoffRequest]: ...
    def save(self, request: HandoffRequest) -> None: ...


class WhatsAppOutboxRepository(Protocol):
    """WA-17 — cola de envío saliente (§21-22)."""

    def get_by_id(self, message_id: str) -> Optional[OutboxMessage]: ...
    def get_by_operation_id(self, operation_id: str) -> Optional[OutboxMessage]: ...
    def claim_due(self, limit: int = 10) -> List[OutboxMessage]: ...
    def save(self, message: OutboxMessage) -> None: ...
