"""Canonical context/navigation event names — SHELL-6 §73 "Contexto"."""
from __future__ import annotations

APPLICATION_CONTEXT_CHANGING = "APPLICATION_CONTEXT_CHANGING"
APPLICATION_CONTEXT_CHANGED = "APPLICATION_CONTEXT_CHANGED"
NAVIGATION_CONTEXT_REBUILT = "NAVIGATION_CONTEXT_REBUILT"
