"""Repository ports for the Customer Master bounded context (§10).

Protocols only — implementations live in
``backend/infrastructure/db/repositories/customers/``. Every id is a UUIDv7
string. Mirrors backend/domain/finance/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.customers.entities.customer import Customer
from backend.domain.customers.entities.customer_account import CustomerAccount
from backend.domain.customers.entities.customer_address import CustomerAddress
from backend.domain.customers.entities.customer_contact import CustomerContactPerson
from backend.domain.customers.entities.customer_data_quality_issue import (
    CustomerDataQualityIssue,
)
from backend.domain.customers.entities.customer_duplicate_candidate import (
    CustomerDuplicateCandidate,
)
from backend.domain.customers.entities.customer_import_batch import CustomerImportBatch
from backend.domain.customers.entities.customer_merge_record import CustomerMergeRecord
from backend.domain.customers.entities.customer_tax_profile import CustomerTaxProfile
from backend.domain.customers.value_objects.customer_code import CustomerCode


class CustomerRepositoryPort(Protocol):
    def next_code(self) -> CustomerCode: ...
    def save(self, customer: Customer, *, operation_id: str | None = None) -> None: ...
    def update(self, customer: Customer) -> None: ...
    def get(self, customer_id: str) -> Customer | None: ...
    def get_by_code(self, code: str) -> Customer | None: ...
    def get_by_operation_id(self, operation_id: str) -> Customer | None: ...
    def find_duplicate_rows(self) -> list[dict]: ...
    def list_active(self, *, limit: int = 200, offset: int = 0) -> list[Customer]: ...
    def search_lookup(self, query: str, *, limit: int = 20) -> list[dict]: ...


class CustomerAccountRepositoryPort(Protocol):
    def save(self, account: CustomerAccount) -> None: ...
    def get(self, account_id: str) -> CustomerAccount | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerAccount]: ...
    def reassign_customer_id(self, old_customer_id: str, new_customer_id: str) -> None: ...


class CustomerContactRepositoryPort(Protocol):
    def save(self, contact: CustomerContactPerson) -> None: ...
    def update(self, contact: CustomerContactPerson) -> None: ...
    def remove(self, contact_id: str) -> None: ...
    def get(self, contact_id: str) -> CustomerContactPerson | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerContactPerson]: ...
    def clear_primary(self, customer_id: str) -> None: ...
    def reassign_customer_id(self, old_customer_id: str, new_customer_id: str) -> None: ...


class CustomerAddressRepositoryPort(Protocol):
    def save(self, address: CustomerAddress) -> None: ...
    def update(self, address: CustomerAddress) -> None: ...
    def remove(self, address_id: str) -> None: ...
    def get(self, address_id: str) -> CustomerAddress | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerAddress]: ...
    def clear_default(self, customer_id: str, address_type: str) -> None: ...
    def reassign_customer_id(self, old_customer_id: str, new_customer_id: str) -> None: ...


class CustomerTaxProfileRepositoryPort(Protocol):
    def save(self, profile: CustomerTaxProfile) -> None: ...
    def update(self, profile: CustomerTaxProfile) -> None: ...
    def get_for_customer(self, customer_id: str) -> CustomerTaxProfile | None: ...
    def reassign_customer_id(self, old_customer_id: str, new_customer_id: str) -> None: ...
    def delete_for_customer(self, customer_id: str) -> None: ...


class CustomerDuplicateCandidateRepositoryPort(Protocol):
    def save(self, candidate: CustomerDuplicateCandidate, *,
             operation_id: str | None = None) -> None: ...
    def update(self, candidate: CustomerDuplicateCandidate) -> None: ...
    def get(self, candidate_id: str) -> CustomerDuplicateCandidate | None: ...
    def get_active_pair(self, customer_id_a: str,
                        customer_id_b: str) -> CustomerDuplicateCandidate | None: ...
    def list_by_status(self, status: str) -> list[CustomerDuplicateCandidate]: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerDuplicateCandidate]: ...


class CustomerMergeRecordRepositoryPort(Protocol):
    def save(self, record: CustomerMergeRecord, *, operation_id: str | None = None) -> None: ...
    def update(self, record: CustomerMergeRecord) -> None: ...
    def get(self, record_id: str) -> CustomerMergeRecord | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerMergeRecord]: ...


class CustomerDataQualityIssueRepositoryPort(Protocol):
    def save(self, issue: CustomerDataQualityIssue, *,
             operation_id: str | None = None) -> None: ...
    def update(self, issue: CustomerDataQualityIssue) -> None: ...
    def get(self, issue_id: str) -> CustomerDataQualityIssue | None: ...
    def get_open(self, customer_id: str, rule_code: str) -> CustomerDataQualityIssue | None: ...
    def list_open_for_customer(self, customer_id: str) -> list[CustomerDataQualityIssue]: ...
    def list_by_status(self, status: str) -> list[CustomerDataQualityIssue]: ...


class CustomerImportBatchRepositoryPort(Protocol):
    def save(self, batch: CustomerImportBatch, *, operation_id: str | None = None) -> None: ...
    def update(self, batch: CustomerImportBatch) -> None: ...
    def get(self, batch_id: str) -> CustomerImportBatch | None: ...
    def list_pending_approval(self) -> list[CustomerImportBatch]: ...
    def save_pending_rows(self, batch_id: str, rows_json: str) -> None: ...
    def get_pending_rows(self, batch_id: str) -> str | None: ...
    def clear_pending_rows(self, batch_id: str) -> None: ...
