"""Repository ports for the Customer Master bounded context (§10).

Protocols only — implementations live in
``backend/infrastructure/db/repositories/customers/``. Every id is a UUIDv7
string. Mirrors backend/domain/finance/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.customers.entities.customer import Customer
from backend.domain.customers.entities.customer_account import CustomerAccount
from backend.domain.customers.entities.customer_address import CustomerAddress
from backend.domain.customers.entities.customer_contact import CustomerContactPerson
from backend.domain.customers.entities.customer_tax_profile import CustomerTaxProfile
from backend.domain.customers.value_objects.customer_code import CustomerCode


class CustomerRepositoryPort(Protocol):
    def next_code(self) -> CustomerCode: ...
    def save(self, customer: Customer, *, operation_id: str | None = None) -> None: ...
    def update(self, customer: Customer) -> None: ...
    def get(self, customer_id: str) -> Customer | None: ...
    def get_by_code(self, code: str) -> Customer | None: ...
    def get_by_operation_id(self, operation_id: str) -> Customer | None: ...
    def find_duplicate_rows(self) -> list[dict]: ...
    def list_active(self, *, limit: int = 200, offset: int = 0) -> list[Customer]: ...


class CustomerAccountRepositoryPort(Protocol):
    def save(self, account: CustomerAccount) -> None: ...
    def get(self, account_id: str) -> CustomerAccount | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerAccount]: ...


class CustomerContactRepositoryPort(Protocol):
    def save(self, contact: CustomerContactPerson) -> None: ...
    def update(self, contact: CustomerContactPerson) -> None: ...
    def remove(self, contact_id: str) -> None: ...
    def get(self, contact_id: str) -> CustomerContactPerson | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerContactPerson]: ...
    def clear_primary(self, customer_id: str) -> None: ...


class CustomerAddressRepositoryPort(Protocol):
    def save(self, address: CustomerAddress) -> None: ...
    def update(self, address: CustomerAddress) -> None: ...
    def remove(self, address_id: str) -> None: ...
    def get(self, address_id: str) -> CustomerAddress | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerAddress]: ...
    def clear_default(self, customer_id: str, address_type: str) -> None: ...


class CustomerTaxProfileRepositoryPort(Protocol):
    def save(self, profile: CustomerTaxProfile) -> None: ...
    def update(self, profile: CustomerTaxProfile) -> None: ...
    def get_for_customer(self, customer_id: str) -> CustomerTaxProfile | None: ...
