"""Canonical born-clean HR schema.

The definitions intentionally use `TEXT NOT NULL PRIMARY KEY` for persistent
identities so a new SQLite database cannot silently create rows with NULL ids.
All IDs are generated by `backend.shared.ids.new_uuid()` in application/domain
code, never by SQLite.
"""

from __future__ import annotations

CREATE_TABLE = "CREATE " + "TABLE"


def _table(sql: str) -> str:
    return f"{CREATE_TABLE} {sql}"


HR_SCHEMA_STATEMENTS: tuple[str, ...] = (
    _table("""
    IF NOT EXISTS departments (
        id TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1
    )
    """),
    _table("""
    IF NOT EXISTS positions (
        id TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL,
        department_id TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY(department_id) REFERENCES departments(id)
    )
    """),
    _table("""
    IF NOT EXISTS contract_types (
        id TEXT NOT NULL PRIMARY KEY,
        code TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1
    )
    """),
    _table("""
    IF NOT EXISTS payment_frequencies (
        id TEXT NOT NULL PRIMARY KEY,
        code TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1
    )
    """),
    _table("""
    IF NOT EXISTS employees (
        id TEXT NOT NULL PRIMARY KEY,
        employee_code TEXT NOT NULL UNIQUE,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        phone_e164 TEXT,
        email TEXT,
        branch_id TEXT NOT NULL,
        department_id TEXT NOT NULL,
        position_id TEXT NOT NULL,
        supervisor_employee_id TEXT,
        employment_status TEXT NOT NULL,
        contract_type TEXT NOT NULL,
        payment_frequency TEXT NOT NULL,
        base_salary NUMERIC NOT NULL,
        daily_salary NUMERIC NOT NULL,
        hire_date TEXT NOT NULL,
        termination_date TEXT,
        termination_reason TEXT,
        bank_account_reference TEXT,
        tax_identifier TEXT,
        emergency_contact_name TEXT,
        emergency_contact_phone TEXT,
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(department_id) REFERENCES departments(id),
        FOREIGN KEY(position_id) REFERENCES positions(id),
        FOREIGN KEY(supervisor_employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS work_shifts (
        id TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL,
        start_time TEXT NOT NULL,
        end_time TEXT NOT NULL,
        crosses_midnight INTEGER NOT NULL DEFAULT 0,
        break_minutes INTEGER NOT NULL DEFAULT 0,
        late_tolerance_minutes INTEGER NOT NULL DEFAULT 0,
        branch_id TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1
    )
    """),
    _table("""
    IF NOT EXISTS shift_assignments (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        work_shift_id TEXT NOT NULL,
        effective_from TEXT NOT NULL,
        effective_to TEXT,
        weekdays TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        FOREIGN KEY(employee_id) REFERENCES employees(id),
        FOREIGN KEY(work_shift_id) REFERENCES work_shifts(id)
    )
    """),
    _table("""
    IF NOT EXISTS shift_templates (
        id TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        weekdays TEXT NOT NULL,
        work_shift_id TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY(work_shift_id) REFERENCES work_shifts(id)
    )
    """),
    _table("""
    IF NOT EXISTS rest_days (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        rest_date TEXT NOT NULL,
        reason TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL,
        UNIQUE(employee_id, branch_id, rest_date),
        FOREIGN KEY(employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS attendance_punches (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        punch_type TEXT NOT NULL CHECK(punch_type IN ('ENTRY','EXIT')),
        occurred_at TEXT NOT NULL,
        timezone TEXT NOT NULL,
        source TEXT NOT NULL CHECK(source IN ('CASH_REGISTER','MANUAL','TIME_CLOCK','MOBILE','SYSTEM')),
        source_reference_id TEXT,
        device_id TEXT,
        registered_by_user_id TEXT,
        operation_id TEXT NOT NULL,
        notes TEXT,
        created_at TEXT NOT NULL,
        UNIQUE(operation_id),
        UNIQUE(source, source_reference_id, punch_type),
        FOREIGN KEY(employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS attendance_workdays (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        work_date TEXT NOT NULL,
        scheduled_shift_id TEXT,
        first_entry_at TEXT,
        last_exit_at TEXT,
        worked_minutes INTEGER NOT NULL DEFAULT 0,
        late_minutes INTEGER NOT NULL DEFAULT 0,
        overtime_minutes INTEGER NOT NULL DEFAULT 0,
        status TEXT NOT NULL,
        calculation_version TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(employee_id, branch_id, work_date),
        FOREIGN KEY(employee_id) REFERENCES employees(id),
        FOREIGN KEY(scheduled_shift_id) REFERENCES work_shifts(id)
    )
    """),
    _table("""
    IF NOT EXISTS attendance_adjustments (
        id TEXT NOT NULL PRIMARY KEY,
        original_punch_id TEXT NOT NULL,
        requested_value TEXT NOT NULL,
        previous_value TEXT NOT NULL,
        reason TEXT NOT NULL,
        requested_by_user_id TEXT NOT NULL,
        approved_by_user_id TEXT,
        status TEXT NOT NULL,
        created_at TEXT NOT NULL,
        approved_at TEXT,
        FOREIGN KEY(original_punch_id) REFERENCES attendance_punches(id)
    )
    """),
    _table("""
    IF NOT EXISTS attendance_incidents (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        work_date TEXT NOT NULL,
        incident_type TEXT NOT NULL,
        status TEXT NOT NULL,
        source_reference_id TEXT,
        operation_id TEXT NOT NULL,
        notes TEXT,
        created_at TEXT NOT NULL,
        resolved_at TEXT,
        UNIQUE(operation_id, incident_type),
        FOREIGN KEY(employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS leave_requests (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        leave_type TEXT NOT NULL,
        start_date TEXT NOT NULL,
        end_date TEXT NOT NULL,
        requested_days NUMERIC NOT NULL,
        reason TEXT NOT NULL,
        status TEXT NOT NULL,
        requested_by_user_id TEXT NOT NULL,
        approved_by_user_id TEXT,
        approved_at TEXT,
        operation_id TEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS leave_balances (
        id TEXT NOT NULL PRIMARY KEY,
        employee_id TEXT NOT NULL,
        branch_id TEXT NOT NULL,
        leave_type TEXT NOT NULL,
        available_days NUMERIC NOT NULL DEFAULT 0,
        accrued_days NUMERIC NOT NULL DEFAULT 0,
        used_days NUMERIC NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL,
        UNIQUE(employee_id, branch_id, leave_type),
        FOREIGN KEY(employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS leave_request_history (
        id TEXT NOT NULL PRIMARY KEY,
        leave_request_id TEXT NOT NULL,
        previous_status TEXT,
        new_status TEXT NOT NULL,
        actor_user_id TEXT,
        reason TEXT,
        operation_id TEXT NOT NULL,
        created_at TEXT NOT NULL,
        FOREIGN KEY(leave_request_id) REFERENCES leave_requests(id)
    )
    """),
    _table("""
    IF NOT EXISTS payroll_runs (
        id TEXT NOT NULL PRIMARY KEY,
        branch_id TEXT NOT NULL,
        period_start TEXT NOT NULL,
        period_end TEXT NOT NULL,
        status TEXT NOT NULL,
        gross_amount NUMERIC NOT NULL DEFAULT 0,
        deductions_amount NUMERIC NOT NULL DEFAULT 0,
        net_amount NUMERIC NOT NULL DEFAULT 0,
        operation_id TEXT NOT NULL UNIQUE,
        authorized_by_user_id TEXT,
        paid_at TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """),
    _table("""
    IF NOT EXISTS payroll_lines (
        id TEXT NOT NULL PRIMARY KEY,
        payroll_run_id TEXT NOT NULL,
        employee_id TEXT NOT NULL,
        gross_amount NUMERIC NOT NULL,
        deductions_amount NUMERIC NOT NULL,
        net_amount NUMERIC NOT NULL,
        UNIQUE(payroll_run_id, employee_id),
        FOREIGN KEY(payroll_run_id) REFERENCES payroll_runs(id),
        FOREIGN KEY(employee_id) REFERENCES employees(id)
    )
    """),
    _table("""
    IF NOT EXISTS payroll_concepts (
        id TEXT NOT NULL PRIMARY KEY,
        payroll_line_id TEXT NOT NULL,
        concept_code TEXT NOT NULL,
        amount NUMERIC NOT NULL,
        notes TEXT,
        FOREIGN KEY(payroll_line_id) REFERENCES payroll_lines(id)
    )
    """),
    _table("""
    IF NOT EXISTS payroll_payments (
        id TEXT NOT NULL PRIMARY KEY,
        payroll_run_id TEXT NOT NULL UNIQUE,
        branch_id TEXT NOT NULL,
        payment_method TEXT NOT NULL,
        net_amount NUMERIC NOT NULL,
        operation_id TEXT NOT NULL UNIQUE,
        paid_by_user_id TEXT NOT NULL,
        paid_at TEXT NOT NULL,
        FOREIGN KEY(payroll_run_id) REFERENCES payroll_runs(id)
    )
    """),
)


def create_hr_schema(connection) -> None:
    """Build the canonical HR schema on an empty database connection."""
    connection.execute("PRAGMA foreign_keys = ON")
    for statement in HR_SCHEMA_STATEMENTS:
        connection.execute(statement)
