"""Repository ports for the Feature Flags bounded context — SET-21.
Protocols only — implementations land in
``backend/infrastructure/db/repositories/feature_flags/``. Every id is a
UUIDv7 string. Mirrors backend/domain/notifications/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.feature_flags.entities.feature_flag import FeatureFlag
from backend.domain.feature_flags.entities.feature_flag_change_request import FeatureFlagChangeRequest
from backend.domain.feature_flags.entities.feature_flag_rule import FeatureFlagRule


class FeatureFlagRepositoryPort(Protocol):
    def save(self, flag: FeatureFlag) -> None: ...
    def get(self, flag_id: str) -> FeatureFlag | None: ...
    def get_by_code(self, code: str) -> FeatureFlag | None: ...
    def list_active(self) -> list[FeatureFlag]: ...


class FeatureFlagRuleRepositoryPort(Protocol):
    def save(self, rule: FeatureFlagRule) -> None: ...
    def get(self, rule_id: str) -> FeatureFlagRule | None: ...
    def list_for_flag(self, flag_id: str) -> list[FeatureFlagRule]: ...


class FeatureFlagChangeRequestRepositoryPort(Protocol):
    def save(self, request: FeatureFlagChangeRequest) -> None: ...
    def get(self, request_id: str) -> FeatureFlagChangeRequest | None: ...
    def list_pending(self) -> list[FeatureFlagChangeRequest]: ...
