"""Granular procurement permission codes (§55-62).

Never gate purchasing with a single general permission. Each sensitive action —
direct purchase, financial treatment, requisitions, quotes, orders, receiving,
invoicing — has its own code. The backend re-validates every one (hiding a
button is not security).
"""

from __future__ import annotations


class PurchasePermissions:
    # ── consulta (§55) ────────────────────────────────────────────────────
    VIEW = "PURCHASES_VIEW"
    VIEW_OWN_BRANCH = "PURCHASES_VIEW_OWN_BRANCH"
    VIEW_ASSIGNED_BRANCHES = "PURCHASES_VIEW_ASSIGNED_BRANCHES"
    VIEW_ALL_BRANCHES = "PURCHASES_VIEW_ALL_BRANCHES"
    VIEW_COSTS = "PURCHASES_VIEW_COSTS"
    VIEW_MARGINS = "PURCHASES_VIEW_MARGINS"
    VIEW_PAYMENTS = "PURCHASES_VIEW_PAYMENTS"
    VIEW_SUPPLIER_CREDIT = "PURCHASES_VIEW_SUPPLIER_CREDIT"
    VIEW_AUDIT = "PURCHASES_VIEW_AUDIT"
    VIEW_ANALYTICS = "PURCHASES_VIEW_ANALYTICS"
    EXPORT = "PURCHASES_EXPORT"

    # ── compra directa (§56) ──────────────────────────────────────────────
    DIRECT_VIEW = "PURCHASES_DIRECT_VIEW"
    DIRECT_CREATE = "PURCHASES_DIRECT_CREATE"
    DIRECT_EDIT = "PURCHASES_DIRECT_EDIT"
    DIRECT_CONFIRM = "PURCHASES_DIRECT_CONFIRM"
    DIRECT_SAVE_DRAFT = "PURCHASES_DIRECT_SAVE_DRAFT"
    DIRECT_USE_OCCASIONAL_SUPPLIER = "PURCHASES_DIRECT_USE_OCCASIONAL_SUPPLIER"
    DIRECT_CREATE_PRODUCT = "PURCHASES_DIRECT_CREATE_PRODUCT"
    DIRECT_OVERRIDE_PRICE = "PURCHASES_DIRECT_OVERRIDE_PRICE"
    DIRECT_OVERRIDE_COST = "PURCHASES_DIRECT_OVERRIDE_COST"
    DIRECT_OVER_RECEIVE = "PURCHASES_DIRECT_OVER_RECEIVE"
    DIRECT_CANCEL = "PURCHASES_DIRECT_CANCEL"
    DIRECT_REVERSE = "PURCHASES_DIRECT_REVERSE"
    DIRECT_PRINT = "PURCHASES_DIRECT_PRINT"

    # ── financieros (§57) ─────────────────────────────────────────────────
    REQUEST_IMMEDIATE_PAYMENT = "PURCHASES_REQUEST_IMMEDIATE_PAYMENT"
    REQUEST_PETTY_CASH_PAYMENT = "PURCHASES_REQUEST_PETTY_CASH_PAYMENT"
    REQUEST_TREASURY_PAYMENT = "PURCHASES_REQUEST_TREASURY_PAYMENT"
    REQUEST_BANK_TRANSFER = "PURCHASES_REQUEST_BANK_TRANSFER"
    USE_SUPPLIER_CREDIT = "PURCHASES_USE_SUPPLIER_CREDIT"
    USE_ADVANCE = "PURCHASES_USE_ADVANCE"
    USE_MIXED_TERMS = "PURCHASES_USE_MIXED_TERMS"
    OVERRIDE_FINANCIAL_LIMIT = "PURCHASES_OVERRIDE_FINANCIAL_LIMIT"
    VIEW_PAYMENT_REFERENCE = "PURCHASES_VIEW_PAYMENT_REFERENCE"

    # ── solicitudes (§58) ─────────────────────────────────────────────────
    REQUISITION_VIEW = "PURCHASES_REQUISITION_VIEW"
    REQUISITION_CREATE = "PURCHASES_REQUISITION_CREATE"
    REQUISITION_EDIT = "PURCHASES_REQUISITION_EDIT"
    REQUISITION_SUBMIT = "PURCHASES_REQUISITION_SUBMIT"
    REQUISITION_APPROVE = "PURCHASES_REQUISITION_APPROVE"
    REQUISITION_REJECT = "PURCHASES_REQUISITION_REJECT"
    REQUISITION_CANCEL = "PURCHASES_REQUISITION_CANCEL"

    # ── cotizaciones (§59) ────────────────────────────────────────────────
    RFQ_CREATE = "PURCHASES_RFQ_CREATE"
    RFQ_SEND = "PURCHASES_RFQ_SEND"
    QUOTE_CAPTURE = "PURCHASES_QUOTE_CAPTURE"
    QUOTE_EDIT = "PURCHASES_QUOTE_EDIT"
    QUOTE_COMPARE = "PURCHASES_QUOTE_COMPARE"
    QUOTE_AWARD = "PURCHASES_QUOTE_AWARD"
    QUOTE_OVERRIDE_SELECTION = "PURCHASES_QUOTE_OVERRIDE_SELECTION"

    # ── órdenes (§60) ─────────────────────────────────────────────────────
    ORDER_VIEW = "PURCHASES_ORDER_VIEW"
    ORDER_CREATE = "PURCHASES_ORDER_CREATE"
    ORDER_EDIT = "PURCHASES_ORDER_EDIT"
    ORDER_SUBMIT = "PURCHASES_ORDER_SUBMIT"
    ORDER_APPROVE = "PURCHASES_ORDER_APPROVE"
    ORDER_SEND = "PURCHASES_ORDER_SEND"
    ORDER_ACKNOWLEDGE = "PURCHASES_ORDER_ACKNOWLEDGE"
    ORDER_CHANGE_APPROVED = "PURCHASES_ORDER_CHANGE_APPROVED"
    ORDER_CANCEL = "PURCHASES_ORDER_CANCEL"
    ORDER_CLOSE = "PURCHASES_ORDER_CLOSE"

    # ── recepción (§61) ───────────────────────────────────────────────────
    RECEIPT_VIEW = "PURCHASES_RECEIPT_VIEW"
    RECEIPT_CREATE = "PURCHASES_RECEIPT_CREATE"
    RECEIPT_DIRECT = "PURCHASES_RECEIPT_DIRECT"
    RECEIPT_COMPLETE = "PURCHASES_RECEIPT_COMPLETE"
    RECEIPT_PARTIAL = "PURCHASES_RECEIPT_PARTIAL"
    RECEIPT_OVER_TOLERANCE = "PURCHASES_RECEIPT_OVER_TOLERANCE"
    RECEIPT_MANUAL_WEIGHT = "PURCHASES_RECEIPT_MANUAL_WEIGHT"
    RECEIPT_REJECT = "PURCHASES_RECEIPT_REJECT"
    RECEIPT_REVERSE = "PURCHASES_RECEIPT_REVERSE"
    QUALITY_INSPECT = "PURCHASES_QUALITY_INSPECT"
    QUALITY_RELEASE = "PURCHASES_QUALITY_RELEASE"
    QUARANTINE = "PURCHASES_QUARANTINE"
    RETURN = "PURCHASES_RETURN"

    # ── facturas y conciliación (§62) ─────────────────────────────────────
    INVOICE_VIEW = "PURCHASES_INVOICE_VIEW"
    INVOICE_CAPTURE = "PURCHASES_INVOICE_CAPTURE"
    INVOICE_EDIT = "PURCHASES_INVOICE_EDIT"
    INVOICE_MATCH = "PURCHASES_INVOICE_MATCH"
    INVOICE_RELEASE_VARIANCE = "PURCHASES_INVOICE_RELEASE_VARIANCE"
    INVOICE_BLOCK = "PURCHASES_INVOICE_BLOCK"
    INVOICE_CANCEL = "PURCHASES_INVOICE_CANCEL"


ALL_PURCHASE_PERMISSIONS = frozenset(
    v for k, v in vars(PurchasePermissions).items()
    if not k.startswith("_") and isinstance(v, str)
)
