"""Auto-generado por tools/refactor_control/build_cutover_spec.py (auditoría de esquema).

Mapa de relaciones legacy resuelto al 100% (turno_id->turnos_caja, tarjeta_id->
tarjetas_fidelidad, order_id->delivery_orders, cut_id->delivery_driver_cuts,
ticket_id->ventas, batch_id->card_batches, rol_id->roles, permiso_id->permisos).
NO EDITAR A MANO: regenerar con el tool.
"""
from backend.infrastructure.db.uuid_cutover import TableSpec

# 256 tablas | 15 junction/config (pk=None) | 0 con FK no resueltas

CUTOVER_SPECS = [
    TableSpec("accounts_payable", pk="id", fks={"supplier_id": "proveedores", "sucursal_id": "sucursales"}),
    TableSpec("accounts_receivable", pk="id", fks={"cliente_id": "clientes", "venta_id": "ventas", "sucursal_id": "sucursales"}),
    TableSpec("activos", pk="id", fks={"responsable_id": "usuarios"}),
    TableSpec("ajustes_inventario", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("alertas_config", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("alertas_log", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("anticipo_config", pk=None),
    TableSpec("anticipo_reglas", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("ap_payments", pk="id", fks={"ap_id": "accounts_payable"}),
    TableSpec("ar_payments", pk="id", fks={"ar_id": "accounts_receivable"}),
    TableSpec("asistencias", pk="id", fks={"personal_id": "personal"}),
    TableSpec("asset_depreciation_entries", pk="id", fks={"asset_id": "assets", "journal_entry_id": "journal_entries"}),
    TableSpec("asset_maintenance", pk="id", fks={"asset_id": "assets"}),
    TableSpec("assets", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("audit_log", pk="id", fks={"user_id": "usuarios", "sucursal_id": "sucursales"}),
    TableSpec("audit_logs", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("batch_movements", pk="id", fks={"batch_id": "batches", "bib_id": "branch_inventory_batches", "branch_id": "sucursales", "producto_id": "productos"}),
    TableSpec("batch_tree_audits", pk="id", fks={"root_batch_id": "batches"}),
    TableSpec("batches", pk="id", fks={"producto_id": "productos", "parent_batch_id": "batches", "root_batch_id": "batches"}),
    TableSpec("bi_branch_ranking", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("bi_product_profit", pk="id", fks={"producto_id": "productos"}),
    TableSpec("bi_sales_daily", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("bi_transformations", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("bot_sessions", pk=None, fks={"sucursal_id": "sucursales"}),
    TableSpec("branch_inventory", pk="id", fks={"branch_id": "sucursales", "product_id": "productos", "batch_id": "batches"}),
    TableSpec("branch_inventory_batches", pk="id", fks={"batch_id": "batches", "branch_id": "sucursales", "producto_id": "productos", "batch_padre_id": "batches"}),
    TableSpec("branch_products", pk=None, fks={"branch_id": "sucursales", "product_id": "productos"}),
    TableSpec("caja_operations", pk="id", fks={"branch_id": "sucursales", "venta_id": "ventas", "sucursal_id": "sucursales"}),
    TableSpec("cajas", pk="id"),
    TableSpec("capital_movements", pk="id", fks={"branch_id": "sucursales", "journal_entry_id": "journal_entries", "treasury_movement_id": "treasury_movements"}),
    TableSpec("card_assignment_history", pk="id", fks={"tarjeta_id": "tarjetas_fidelidad"}),
    TableSpec("card_batches", pk="id"),
    TableSpec("categorias", pk="id"),
    TableSpec("chicken_batches", pk="id", fks={"branch_id": "sucursales", "producto_id": "productos", "compra_global_id": "compras", "parent_batch_id": "batches"}),
    TableSpec("cierre_mensual", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("cierres_caja", pk="id", fks={"sucursal_id": "sucursales", "turno_id": "turnos_caja"}),
    TableSpec("clientes", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("clientes_diarios", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("clientes_lista_precio", pk=None, fks={"cliente_id": "clientes", "lista_id": "listas_precio"}),
    TableSpec("comisiones_acumuladas", pk="id", fks={"venta_id": "ventas", "sucursal_id": "sucursales"}),
    TableSpec("comisiones_config", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("componentes_producto", pk="id", fks={"producto_compuesto_id": "productos", "producto_componente_id": "productos"}),
    TableSpec("compras", pk="id", fks={"proveedor_id": "proveedores", "sucursal_id": "sucursales", "purchase_order_id": "ordenes_compra"}),
    TableSpec("compras_inventariables", pk="id", fks={"gasto_id": "gastos", "producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("compras_pollo", pk="id"),
    TableSpec("conciliation_runs", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("concurrency_events", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("config_diseno_tarjetas", pk="id"),
    TableSpec("config_programa_fidelidad", pk="id"),
    TableSpec("configuraciones", pk=None),
    TableSpec("configuracioneses", pk="id"),
    TableSpec("contenedor_productos", pk="id", fks={"contenedor_id": "contenedores", "producto_id": "productos"}),
    TableSpec("contenedores", pk="id", fks={"proveedor_id": "proveedores", "compra_id": "compras", "parent_id": "contenedores"}),
    TableSpec("contenedores_qr", pk="id"),
    TableSpec("cotizaciones", pk="id", fks={"cliente_id": "clientes", "venta_id": "ventas", "sucursal_id": "sucursales", "venta_ref_id": "ventas"}),
    TableSpec("cotizaciones_detalle", pk="id", fks={"cotizacion_id": "cotizaciones", "producto_id": "productos"}),
    TableSpec("credit_notes", pk="id", fks={"sale_id": "ventas"}),
    TableSpec("decision_log", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("delivery_cut_items", pk="id", fks={"cut_id": "delivery_driver_cuts", "order_id": "delivery_orders"}),
    TableSpec("delivery_driver_cuts", pk="id", fks={"driver_id": "drivers", "sucursal_id": "sucursales"}),
    TableSpec("delivery_orders", pk="id", fks={"venta_id": "ventas", "driver_id": "drivers", "cliente_id": "clientes", "sucursal_id": "sucursales", "corte_id": "cierres_caja"}),
    TableSpec("demand_forecast", pk="id", fks={"product_id": "productos", "branch_id": "sucursales"}),
    TableSpec("depreciacion_acumulada", pk="id", fks={"activo_id": "activos", "cuenta_id": "plan_cuentas"}),
    TableSpec("detalles_compra", pk="id", fks={"compra_id": "compras", "producto_id": "productos"}),
    TableSpec("detalles_venta", pk="id", fks={"venta_id": "ventas", "producto_id": "productos", "batch_id": "batches"}),
    TableSpec("devoluciones", pk="id", fks={"venta_id": "ventas", "sucursal_id": "sucursales"}),
    TableSpec("devoluciones_detalle", pk="id", fks={"devolucion_id": "devoluciones", "producto_id": "productos"}),
    TableSpec("driver_locations", pk=None, fks={"chofer_id": "drivers"}),
    TableSpec("drivers", pk="id", fks={"sucursal_id": "sucursales", "usuario_id": "usuarios", "personal_id": "personal"}),
    TableSpec("email_config", pk="id"),
    TableSpec("email_schedule", pk="id"),
    TableSpec("evaluaciones_personal", pk="id", fks={"personal_id": "personal"}),
    TableSpec("event_log", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("facturas_cfdi", pk="id", fks={"venta_id": "ventas"}),
    TableSpec("feature_flags", pk=None),
    TableSpec("financial_documents", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("financial_event_log", pk="id", fks={"usuario_id": "usuarios", "sucursal_id": "sucursales"}),
    TableSpec("financial_trace_log", pk="id"),
    TableSpec("fixed_assets", pk="id", fks={"supplier_id": "proveedores", "branch_id": "sucursales", "financial_document_id": "financial_documents", "treasury_movement_id": "treasury_movements", "journal_entry_id": "journal_entries"}),
    TableSpec("forecast_cache", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("forecast_metrics", pk="id", fks={"product_id": "productos", "branch_id": "sucursales"}),
    TableSpec("forecast_run_log", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("gastos", pk="id"),
    TableSpec("gastos_fijos", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("gastos_futuros", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("growth_ledger", pk="id", fks={"cliente_id": "clientes", "sucursal_id": "sucursales", "ticket_id": "ventas", "cajero_id": "usuarios"}),
    TableSpec("growth_metas", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("growth_misiones", pk="id"),
    TableSpec("growth_misiones_progreso", pk="id", fks={"cliente_id": "clientes", "mision_id": "growth_misiones"}),
    TableSpec("growth_otp", pk="id", fks={"cliente_id": "clientes"}),
    TableSpec("happy_hour_rules", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("hardware_config", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("historial", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("historial_precios", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("historico_puntos", pk="id", fks={"cliente_id": "clientes", "venta_id": "ventas"}),
    TableSpec("historico_tarjetas", pk="id"),
    TableSpec("hr_auditoria_log", pk="id", fks={"empleado_id": "personal", "sucursal_id": "sucursales"}),
    TableSpec("hr_pago_log", pk="id", fks={"empleado_id": "personal", "sucursal_id": "sucursales"}),
    TableSpec("inventario_actual", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("inventario_diario", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("inventario_global", pk="id", fks={"producto_id": "productos", "compra_ref_id": "compras"}),
    TableSpec("inventario_subproductos", pk="id", fks={"compra_pollo_id": "compras", "producto_id": "productos"}),
    TableSpec("inventario_sucursal", pk="id", fks={"sucursal_id": "sucursales", "producto_id": "productos"}),
    TableSpec("inventory_movements", pk="id", fks={"product_id": "productos", "branch_id": "sucursales", "batch_id": "batches"}),
    TableSpec("inventory_reservations", pk="id", fks={"branch_id": "sucursales", "product_id": "productos"}),
    TableSpec("inventory_stock", pk="id", fks={"product_id": "productos", "branch_id": "sucursales"}),
    TableSpec("journal_entries", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("json_audit_log", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("json_log_events", pk="id", fks={"sucursal_id": "sucursales", "branch_id": "sucursales"}),
    TableSpec("kpi_snapshots", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("legacy_branch_inventory", pk="id", fks={"branch_id": "sucursales", "product_id": "productos", "batch_id": "batches"}),
    TableSpec("legacy_inventario_actual", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("legacy_movimientos_inventario", pk="id", fks={"producto_id": "productos", "proveedor_id": "proveedores", "batch_id": "batches", "bib_id": "branch_inventory_batches", "sucursal_id": "sucursales", "lote_id": "lotes"}),
    TableSpec("links_pago", pk="id", fks={"pedido_id": "delivery_orders", "payment_id": "payments"}),
    TableSpec("listas_precio", pk="id"),
    TableSpec("login_attempts", pk="id"),
    TableSpec("login_blocks", pk=None),
    TableSpec("logs", pk="id"),
    TableSpec("lotes", pk="id", fks={"producto_id": "productos", "proveedor_id": "proveedores", "sucursal_id": "sucursales", "lote_padre_id": "lotes", "batch_id": "batches"}),
    TableSpec("lotes_tarjetas_pdf", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("loyalty_budget_caps", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("loyalty_challenge_progress", pk="id", fks={"cliente_id": "clientes"}),
    TableSpec("loyalty_challenges", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("loyalty_community_contributions", pk="id", fks={"goal_id": "loyalty_community_goals", "cliente_id": "clientes", "venta_id": "ventas"}),
    TableSpec("loyalty_community_goals", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("loyalty_config", pk=None),
    TableSpec("loyalty_ledger", pk="id", fks={"cliente_id": "clientes", "sucursal_id": "sucursales"}),
    TableSpec("loyalty_level_history", pk="id", fks={"cliente_id": "clientes"}),
    TableSpec("loyalty_multiplier_rules", pk="id"),
    TableSpec("loyalty_points_log", pk="id", fks={"cliente_id": "clientes", "venta_id": "ventas", "branch_id": "sucursales"}),
    TableSpec("loyalty_programs", pk="id"),
    TableSpec("loyalty_redemption_limits", pk=None, fks={"branch_id": "sucursales"}),
    TableSpec("loyalty_roi_tracking", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("loyalty_scores", pk=None, fks={"cliente_id": "clientes"}),
    TableSpec("loyalty_snapshots", pk="id", fks={"cliente_id": "clientes"}),
    TableSpec("loyalty_ticket_messages", pk="id"),
    TableSpec("maintenance_records", pk="id", fks={"asset_id": "assets", "supplier_id": "proveedores", "branch_id": "sucursales", "financial_document_id": "financial_documents", "treasury_movement_id": "treasury_movements", "journal_entry_id": "journal_entries"}),
    TableSpec("mantenimientos", pk="id", fks={"activo_id": "activos"}),
    TableSpec("marketing_messages", pk="id"),
    TableSpec("meat_production_runs", pk="id", fks={"branch_id": "sucursales", "source_product_id": "productos", "user_id": "usuarios"}),
    TableSpec("meat_production_yields", pk="id", fks={"yield_product_id": "productos"}),
    TableSpec("merma_log", pk="id", fks={"producto_id": "productos", "lote_id": "lotes", "produccion_id": "producciones", "batch_id": "batches", "sucursal_id": "sucursales"}),
    TableSpec("mermas", pk="id", fks={"producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("module_toggles", pk=None),
    TableSpec("movimientos_caja", pk="id", fks={"sucursal_id": "sucursales", "venta_id": "ventas", "turno_id": "turnos_caja", "caja_id": "cajas"}),
    TableSpec("movimientos_inventario", pk="id", fks={"producto_id": "productos", "proveedor_id": "proveedores", "batch_id": "batches", "bib_id": "branch_inventory_batches", "sucursal_id": "sucursales", "lote_id": "lotes"}),
    TableSpec("movimientos_lote", pk="id", fks={"lote_id": "lotes"}),
    TableSpec("movimientos_trazabilidad", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("nomina_pagos", pk="id", fks={"empleado_id": "personal"}),
    TableSpec("nomina_records", pk="id", fks={"personal_id": "personal"}),
    TableSpec("notification_inbox", pk="id", fks={"empleado_id": "personal", "sucursal_id": "sucursales"}),
    TableSpec("operating_supplies", pk="id", fks={"supplier_id": "proveedores", "branch_id": "sucursales", "financial_document_id": "financial_documents", "treasury_movement_id": "treasury_movements", "journal_entry_id": "journal_entries"}),
    TableSpec("ordenes_compra", pk="id", fks={"proveedor_id": "proveedores", "pr_id": "purchase_requests", "sucursal_id": "sucursales"}),
    TableSpec("ordenes_compra_items", pk="id", fks={"orden_id": "ordenes_compra", "producto_id": "productos"}),
    TableSpec("ordenes_cotizacion", pk="id", fks={"cotizacion_id": "cotizaciones", "cliente_id": "clientes", "sucursal_id": "sucursales", "payment_id": "payments"}),
    TableSpec("pagos_cobros", pk="id", fks={"usuario_id": "usuarios"}),
    TableSpec("pagos_cobros_aplicaciones", pk="id", fks={"pago_cobro_id": "pagos_cobros"}),
    TableSpec("paquetes", pk="id", fks={"producto_id": "productos"}),
    TableSpec("paquetes_componentes", pk="id", fks={"paquete_id": "paquetes", "corte_producto_id": "productos"}),
    TableSpec("payments", pk="id", fks={"venta_id": "ventas"}),
    TableSpec("pedidos_whatsapp", pk="id", fks={"cliente_id": "clientes", "venta_id": "ventas", "repartidor_id": "drivers", "sucursal_id": "sucursales"}),
    TableSpec("pedidos_whatsapp_items", pk="id", fks={"pedido_id": "delivery_orders", "producto_id": "productos"}),
    TableSpec("permisos", pk="id"),
    TableSpec("personal", pk="id", fks={"usuario_id": "usuarios"}),
    TableSpec("plan_cuentas", pk="id", fks={"padre_id": "plan_cuentas"}),
    TableSpec("plantillas_compra", pk="id", fks={"proveedor_id": "proveedores", "sucursal_id": "sucursales"}),
    TableSpec("plantillas_compra_items", pk="id", fks={"plantilla_id": "plantillas_compra", "producto_id": "productos"}),
    TableSpec("precios_lista", pk=None, fks={"lista_id": "listas_precio", "producto_id": "productos"}),
    TableSpec("precios_volumen", pk="id", fks={"producto_id": "productos", "lista_id": "listas_precio"}),
    TableSpec("print_job_log", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("produccion_detalle", pk="id", fks={"produccion_id": "producciones", "producto_resultante_id": "productos", "lote_id": "lotes"}),
    TableSpec("producciones", pk="id", fks={"receta_id": "recetas", "producto_base_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("product_forecast_config", pk="id", fks={"product_id": "productos", "branch_id": "sucursales"}),
    TableSpec("product_recipe_components", pk="id", fks={"recipe_id": "product_recipes", "component_product_id": "productos"}),
    TableSpec("product_recipes", pk="id", fks={"product_id": "productos", "piece_product_id": "productos", "base_product_id": "productos", "output_product_id": "productos"}),
    TableSpec("product_recipes_abarrotes", pk="id", fks={"producto_id": "productos", "ingrediente_id": "productos"}),
    TableSpec("production_alerts", pk="id", fks={"batch_id": "batches"}),
    TableSpec("production_batches", pk="id", fks={"product_source_id": "productos", "branch_id": "sucursales", "lote_origen_id": "lotes"}),
    TableSpec("production_cost_ledger", pk="id", fks={"batch_id": "batches", "output_id": "productos", "product_id": "productos"}),
    TableSpec("production_outputs", pk="id", fks={"batch_id": "batches", "product_id": "productos", "lote_hijo_id": "lotes"}),
    TableSpec("production_yield_analysis", pk="id", fks={"batch_id": "batches"}),
    TableSpec("productos", pk="id", fks={"sucursal_id": "sucursales", "producto_padre_id": "productos"}),
    TableSpec("productos_deletion_guard", pk=None, fks={"producto_id": "productos"}),
    TableSpec("promotion_rules", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("proveedores", pk="id"),
    TableSpec("puestos", pk="id"),
    TableSpec("puntos", pk="id", fks={"cliente_id": "clientes", "venta_id": "ventas"}),
    TableSpec("purchase_request_items", pk="id", fks={"pr_id": "purchase_requests", "producto_id": "productos"}),
    TableSpec("purchase_requests", pk="id", fks={"proveedor_id": "proveedores", "sucursal_id": "sucursales"}),
    TableSpec("rasa_sessions", pk="id", fks={"pedido_activo_id": "delivery_orders"}),
    TableSpec("recepcion_items", pk="id", fks={"recepcion_id": "recepciones", "producto_id": "productos", "lote_id": "lotes"}),
    TableSpec("recepciones", pk="id", fks={"proveedor_id": "proveedores", "sucursal_id": "sucursales"}),
    TableSpec("recepciones_pollo", pk="id", fks={"sucursal_id": "sucursales", "producto_id": "productos", "compra_global_id": "compras", "usuario_id": "usuarios", "batch_id": "batches"}),
    TableSpec("receta_componentes", pk="id", fks={"receta_id": "recetas", "producto_id": "productos"}),
    TableSpec("recetas", pk="id", fks={"producto_base_id": "productos"}),
    TableSpec("recetas_consumo", pk="id", fks={"producto_venta_id": "productos"}),
    TableSpec("recetas_consumo_detalle", pk="id", fks={"receta_id": "recetas", "materia_prima_id": "productos"}),
    TableSpec("recipe_dependency_graph", pk=None, fks={"parent_recipe_id": "product_recipes", "child_product_id": "productos"}),
    TableSpec("reconciliation_records", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("referidos", pk="id"),
    TableSpec("rendimiento_derivados", pk="id", fks={"producto_pollo_id": "productos", "producto_derivado_id": "productos", "producto_padre_id": "productos"}),
    TableSpec("rendimiento_pollo", pk="id", fks={"producto_pollo_id": "productos"}),
    TableSpec("replenishment_recommendations", pk="id", fks={"product_id": "productos", "branch_id": "sucursales"}),
    TableSpec("report_export_log", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("reporte_exports", pk="id"),
    TableSpec("rol_permisos", pk="id", fks={"rol_id": "roles"}),
    TableSpec("roles", pk="id"),
    TableSpec("roles_permisos", pk=None, fks={"rol_id": "roles", "permiso_id": "permisos"}),
    TableSpec("sale_refunds", pk="id", fks={"sale_id": "ventas", "sale_item_id": "detalles_venta", "product_id": "productos"}),
    TableSpec("scan_event_log", pk="id", fks={"cliente_id": "clientes", "producto_id": "productos", "sucursal_id": "sucursales"}),
    TableSpec("scheduled_demand_events", pk="id", fks={"sale_id": "ventas", "branch_id": "sucursales", "product_id": "productos", "customer_id": "clientes"}),
    TableSpec("sucursales", pk="id"),
    TableSpec("suppliers", pk="id", fks={"proveedor_id": "proveedores"}),
    TableSpec("sync_batch_log", pk="id", fks={"batch_id": "batches"}),
    TableSpec("sync_conflicts", pk="id"),
    TableSpec("sync_inbox", pk="id"),
    TableSpec("sync_outbox", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("sync_state", pk=None),
    TableSpec("sync_version_history", pk="id"),
    TableSpec("system_constants", pk=None),
    TableSpec("system_integrity_reports", pk="id"),
    TableSpec("system_locks", pk="id", fks={"branch_id": "sucursales"}),
    TableSpec("tarjetas_fidelidad", pk="id", fks={"lote_origen_id": "lotes", "batch_id": "card_batches"}),
    TableSpec("temp_purchase_drafts", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("ticket_design_config", pk="id"),
    TableSpec("tipos_cambio", pk="id"),
    TableSpec("transfer_items", pk="id", fks={"transfer_id": "transferencias", "product_id": "productos", "batch_id": "batches"}),
    TableSpec("transfer_suggestions", pk="id", fks={"product_id": "productos", "origin_branch_id": "sucursales", "dest_branch_id": "sucursales", "transfer_id": "transferencias"}),
    TableSpec("transferencia_detalle", pk="id", fks={"transferencia_id": "transferencias", "producto_id": "productos"}),
    TableSpec("transferencias", pk="id", fks={"origen_id": "sucursales", "destino_id": "sucursales"}),
    TableSpec("transferencias_inventario", pk="id", fks={"producto_id": "productos"}),
    TableSpec("transfers", pk="id", fks={"branch_origin_id": "sucursales", "branch_dest_id": "sucursales"}),
    TableSpec("traspasos_inventario", pk="id", fks={"sucursal_origen_id": "sucursales", "sucursal_destino_id": "sucursales", "producto_id": "productos"}),
    TableSpec("traspasos_pollo", pk="id", fks={"sucursal_origen_id": "sucursales", "sucursal_destino_id": "sucursales", "producto_id": "productos"}),
    TableSpec("trazabilidad_qr", pk="id", fks={"producto_id": "productos", "proveedor_id": "proveedores", "lote_id": "lotes", "sucursal_id": "sucursales", "venta_id": "ventas", "cliente_id": "clientes", "recepcion_id": "recepciones"}),
    TableSpec("treasury_capital", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("treasury_gastos_fijos", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("treasury_ledger", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("treasury_movements", pk="id", fks={"financial_document_id": "financial_documents", "branch_id": "sucursales"}),
    TableSpec("turno_actual", pk=None, fks={"sucursal_id": "sucursales"}),
    TableSpec("turno_asignaciones", pk="id", fks={"personal_id": "personal", "turno_rol_id": "turno_roles"}),
    TableSpec("turno_notificaciones_log", pk="id", fks={"personal_id": "personal"}),
    TableSpec("turno_roles", pk="id"),
    TableSpec("turnos_caja", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("unidades_conversion", pk="id"),
    TableSpec("unidades_medida", pk="id"),
    TableSpec("usuarios", pk="id", fks={"sucursal_id": "sucursales", "empleado_id": "personal", "sucursal_principal_id": "sucursales", "personal_id": "personal"}),
    TableSpec("usuarios_roles", pk=None, fks={"usuario_id": "usuarios", "rol_id": "roles", "sucursal_id": "sucursales"}),
    TableSpec("usuarios_sucursales", pk=None, fks={"usuario_id": "usuarios", "sucursal_id": "sucursales"}),
    TableSpec("vacaciones_personal", pk="id", fks={"personal_id": "personal"}),
    TableSpec("ventas", pk="id", fks={"sucursal_id": "sucursales", "cliente_id": "clientes", "turno_id": "turnos_caja"}),
    TableSpec("ventas_diarias", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("wa_event_log", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("wa_reminder_queue", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("whatsapp_numeros", pk="id", fks={"sucursal_id": "sucursales"}),
    TableSpec("whatsapp_queue", pk="id"),
]
