from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]


def test_phase0_architecture_docs_and_phase1_guardrails_are_installed() -> None:
    required_paths = [
        "docs/architecture/ARCHITECTURE.md",
        "docs/architecture/BACKEND_FRONTEND_LANGUAGE_RULES.md",
        "docs/architecture/DATABASE_COMPATIBILITY.md",
        "docs/architecture/UI_COMPONENT_RULES.md",
        "docs/architecture/EVENT_CATALOG.md",
        "docs/architecture/INSTALLER_AND_UPDATER.md",
        "docs/architecture/REFACTOR_RULES.md",
        "docs/architecture/MODULE_MAP.md",
        "docs/architecture/DELETE_LEGACY_POLICY.md",
        "tests/architecture/architecture_guardrails.py",
        "tests/architecture/allowlists.py",
        "tests/architecture/test_no_sql_in_frontend.py",
        "tests/architecture/test_no_commit_rollback_in_frontend.py",
        "tests/architecture/test_no_schema_changes_outside_migrations.py",
        "tests/architecture/test_no_hardcoded_numeric_defaults_in_ui.py",
        "tests/architecture/test_no_plain_phone_inputs.py",
        "tests/architecture/test_no_entity_combo_mass_loading.py",
        "tests/architecture/test_no_hardcoded_paths.py",
        "tests/architecture/test_no_container_passed_to_services.py",
        "tests/architecture/test_no_deprecated_services_with_business_logic.py",
        "backend/shared/app_paths.py",
        "backend/infrastructure/updater/version_checker.py",
        "backend/infrastructure/updater/update_manifest.py",
        "backend/infrastructure/updater/update_downloader.py",
        "backend/infrastructure/updater/update_installer.py",
        "backend/infrastructure/db/database.py",
        "backend/infrastructure/db/dialect.py",
        "backend/infrastructure/db/unit_of_work.py",
        "backend/infrastructure/db/transaction.py",
        "backend/infrastructure/db/repositories/base_repository.py",
        "backend/api/main.py",
        "backend/api/dependencies.py",
        "frontend/desktop/components/numeric_input.py",
        "frontend/desktop/components/money_input.py",
        "frontend/desktop/components/quantity_input.py",
        "frontend/desktop/components/percent_input.py",
        "frontend/desktop/components/integer_input.py",
        "frontend/desktop/components/phone_input.py",
        "frontend/desktop/components/search_selector.py",
        "frontend/desktop/components/address_input.py",
        "frontend/desktop/components/product_search_box.py",
        "frontend/desktop/components/customer_search_box.py",
        "frontend/desktop/components/supplier_search_box.py",
        "frontend/desktop/components/employee_search_box.py",
        "frontend/desktop/components/branch_search_box.py",
        "frontend/desktop/components/driver_search_box.py",
        "frontend/desktop/components/asset_search_box.py",
        "frontend/desktop/components/status_badge.py",
        "frontend/desktop/components/date_range_filter.py",
        "backend/shared/events/event_bus.py",
        "backend/shared/events/event_contracts.py",
        "backend/shared/events/event_names.py",
        "backend/shared/events/event_dispatcher.py",
        "backend/application/queries/customer_query_service.py",
        "backend/application/queries/product_query_service.py",
        "backend/application/queries/supplier_query_service.py",
        "backend/application/queries/employee_query_service.py",
        "backend/application/queries/branch_query_service.py",
        "backend/application/queries/driver_query_service.py",
        "backend/application/queries/asset_query_service.py",
        "backend/application/queries/delivery_query_service.py",
        "backend/application/queries/transfer_query_service.py",
        "backend/application/queries/waste_query_service.py",
        "backend/application/queries/production_query_service.py",
        "backend/application/queries/quote_query_service.py",
        "backend/application/queries/loyalty_query_service.py",
        "backend/application/queries/cash_register_query_service.py",
        "backend/application/queries/purchase_planning_query_service.py",
        "backend/application/queries/business_intelligence_query_service.py",
        "backend/application/use_cases/register_waste_use_case.py",
        "backend/application/use_cases/create_sale_use_case.py",
        "backend/application/use_cases/execute_meat_production_use_case.py",
        "backend/application/use_cases/dispatch_transfer_use_case.py",
        "backend/application/use_cases/receive_transfer_use_case.py",
        "backend/application/use_cases/create_delivery_order_use_case.py",
        "backend/application/use_cases/create_product_use_case.py",
        "backend/application/use_cases/generate_z_cut_use_case.py",
        "backend/application/use_cases/convert_quote_to_sale_use_case.py",
        "backend/application/use_cases/generate_purchase_plan_use_case.py",
        "backend/application/commands/base_command.py",
        "backend/application/dto/use_case_result.py",
        "pos_spj_v13.4/core/services/configuration_settings_service.py",
        "pos_spj_v13.4/migrations/standalone/096_configuration_services_schema.py",
    ]

    missing_paths = [path for path in required_paths if not (REPO_ROOT / path).is_file()]
    assert not missing_paths, "Missing refactor scaffolding files: " + ", ".join(missing_paths)
