"""Repository ports for the Integrations bounded context — SET-19.
Protocols only — implementations land in
``backend/infrastructure/db/repositories/integrations/``. Every id is a
UUIDv7 string. Mirrors backend/domain/customer_display/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.integrations.entities.integration_definition import IntegrationDefinition
from backend.domain.integrations.entities.integration_health_check import IntegrationHealthCheck
from backend.domain.integrations.entities.integration_instance import IntegrationInstance
from backend.domain.integrations.entities.webhook_endpoint import WebhookEndpoint


class IntegrationDefinitionRepositoryPort(Protocol):
    def save(self, definition: IntegrationDefinition) -> None: ...
    def get(self, definition_id: str) -> IntegrationDefinition | None: ...
    def get_by_code(self, code: str) -> IntegrationDefinition | None: ...
    def list_active(self) -> list[IntegrationDefinition]: ...


class IntegrationInstanceRepositoryPort(Protocol):
    def save(self, instance: IntegrationInstance) -> None: ...
    def get(self, instance_id: str) -> IntegrationInstance | None: ...
    def list_by_definition(self, definition_id: str) -> list[IntegrationInstance]: ...
    def list_active(self) -> list[IntegrationInstance]: ...


class IntegrationHealthCheckRepositoryPort(Protocol):
    def save(self, check: IntegrationHealthCheck) -> None: ...
    def list_for_instance(self, instance_id: str, *, limit: int = 20) -> list[IntegrationHealthCheck]: ...


class WebhookEndpointRepositoryPort(Protocol):
    def save(self, endpoint: WebhookEndpoint) -> None: ...
    def get(self, endpoint_id: str) -> WebhookEndpoint | None: ...
    def get_by_code(self, code: str) -> WebhookEndpoint | None: ...
    def list_by_instance(self, instance_id: str) -> list[WebhookEndpoint]: ...
