"""Canonical enums for the procurement bounded context."""

from __future__ import annotations

from enum import Enum


class PurchaseFlow(str, Enum):
    DIRECT_FLOW = "DIRECT_FLOW"
    STANDARD_FLOW = "STANDARD_FLOW"
    ENTERPRISE_FLOW = "ENTERPRISE_FLOW"
    EMERGENCY_FLOW = "EMERGENCY_FLOW"


class PurchaseType(str, Enum):
    INVENTORY = "INVENTORY"
    RAW_MATERIAL = "RAW_MATERIAL"
    POULTRY = "POULTRY"
    GROCERY = "GROCERY"
    PACKAGING = "PACKAGING"
    SUPPLIES = "SUPPLIES"
    SERVICE = "SERVICE"
    EXPENSE = "EXPENSE"
    ASSET = "ASSET"
    MAINTENANCE = "MAINTENANCE"
    LOGISTICS = "LOGISTICS"
    EMERGENCY = "EMERGENCY"
    DIRECT = "DIRECT"
    CONTRACT = "CONTRACT"
    RECURRING = "RECURRING"


class SourceChannel(str, Enum):
    PROCUREMENT_DESKTOP = "PROCUREMENT_DESKTOP"
    PROCUREMENT_DIRECT = "PROCUREMENT_DIRECT"
    MOBILE_RECEIVING = "MOBILE_RECEIVING"
    FORECAST = "FORECAST"
    MINIMUM_STOCK = "MINIMUM_STOCK"
    POS_REPLENISHMENT_REQUEST = "POS_REPLENISHMENT_REQUEST"
    PRODUCTION_PLAN = "PRODUCTION_PLAN"
    CUSTOMER_ORDER = "CUSTOMER_ORDER"
    MAINTENANCE = "MAINTENANCE"
    ASSET_REQUEST = "ASSET_REQUEST"
    RECURRING_PLAN = "RECURRING_PLAN"
    EMERGENCY = "EMERGENCY"
    IMPORT = "IMPORT"
    API = "API"


class PaymentCondition(str, Enum):
    IMMEDIATE_PAYMENT = "IMMEDIATE_PAYMENT"
    SUPPLIER_CREDIT = "SUPPLIER_CREDIT"
    ADVANCE_PAYMENT = "ADVANCE_PAYMENT"
    MIXED = "MIXED"
    PAYMENT_INSTRUCTION = "PAYMENT_INSTRUCTION"


class PaymentSource(str, Enum):
    PETTY_CASH = "PETTY_CASH"
    TREASURY_ACCOUNT = "TREASURY_ACCOUNT"
    BANK_TRANSFER = "BANK_TRANSFER"
    AUTHORIZED_CARD = "AUTHORIZED_CARD"
    MERCADO_PAGO = "MERCADO_PAGO"
    OTHER_CONFIGURED_SOURCE = "OTHER_CONFIGURED_SOURCE"


class DirectPurchaseMode(str, Enum):
    DIRECT_WITH_IMMEDIATE_RECEIPT = "DIRECT_WITH_IMMEDIATE_RECEIPT"
    DIRECT_WITH_PENDING_RECEIPT = "DIRECT_WITH_PENDING_RECEIPT"
    DIRECT_SERVICE = "DIRECT_SERVICE"
    DIRECT_EXPENSE = "DIRECT_EXPENSE"
    DIRECT_ASSET = "DIRECT_ASSET"


class DocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_AUTHORIZATION = "PENDING_AUTHORIZATION"
    CONFIRMED = "CONFIRMED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"
    REVERSED = "REVERSED"


class RequisitionStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    PARTIALLY_SOURCED = "PARTIALLY_SOURCED"
    SOURCED = "SOURCED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"


class PurchaseOrderStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    RECEIVED = "RECEIVED"
    PARTIALLY_INVOICED = "PARTIALLY_INVOICED"
    INVOICED = "INVOICED"
    ON_HOLD = "ON_HOLD"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PricingBasis(str, Enum):
    PER_UNIT = "PER_UNIT"
    PER_KILOGRAM = "PER_KILOGRAM"
    PER_GRAM = "PER_GRAM"
    PER_LITER = "PER_LITER"
    PER_PACKAGE = "PER_PACKAGE"
    PER_CASE = "PER_CASE"
    FIXED_SERVICE = "FIXED_SERVICE"


class ProcurementRole(str, Enum):
    """Roles for separation-of-duties checks."""

    REQUESTER = "REQUESTER"
    BUYER = "BUYER"
    APPROVER = "APPROVER"
    RECEIVER = "RECEIVER"
    QUALITY_INSPECTOR = "QUALITY_INSPECTOR"
    INVOICE_CLERK = "INVOICE_CLERK"
    VARIANCE_RELEASER = "VARIANCE_RELEASER"
    PAYMENT_REQUESTER = "PAYMENT_REQUESTER"
    PAYMENT_EXECUTOR = "PAYMENT_EXECUTOR"
    REVERSAL_AUTHORIZER = "REVERSAL_AUTHORIZER"


class DiscrepancyType(str, Enum):
    SHORT_QUANTITY = "SHORT_QUANTITY"
    OVER_QUANTITY = "OVER_QUANTITY"
    WRONG_PRODUCT = "WRONG_PRODUCT"
    DAMAGED = "DAMAGED"
    QUALITY_FAILURE = "QUALITY_FAILURE"
    TEMPERATURE_FAILURE = "TEMPERATURE_FAILURE"
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    PRICE_DIFFERENCE = "PRICE_DIFFERENCE"
    LOT_DIFFERENCE = "LOT_DIFFERENCE"
    EXPIRATION_FAILURE = "EXPIRATION_FAILURE"
