"""Repository ports for the Appearance bounded context — SET-22.
Protocols only — implementations land in
``backend/infrastructure/db/repositories/appearance/``. Every id is a
UUIDv7 string. Mirrors backend/domain/feature_flags/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.appearance.entities.appearance_preference import AppearancePreference
from backend.domain.appearance.entities.density_profile import DensityProfile
from backend.domain.appearance.entities.design_token import DesignToken
from backend.domain.appearance.entities.theme import Theme
from backend.domain.appearance.enums import DensityLevel


class ThemeRepositoryPort(Protocol):
    def save(self, theme: Theme) -> None: ...
    def get(self, theme_id: str) -> Theme | None: ...
    def get_by_code(self, code: str) -> Theme | None: ...
    def get_default(self) -> Theme | None: ...
    def list_active(self) -> list[Theme]: ...


class DesignTokenRepositoryPort(Protocol):
    def save(self, token: DesignToken) -> None: ...
    def get(self, token_id: str) -> DesignToken | None: ...

    def list_for_theme(self, theme_id: str) -> list[DesignToken]:
        """Returns GLOBAL tokens (theme_id IS NULL) plus tokens scoped to
        theme_id — the raw material for
        `policies/token_resolution_policy.py::resolve_tokens_for_theme`."""
        ...


class DensityProfileRepositoryPort(Protocol):
    def save(self, profile: DensityProfile) -> None: ...
    def get(self, profile_id: str) -> DensityProfile | None: ...
    def get_by_level(self, level: DensityLevel) -> DensityProfile | None: ...
    def list_active(self) -> list[DensityProfile]: ...


class AppearancePreferenceRepositoryPort(Protocol):
    def save(self, preference: AppearancePreference) -> None: ...
    def get(self, preference_id: str) -> AppearancePreference | None: ...
    def list_active(self) -> list[AppearancePreference]: ...
