"""Granular inventory permission codes (§45-49).

Inventory is never gated by a single ``INVENTARIO`` permission. Every sensitive
action — movement, adjustment, transfer approval/dispatch/receipt, count
confirm, quarantine release, manual weight override — has its own code, and the
backend re-validates each one on every use case (hiding a button is not
security).
"""

from __future__ import annotations


class InventoryPermissions:
    # ── consulta (§46) ────────────────────────────────────────────────────
    ACCESS = "INVENTORY_ACCESS"
    VIEW = "INVENTORY_VIEW"
    VIEW_OWN_BRANCH = "INVENTORY_VIEW_OWN_BRANCH"
    VIEW_ASSIGNED_BRANCHES = "INVENTORY_VIEW_ASSIGNED_BRANCHES"
    VIEW_ALL_BRANCHES = "INVENTORY_VIEW_ALL_BRANCHES"
    VIEW_COST_REFERENCE = "INVENTORY_VIEW_COST_REFERENCE"
    VIEW_TRACEABILITY = "INVENTORY_VIEW_TRACEABILITY"
    VIEW_AUDIT = "INVENTORY_VIEW_AUDIT"
    EXPORT = "INVENTORY_EXPORT"

    # ── almacenes y ubicaciones (§46) ─────────────────────────────────────
    WAREHOUSE_VIEW = "INVENTORY_WAREHOUSE_VIEW"
    WAREHOUSE_CREATE = "INVENTORY_WAREHOUSE_CREATE"
    WAREHOUSE_EDIT = "INVENTORY_WAREHOUSE_EDIT"
    WAREHOUSE_ACTIVATE = "INVENTORY_WAREHOUSE_ACTIVATE"
    WAREHOUSE_BLOCK = "INVENTORY_WAREHOUSE_BLOCK"
    LOCATION_VIEW = "INVENTORY_LOCATION_VIEW"
    LOCATION_MANAGE = "INVENTORY_LOCATION_MANAGE"

    # ── movimientos (§46) ─────────────────────────────────────────────────
    MOVEMENT_VIEW = "INVENTORY_MOVEMENT_VIEW"
    MOVEMENT_CREATE = "INVENTORY_MOVEMENT_CREATE"
    MOVEMENT_REVERSE = "INVENTORY_MOVEMENT_REVERSE"
    MOVEMENT_OVERRIDE = "INVENTORY_MOVEMENT_OVERRIDE"

    # ── lotes y series (§46) ──────────────────────────────────────────────
    LOT_VIEW = "INVENTORY_LOT_VIEW"
    LOT_CREATE = "INVENTORY_LOT_CREATE"
    LOT_EDIT = "INVENTORY_LOT_EDIT"
    LOT_BLOCK = "INVENTORY_LOT_BLOCK"
    LOT_RELEASE = "INVENTORY_LOT_RELEASE"
    SERIAL_MANAGE = "INVENTORY_SERIAL_MANAGE"

    # ── reservas (§46) ────────────────────────────────────────────────────
    RESERVATION_VIEW = "INVENTORY_RESERVATION_VIEW"
    RESERVATION_CREATE = "INVENTORY_RESERVATION_CREATE"
    RESERVATION_RELEASE = "INVENTORY_RESERVATION_RELEASE"
    ALLOCATION_OVERRIDE = "INVENTORY_ALLOCATION_OVERRIDE"

    # ── transferencias (§46) ──────────────────────────────────────────────
    TRANSFER_VIEW = "INVENTORY_TRANSFER_VIEW"
    TRANSFER_CREATE = "INVENTORY_TRANSFER_CREATE"
    TRANSFER_EDIT = "INVENTORY_TRANSFER_EDIT"
    TRANSFER_SUBMIT = "INVENTORY_TRANSFER_SUBMIT"
    TRANSFER_APPROVE = "INVENTORY_TRANSFER_APPROVE"
    TRANSFER_DISPATCH = "INVENTORY_TRANSFER_DISPATCH"
    TRANSFER_RECEIVE = "INVENTORY_TRANSFER_RECEIVE"
    TRANSFER_RESOLVE_DIFFERENCE = "INVENTORY_TRANSFER_RESOLVE_DIFFERENCE"
    TRANSFER_CANCEL = "INVENTORY_TRANSFER_CANCEL"

    # ── conteos (§46) ─────────────────────────────────────────────────────
    COUNT_VIEW = "INVENTORY_COUNT_VIEW"
    COUNT_CREATE = "INVENTORY_COUNT_CREATE"
    COUNT_EXECUTE = "INVENTORY_COUNT_EXECUTE"
    COUNT_CONFIRM = "INVENTORY_COUNT_CONFIRM"
    COUNT_RECOUNT = "INVENTORY_COUNT_RECOUNT"
    COUNT_APPROVE = "INVENTORY_COUNT_APPROVE"
    COUNT_VIEW_EXPECTED = "INVENTORY_COUNT_VIEW_EXPECTED"

    # ── ajustes (§46) ─────────────────────────────────────────────────────
    ADJUSTMENT_VIEW = "INVENTORY_ADJUSTMENT_VIEW"
    ADJUSTMENT_CREATE = "INVENTORY_ADJUSTMENT_CREATE"
    ADJUSTMENT_APPROVE = "INVENTORY_ADJUSTMENT_APPROVE"
    ADJUSTMENT_POST = "INVENTORY_ADJUSTMENT_POST"
    ADJUSTMENT_REVERSE = "INVENTORY_ADJUSTMENT_REVERSE"

    # ── calidad y cuarentena (§46) ────────────────────────────────────────
    QUARANTINE_VIEW = "INVENTORY_QUARANTINE_VIEW"
    QUARANTINE_CREATE = "INVENTORY_QUARANTINE_CREATE"
    QUARANTINE_RELEASE = "INVENTORY_QUARANTINE_RELEASE"
    QUALITY_BLOCK = "INVENTORY_QUALITY_BLOCK"
    QUALITY_RELEASE = "INVENTORY_QUALITY_RELEASE"
    DISPOSAL_AUTHORIZE = "INVENTORY_DISPOSAL_AUTHORIZE"

    # ── peso y hardware (§46) ─────────────────────────────────────────────
    WEIGHT_CAPTURE = "INVENTORY_WEIGHT_CAPTURE"
    WEIGHT_MANUAL_OVERRIDE = "INVENTORY_WEIGHT_MANUAL_OVERRIDE"
    SCALE_MANAGE = "INVENTORY_SCALE_MANAGE"
    LABEL_PRINT = "INVENTORY_LABEL_PRINT"
    LABEL_REPRINT = "INVENTORY_LABEL_REPRINT"

    # ── negativo (override) (§16) ─────────────────────────────────────────
    NEGATIVE_OVERRIDE = "INVENTORY_NEGATIVE_OVERRIDE"

    # ── configuración (§46) ───────────────────────────────────────────────
    SETTINGS_VIEW = "INVENTORY_SETTINGS_VIEW"
    SETTINGS_MANAGE = "INVENTORY_SETTINGS_MANAGE"
    NOTIFICATIONS_MANAGE = "INVENTORY_NOTIFICATIONS_MANAGE"
    WHATSAPP_ALERTS_MANAGE = "INVENTORY_WHATSAPP_ALERTS_MANAGE"


ALL_INVENTORY_PERMISSIONS = frozenset(
    v for k, v in vars(InventoryPermissions).items()
    if not k.startswith("_") and isinstance(v, str)
)
