"""Repository ports for the Settings (Configuration Governance) bounded
context — SET-2.

Protocols only — implementations land in
``backend/infrastructure/db/repositories/settings/`` in SET-3 (born-clean
schema). Every id is a UUIDv7 string. Mirrors
backend/domain/crm/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.settings.entities.branch_profile import BranchProfile
from backend.domain.settings.entities.company_profile import CompanyProfile
from backend.domain.settings.entities.configuration_definition import ConfigurationDefinition
from backend.domain.settings.entities.configuration_value import ConfigurationValue
from backend.domain.settings.entities.workstation import Workstation
from backend.domain.settings.value_objects.configuration_scope import ConfigurationScope


class ConfigurationDefinitionRepositoryPort(Protocol):
    def save(self, definition: ConfigurationDefinition) -> None: ...
    def get(self, definition_id: str) -> ConfigurationDefinition | None: ...
    def get_by_key(self, key: str) -> ConfigurationDefinition | None: ...
    def list_by_module(self, module: str) -> list[ConfigurationDefinition]: ...
    def list_all(self) -> list[ConfigurationDefinition]: ...


class ConfigurationValueRepositoryPort(Protocol):
    def save(self, value: ConfigurationValue, *, operation_id: str | None = None) -> None: ...
    def get(self, value_id: str) -> ConfigurationValue | None: ...
    def list_candidates(
        self, definition_id: str, scopes: tuple[ConfigurationScope, ...],
    ) -> list[ConfigurationValue]:
        """Every value (any status) for `definition_id` whose scope is one
        of `scopes` — the resolution service filters by effectiveness."""
        ...
    def list_active_for_scope(self, scope: ConfigurationScope) -> list[ConfigurationValue]: ...
    def get_by_operation_id(self, operation_id: str) -> ConfigurationValue | None: ...


class CompanyProfileRepositoryPort(Protocol):
    def save(self, profile: CompanyProfile) -> None: ...
    def get(self, profile_id: str) -> CompanyProfile | None: ...
    def list_active(self) -> list[CompanyProfile]: ...


class BranchProfileRepositoryPort(Protocol):
    def save(self, profile: BranchProfile) -> None: ...
    def get(self, branch_id: str) -> BranchProfile | None: ...
    def get_by_code(self, code: str) -> BranchProfile | None: ...
    def list_active(self) -> list[BranchProfile]: ...


class WorkstationRepositoryPort(Protocol):
    def save(self, workstation: Workstation) -> None: ...
    def get(self, workstation_id: str) -> Workstation | None: ...
    def get_by_code(self, code: str) -> Workstation | None: ...
    def list_by_branch(self, branch_id: str) -> list[Workstation]: ...
    def list_active(self) -> list[Workstation]: ...
    def list_all(self) -> list[Workstation]: ...
