"""Canonical module permission catalog for SPJ POS.

This catalog is the source of truth for module visibility. UI navigation,
Configuración permission matrix and SessionContext checks must all use the same
`MODULO.accion` permission code format.
"""
from __future__ import annotations

CANONICAL_MODULE_PERMISSIONS: dict[str, list[str]] = {
    "DASHBOARD": ["ver"],
    "POS": ["ver", "crear", "cancelar", "descuento"],
    # Bounded context de Caja (granular; ver backend/application/cash_register/permissions.py).
    "CAJA": [
        "ver", "ver.sucursal_propia", "ver.sucursales_asignadas",
        "ver.todas_sucursales", "ver.importes_sensibles", "ver.auditoria",
        "exportar",
        "caja.ver", "caja.crear", "caja.editar", "caja.activar",
        "caja.bloquear", "caja.retirar",
        "cajon.ver", "cajon.gestionar", "cajon.abrir",
        "cajon.abrir_sin_venta",
        "terminal.ver", "terminal.gestionar", "terminal.operar",
        "turno.ver", "turno.abrir", "turno.suspender", "turno.reanudar",
        "turno.pre_cerrar", "turno.cerrar", "turno.forzar_cierre",
        "turno.reasignar",
        "movimiento.ver", "movimiento.ingreso", "movimiento.retiro",
        "movimiento.safe_drop", "movimiento.reversar",
        "movimiento.autorizar_exceso",
        "conteo.ver", "conteo.iniciar", "conteo.capturar",
        "conteo.confirmar", "conteo.ver_esperado", "conteo.cancelar",
        "conteo.sobrescribir",
        "corte_x.ver", "corte_x.generar", "corte_x.imprimir",
        "corte_x.reimprimir",
        "corte_z.ver", "corte_z.generar", "corte_z.revisar",
        "corte_z.imprimir", "corte_z.reimprimir",
        "diferencia.ver", "diferencia.explicar", "diferencia.revisar",
        "diferencia.resolver", "diferencia.castigar",
        "retiro_seguridad.ver", "retiro_seguridad.crear",
        "retiro_seguridad.autorizar",
        "entrega.ver", "entrega.preparar", "entrega.entregar",
        "entrega.recibir", "entrega.disputar", "entrega.cancelar",
        "deposito.ver", "deposito.preparar", "deposito.cancelar",
        "pago.ver", "pago.registrar", "pago.reversar",
        "medio_pago.ver", "medio_pago.gestionar",
        "terminal_pago.ver", "terminal_pago.gestionar",
        "terminal_pago.conciliar_operacion",
        "reembolso.ver", "reembolso.solicitar", "reembolso.ejecutar",
        "reembolso.autorizar", "reembolso.sobrescribir",
        "evento_cajon.ver",
        "hardware.ver", "hardware.diagnosticar", "hardware.gestionar",
        "imprimir", "reimprimir",
        "configuracion.ver", "configuracion.editar",
        "notificacion.ver", "notificacion.gestionar", "whatsapp.gestionar",
        "sync.ver", "sync.gestionar",
    ],
    # Bounded context de Inventario (granular; ver
    # backend/application/inventory/permissions.py). El workflow de
    # transferencias vive en TRANSFERENCIAS.*; Inventario sólo expone
    # `transito.ver` (lectura del stock en tránsito).
    "INVENTARIO": [
        "acceso", "ver", "ver.sucursal_propia", "ver.sucursales_asignadas",
        "ver.todas_sucursales", "ver.costo_referencia", "ver.trazabilidad",
        "ver.auditoria", "exportar", "trazabilidad.vincular",
        "almacen.ver", "almacen.crear", "almacen.editar", "almacen.activar",
        "almacen.bloquear", "almacen.desactivar",
        "ubicacion.ver", "ubicacion.gestionar",
        "movimiento.ver", "movimiento.crear_manual", "movimiento.reversar",
        "movimiento.sobrescribir", "movimiento.permitir_negativo",
        "lote.ver", "lote.crear", "lote.editar", "lote.bloquear", "lote.liberar",
        "lote.imprimir", "lote.reimprimir",
        "serie.gestionar",
        "reserva.ver", "reserva.crear", "reserva.liberar",
        "reserva.sobrescribir_asignacion",
        "transito.ver",
        "conteo.ver", "conteo.crear", "conteo.ejecutar", "conteo.confirmar",
        "conteo.recontar", "conteo.aprobar", "conteo.ver_esperado",
        "ajuste.ver", "ajuste.crear", "ajuste.aprobar", "ajuste.postear",
        "ajuste.reversar",
        "cuarentena.ver", "cuarentena.crear", "cuarentena.liberar",
        "cuarentena.disponer",
        "calidad.bloquear", "calidad.liberar",
        "peso.capturar", "peso.capturar_manual",
        "bascula.usar", "bascula.gestionar",
        "recepcion.ver", "recepcion.inspeccionar", "recepcion.reversar",
        "reposicion.ver", "reposicion.configurar", "reposicion.generar",
        "temperatura.ver", "temperatura.registrar", "temperatura.resolver",
        "configuracion.ver", "configuracion.editar",
        "notificacion.gestionar",
        "whatsapp.gestionar",
    ],
    "TRANSFERENCIAS": ["ver", "crear", "recibir", "cancelar"],
    "PRODUCTOS": ["ver", "crear", "editar", "eliminar"],
    # Bounded context de Customer Master (granular; ver
    # backend/application/customers/permissions.py). "ver", "crear",
    # "editar", "credito" se conservan por compatibilidad con
    # modulos/clientes.py (legacy) — no autorizar código nuevo contra ellos.
    "CLIENTES": [
        "ver", "crear", "editar", "credito",
        "acceso", "dashboard.ver", "buscar", "buscar.global",
        "configuracion.ver", "configuracion.editar",
        "ver.propia", "ver.equipo", "ver.sucursal", "ver.territorio",
        "ver.cartera", "ver.compania",
        "editar.propia", "editar.sensible",
        "activar", "desactivar", "suspender", "bloquear", "cerrar", "reabrir", "anonimizar",
        "contacto.ver", "contacto.crear", "contacto.editar", "contacto.eliminar",
        "contacto.verificar", "contacto.marcar_principal",
        "direccion.ver", "direccion.crear", "direccion.editar", "direccion.eliminar",
        "direccion.marcar_predeterminada",
        "fiscal.ver", "fiscal.editar", "fiscal.validar",
        "credito.ver", "credito.ver_resumen", "credito.ver_sensible",
        "credito.solicitar", "credito.revisar", "credito.aprobar", "credito.rechazar",
        "credito.limite.editar", "credito.limite.sobrescribir",
        "credito.suspender", "credito.bloquear", "credito.reabrir", "credito.cerrar",
        "credito.historial.ver", "credito.exportar",
        "consentimiento.ver", "consentimiento.capturar", "consentimiento.retirar",
        "consentimiento.evidencia.ver",
        "preferencia_comunicacion.ver", "preferencia_comunicacion.gestionar",
        "privacidad.solicitud.ver", "privacidad.solicitud.crear",
        "privacidad.solicitud.procesar", "privacidad.solicitud.aprobar",
        "sensible.ver", "sensible.exportar", "sensible.desenmascarar",
        "calidad.ver", "calidad.resolver",
        "duplicados.ver", "duplicados.revisar", "duplicados.descartar", "duplicados.fusionar",
        "importar", "importar.aprobar", "exportar", "actualizacion_masiva",
        "auditoria.ver",
        "elegibilidad_comercial.verificar",
        "pedidos.ver", "entregas.ver", "whatsapp.ver", "fidelidad.ver",
    ],
    # Visibilidad del módulo nuevo (frontend/desktop/modules/customers_crm/),
    # adicional al legacy "CLIENTES" de arriba mientras ambos coexisten. Los
    # permisos granulares que el módulo usa internamente ya están
    # registrados bajo "CLIENTES"/"CRM" (CustomerPermissions/CRMPermissions);
    # esta entrada es solo la puerta de entrada al menú lateral.
    "CLIENTES_CRM": ["ver"],
    # Bounded context CRM (relación comercial: leads, oportunidades,
    # actividades, atención; granular, ver backend/application/crm/permissions.py).
    "CRM": [
        "leads.ver", "leads.ver.propia", "leads.ver.equipo",
        "leads.crear", "leads.editar", "leads.asignar", "leads.reasignar",
        "leads.calificar", "leads.descalificar", "leads.convertir",
        "leads.archivar", "leads.exportar",
        "oportunidades.ver", "oportunidades.ver.propia", "oportunidades.ver.equipo",
        "oportunidades.crear", "oportunidades.editar",
        "oportunidades.asignar", "oportunidades.reasignar",
        "oportunidades.cambiar_etapa", "oportunidades.sobrescribir_etapa",
        "oportunidades.marcar_ganada", "oportunidades.marcar_perdida",
        "oportunidades.reabrir",
        "pipeline.ver", "forecast.ver", "forecast.ver.equipo", "forecast.ver.compania",
        "actividades.ver", "actividades.crear", "actividades.editar",
        "actividades.completar", "actividades.cancelar", "actividades.reasignar",
        "tareas.ver", "tareas.crear", "tareas.asignar", "tareas.reasignar",
        "tareas.completar", "tareas.cancelar", "tareas.reprogramar",
        "notas.ver", "notas.crear", "notas.editar.propia", "notas.eliminar.propia",
        "notas.ver.privada", "notas.crear.privada",
        "recordatorios.crear",
        "casos.ver", "casos.ver.propia", "casos.ver.equipo",
        "casos.crear", "casos.editar", "casos.asignar", "casos.reasignar",
        "casos.escalar", "casos.resolver", "casos.cerrar", "casos.reabrir",
        "casos.ver.sensible",
        "sla.ver", "sla.gestionar", "sla.sobrescribir",
        "segmentos.ver", "segmentos.crear", "segmentos.editar",
        "segmentos.asignar", "segmentos.remover",
        "etiquetas.ver", "etiquetas.crear", "etiquetas.editar",
        "etiquetas.asignar", "etiquetas.remover",
        "territorios.ver", "territorios.gestionar",
        "carteras.ver", "carteras.gestionar", "carteras.asignar",
        "propietario.ver", "propietario.asignar", "propietario.reasignar",
        "bi.exportar",
    ],
    "MERMA": ["ver", "crear", "autorizar"],
    "DELIVERY": ["ver", "crear", "asignar", "entregar"],
    # Bounded context de Compras (granular; ver backend/application/procurement/permissions.py).
    "COMPRAS": [
        "ver", "ver.sucursal_propia", "ver.sucursales_asignadas", "ver.todas_sucursales",
        "ver.costos", "ver.margenes", "ver.pagos", "ver.credito_proveedor", "ver.auditoria",
        "ver.analitica", "exportar",
        "directa.ver", "directa.crear", "directa.editar", "directa.confirmar",
        "directa.guardar_borrador", "directa.proveedor_ocasional", "directa.crear_producto",
        "directa.sobrescribir_precio", "directa.sobrescribir_costo", "directa.sobre_recibir",
        "directa.cancelar", "directa.reversar", "directa.imprimir",
        "pago.inmediato", "pago.caja_chica", "pago.tesoreria", "pago.transferencia",
        "credito_proveedor.usar", "anticipo.usar", "condiciones.mixtas",
        "limite.sobrescribir", "pago.ver_referencia",
        "solicitud.ver", "solicitud.crear", "solicitud.editar", "solicitud.enviar",
        "solicitud.aprobar", "solicitud.rechazar", "solicitud.cancelar",
        "rfq.crear", "rfq.enviar", "cotizacion.capturar", "cotizacion.editar",
        "cotizacion.comparar", "cotizacion.adjudicar", "cotizacion.sobrescribir_seleccion",
        "orden.ver", "orden.crear", "orden.editar", "orden.enviar_aprobacion",
        "orden.aprobar", "orden.enviar", "orden.confirmar", "orden.versionar",
        "orden.cancelar", "orden.cerrar",
        "recepcion.ver", "recepcion.crear", "recepcion.directa", "recepcion.completar",
        "recepcion.parcial", "recepcion.tolerancia", "recepcion.peso_manual",
        "recepcion.rechazar", "recepcion.reversar", "recepcion.cuarentena",
        "recepcion.devolucion", "calidad.inspeccionar", "calidad.liberar",
        "factura.ver", "factura.capturar", "factura.editar", "factura.conciliar",
        "factura.liberar_diferencia", "factura.bloquear", "factura.cancelar",
    ],
    # Compra en origen / logística de embarques (ver backend/application/logistics/authorization.py).
    "LOGISTICA": [
        "embarque.ver", "embarque.crear", "embarque.despachar", "embarque.forzar",
        "contenedor.gestionar", "contenedor.adjuntar", "contenedor.mover", "contenedor.sellar",
        "contenedor.liberar", "contenedor.escanear", "etiqueta.imprimir",
    ],
    "COTIZACIONES": ["ver", "crear", "aprobar", "convertir"],
    # Bounded context de Procesamiento Cárnico / Meat Processing (granular; ver
    # backend/application/meat_processing/permissions.py). Reutiliza la clave
    # histórica "PRODUCCION" (coincide con el botón del menú lateral,
    # interfaz/menu_lateral.py: "Procesamiento Cárnico" → "PRODUCCION") en vez de
    # introducir una clave paralela — una sola ruta canónica para la misma área
    # funcional (§3/§64 del prompt maestro de refactor).
    "PRODUCCION": [
        "acceso", "ver", "ver.sucursal_propia", "ver.sucursales_asignadas",
        "ver.todas_sucursales", "exportar", "ver.auditoria",
        "dashboard.ver",
        "preparacion.ver", "en_proceso.ver", "despiece.ver", "derivados.ver",
        "empaque_etiquetado.ver", "lotes_producidos.ver", "calidad.ver",
        "incidencias.ver", "trazabilidad.ver", "alertas.ver", "analisis.ver",
        "plan.ver", "plan.crear", "plan.editar", "plan.aprobar", "plan.cancelar",
        "orden.ver", "orden.crear", "orden.editar", "orden.aprobar",
        "orden.liberar", "orden.iniciar", "orden.pausar", "orden.reanudar",
        "orden.completar", "orden.cerrar", "orden.cancelar", "orden.reversar",
        "material.ver", "material.asignar", "material.sustituir",
        "consumo.capturar", "consumo.sobrescribir",
        "peso.ver", "peso.capturar", "peso.capturar_manual", "bascula.gestionar",
        "output.ver", "output.capturar", "output.coproducto.capturar",
        "output.subproducto.capturar", "output.derivado.capturar",
        "output.merma.capturar",
        "rendimiento.ver", "rendimiento.revisar", "rendimiento.aprobar",
        "rendimiento.sobrescribir",
        "reproceso.ver", "reproceso.crear", "reproceso.aprobar",
        "reproceso.ejecutar", "reproceso.cerrar",
        "empaque.ejecutar", "etiqueta.imprimir", "etiqueta.reimprimir",
        "configuracion.ver", "configuracion.editar",
        "notificacion.gestionar", "whatsapp.gestionar",
        # Sacrificio futuro (§37/§50) — feature-flagged, mismo bounded context.
        "sacrificio.acceso", "sacrificio.recepcion_animal",
        "sacrificio.lote_animal.gestionar", "sacrificio.orden.crear",
        "sacrificio.orden.aprobar", "sacrificio.ejecutar",
        "sacrificio.ante_mortem.registrar", "sacrificio.post_mortem.registrar",
        "sacrificio.canal.crear", "sacrificio.canal.clasificar",
        "sacrificio.decomiso.registrar", "sacrificio.enfriamiento.gestionar",
    ],
    "ETIQUETAS": ["ver", "imprimir"],
    "PLANEACION_COMPRAS": ["ver", "generar"],
    "FINANZAS_UNIFICADAS": ["ver"],
    # Bounded context financiero (nuevo). Los permisos de instrumentos
    # comerciales siguen §24 del contrato: nunca autorizar por nombre de rol.
    "FINANZAS": [
        "ver",
        "asiento.crear",
        "asiento.reversar",
        "periodo.cerrar",
        "periodo.reabrir",
        "cxc.ver",
        "cobro.crear",
        "cxp.ver",
        "pago.programar",
        "pago.autorizar",
        "pago.ejecutar",
        "tesoreria.ver",
        "tesoreria.transferir",
        "conciliacion.ver",
        "conciliacion.ejecutar",
        "presupuesto.ver",
        "presupuesto.aprobar",
        "activo.ver",
        "activo.capitalizar",
        "estados.ver",
        "commercial_obligation.read",
        "commercial_obligation.reconcile",
        "commercial_posting_profile.read",
        "commercial_posting_profile.manage",
        "commercial_adjustment.create",
        "commercial_adjustment.authorize",
    ],
    "ACTIVOS": ["ver", "crear", "mantenimiento"],
    "RRHH": ["ver", "crear", "editar"],
    "GROWTH_ENGINE": ["ver"],
    "TARJETAS_FIDELIDAD": ["ver"],
    "INTELIGENCIA_BI": [
        "ver", "ver_ventas", "ver_inventario", "ver_compras", "ver_caja",
        "ver_clientes", "ver_proveedores", "ver_finanzas", "ver_merma",
        "exportar", "configurar",
    ],
    "WHATSAPP": ["ver"],
    "DISEÑADOR_TICKETS": ["ver"],
    "CONFIG_HARDWARE": ["ver"],
    "CONFIG_MODULOS": ["ver"],
    "CONFIG_SEGURIDAD": ["ver", "editar"],
}


def normalize_permission(code: str) -> str:
    """Normalize permission codes so comparisons are case-insensitive."""
    return str(code or "").strip().upper()


def permission_code(module: str, action: str) -> str:
    """Build a canonical permission code using `MODULE.action` format."""
    return f"{str(module or '').strip().upper()}.{str(action or '').strip().lower()}"


def module_view_permission(module: str) -> str:
    """Return the canonical module visibility permission."""
    return permission_code(module, "ver")
