"""Repository interfaces for the RRHH bounded context.

The phase-1 contracts are intentionally close to existing tables so legacy UI
code can migrate one query at a time without behavior changes.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from core.rrhh.domain import (
    AttendanceRecord,
    Employee,
    LeaveRequest,
    PayrollPayment,
    ShiftAssignment,
    ShiftRole,
)


class EmployeeRepository(Protocol):
    def get_by_id(self, employee_id: int) -> Optional[Employee]: ...
    def list_active(self, limit: int = 500, search: str = "") -> List[Employee]: ...
    def list_for_lookup(self) -> List[Employee]: ...
    def create(self, data: Dict[str, Any]) -> int: ...
    def update(self, employee_id: int, data: Dict[str, Any]) -> None: ...
    def deactivate(self, employee_id: int) -> None: ...


class AttendanceRepository(Protocol):
    def list_between(self, date_from: str, date_to: str, employee_id: Optional[int] = None, limit: int = 300) -> List[AttendanceRecord]: ...
    def list_between_for_table(self, date_from: str, date_to: str, employee_id: Optional[int] = None, limit: int = 300) -> List[tuple]: ...
    def get_for_date(self, employee_id: int, fecha: str) -> Optional[AttendanceRecord]: ...
    def register_check_in(self, employee_id: int, fecha: str, hora: str, estado: str = "PRESENTE") -> int: ...
    def register_check_out(self, attendance_id: int, hora: str, horas_trabajadas: float) -> None: ...
    def upsert_manual(self, record: Dict[str, Any]) -> None: ...


class LeaveRepository(Protocol):
    def list_recent(self, limit: int = 200) -> List[LeaveRequest]: ...
    def list_recent_for_table(self, limit: int = 200) -> List[tuple]: ...
    def create(self, data: Dict[str, Any]) -> int: ...
    def update_status(self, leave_id: int, status: str) -> None: ...
    def find_overlaps(self, employee_id: int, date_from: str, date_to: str, exclude_id: Optional[int] = None) -> List[LeaveRequest]: ...


class PayrollRepository(Protocol):
    def create_payment(self, data: Dict[str, Any]) -> int: ...
    def get_payment(self, payment_id: int) -> Optional[PayrollPayment]: ...
    def get_latest_payment_for_employee(self, employee_id: int) -> Optional[PayrollPayment]: ...
    def sum_paid_between(self, date_from: str, date_to: str) -> float: ...


class ShiftRepository(Protocol):
    def list_roles(self, active_only: bool = True) -> List[ShiftRole]: ...
    def create_role(self, data: Dict[str, Any]) -> int: ...
    def update_role(self, role_id: int, data: Dict[str, Any]) -> None: ...
    def deactivate_role(self, role_id: int) -> None: ...
    def list_assignments(self, active_only: bool = True) -> List[ShiftAssignment]: ...
    def create_assignment(self, data: Dict[str, Any]) -> int: ...
    def update_assignment(self, assignment_id: int, data: Dict[str, Any]) -> None: ...
    def deactivate_assignment(self, assignment_id: int) -> None: ...
