"""Canonical enumerations for the finance bounded context."""

from __future__ import annotations

from enum import Enum


class AccountType(str, Enum):
    ASSET = "ASSET"
    LIABILITY = "LIABILITY"
    EQUITY = "EQUITY"
    REVENUE = "REVENUE"
    CONTRA_REVENUE = "CONTRA_REVENUE"
    COST_OF_SALES = "COST_OF_SALES"
    EXPENSE = "EXPENSE"
    OTHER_INCOME = "OTHER_INCOME"
    OTHER_EXPENSE = "OTHER_EXPENSE"


class NormalBalance(str, Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


#: Natural balance side for each account type.
NORMAL_BALANCE_BY_TYPE: dict[AccountType, NormalBalance] = {
    AccountType.ASSET: NormalBalance.DEBIT,
    AccountType.LIABILITY: NormalBalance.CREDIT,
    AccountType.EQUITY: NormalBalance.CREDIT,
    AccountType.REVENUE: NormalBalance.CREDIT,
    AccountType.CONTRA_REVENUE: NormalBalance.DEBIT,
    AccountType.COST_OF_SALES: NormalBalance.DEBIT,
    AccountType.EXPENSE: NormalBalance.DEBIT,
    AccountType.OTHER_INCOME: NormalBalance.CREDIT,
    AccountType.OTHER_EXPENSE: NormalBalance.DEBIT,
}


class JournalType(str, Enum):
    SALES = "SALES"
    PURCHASES = "PURCHASES"
    CASH = "CASH"
    BANK = "BANK"
    PAYROLL = "PAYROLL"
    INVENTORY = "INVENTORY"
    LOYALTY = "LOYALTY"
    COMMERCIAL_INSTRUMENTS = "COMMERCIAL_INSTRUMENTS"
    FIXED_ASSETS = "FIXED_ASSETS"
    ADJUSTMENTS = "ADJUSTMENTS"
    GENERAL = "GENERAL"
    OPENING = "OPENING"
    CLOSING = "CLOSING"


class JournalEntryStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    POSTED = "POSTED"
    REVERSED = "REVERSED"
    CANCELLED = "CANCELLED"


class FiscalPeriodStatus(str, Enum):
    OPEN = "OPEN"
    SOFT_CLOSED = "SOFT_CLOSED"
    CLOSED = "CLOSED"


class FinancialDocumentType(str, Enum):
    SALES_INVOICE = "SALES_INVOICE"
    SALES_RETURN = "SALES_RETURN"
    CREDIT_NOTE = "CREDIT_NOTE"
    SUPPLIER_INVOICE = "SUPPLIER_INVOICE"
    SUPPLIER_CREDIT_NOTE = "SUPPLIER_CREDIT_NOTE"
    PAYROLL_RUN = "PAYROLL_RUN"
    EXPENSE_VOUCHER = "EXPENSE_VOUCHER"
    CAPITAL_CONTRIBUTION = "CAPITAL_CONTRIBUTION"
    ASSET_ACQUISITION = "ASSET_ACQUISITION"
    INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT"
    WASTE_REPORT = "WASTE_REPORT"
    CASH_SHIFT_CLOSE = "CASH_SHIFT_CLOSE"
    TREASURY_TRANSFER = "TREASURY_TRANSFER"
    LOYALTY_OBLIGATION = "LOYALTY_OBLIGATION"
    LOYALTY_REDEMPTION = "LOYALTY_REDEMPTION"
    COUPON_OBLIGATION = "COUPON_OBLIGATION"
    VOUCHER_OBLIGATION = "VOUCHER_OBLIGATION"
    GIFT_CARD_LIABILITY = "GIFT_CARD_LIABILITY"
    STORED_VALUE_ADJUSTMENT = "STORED_VALUE_ADJUSTMENT"
    PROMOTIONAL_DISCOUNT = "PROMOTIONAL_DISCOUNT"
    COMMERCIAL_INSTRUMENT_EXPIRATION = "COMMERCIAL_INSTRUMENT_EXPIRATION"


class FinancialDocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    PARTIALLY_SETTLED = "PARTIALLY_SETTLED"
    SETTLED = "SETTLED"
    CANCELLED = "CANCELLED"


class ReceivableStatus(str, Enum):
    OPEN = "OPEN"
    PARTIALLY_COLLECTED = "PARTIALLY_COLLECTED"
    SETTLED = "SETTLED"
    WRITTEN_OFF = "WRITTEN_OFF"
    CANCELLED = "CANCELLED"


class PayableStatus(str, Enum):
    OPEN = "OPEN"
    SCHEDULED = "SCHEDULED"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    SETTLED = "SETTLED"
    CANCELLED = "CANCELLED"


class SupplierPaymentStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    AUTHORIZED = "AUTHORIZED"
    EXECUTED = "EXECUTED"
    RECONCILED = "RECONCILED"
    CANCELLED = "CANCELLED"


class TreasuryAccountType(str, Enum):
    BANK = "BANK"
    CASH_REGISTER = "CASH_REGISTER"
    PETTY_CASH = "PETTY_CASH"
    GENERAL_CASH = "GENERAL_CASH"
    PAYMENT_PROCESSOR = "PAYMENT_PROCESSOR"
    DIGITAL_WALLET = "DIGITAL_WALLET"
    CLEARING_ACCOUNT = "CLEARING_ACCOUNT"


class ReconciliationStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REVERTED = "REVERTED"


class BudgetStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"


class FixedAssetStatus(str, Enum):
    DRAFT = "DRAFT"
    CAPITALIZED = "CAPITALIZED"
    FULLY_DEPRECIATED = "FULLY_DEPRECIATED"
    DISPOSED = "DISPOSED"


class DepreciationMethod(str, Enum):
    STRAIGHT_LINE = "STRAIGHT_LINE"


class CommercialInstrumentType(str, Enum):
    LOYALTY_POINTS = "LOYALTY_POINTS"
    PROMOTIONAL_COUPON = "PROMOTIONAL_COUPON"
    DISCOUNT_COUPON = "DISCOUNT_COUPON"
    REFUND_VOUCHER = "REFUND_VOUCHER"
    STORE_CREDIT = "STORE_CREDIT"
    GIFT_CARD = "GIFT_CARD"
    PREPAID_VOUCHER = "PREPAID_VOUCHER"
    PROMOTIONAL_BALANCE = "PROMOTIONAL_BALANCE"
    CUSTOMER_WALLET = "CUSTOMER_WALLET"
    THIRD_PARTY_VOUCHER = "THIRD_PARTY_VOUCHER"


class CommercialObligationStatus(str, Enum):
    PENDING_RECOGNITION = "PENDING_RECOGNITION"
    OPEN = "OPEN"
    PARTIALLY_REDEEMED = "PARTIALLY_REDEEMED"
    REDEEMED = "REDEEMED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    REVERSED = "REVERSED"


class RecognitionBasis(str, Enum):
    """How the economic effect of a commercial instrument is recognized."""

    LIABILITY = "LIABILITY"                # real obligation with the customer
    CONTRA_REVENUE = "CONTRA_REVENUE"      # price reduction at redemption
    PROMOTIONAL_EXPENSE = "PROMOTIONAL_EXPENSE"
    THIRD_PARTY_RECEIVABLE = "THIRD_PARTY_RECEIVABLE"  # funded by a supplier/third party
    NO_INITIAL_RECOGNITION = "NO_INITIAL_RECOGNITION"  # recognized only at redemption


class PostingPurpose(str, Enum):
    """Idempotency discriminator: one purpose per economic effect of a source document."""

    SALE_REVENUE = "SALE_REVENUE"
    SALE_COGS = "SALE_COGS"
    SALE_REVERSAL = "SALE_REVERSAL"
    PURCHASE_RECEIPT = "PURCHASE_RECEIPT"
    SUPPLIER_INVOICE = "SUPPLIER_INVOICE"
    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"
    COLLECTION = "COLLECTION"
    PAYROLL = "PAYROLL"
    INVENTORY_ADJUSTMENT = "INVENTORY_ADJUSTMENT"
    WASTE = "WASTE"
    PRODUCTION = "PRODUCTION"
    CASH_SHIFT_CLOSE = "CASH_SHIFT_CLOSE"
    CASH_DIFFERENCE = "CASH_DIFFERENCE"
    TREASURY_TRANSFER = "TREASURY_TRANSFER"
    CAPITAL_CONTRIBUTION = "CAPITAL_CONTRIBUTION"
    ASSET_CAPITALIZATION = "ASSET_CAPITALIZATION"
    DEPRECIATION = "DEPRECIATION"
    ASSET_DISPOSAL = "ASSET_DISPOSAL"
    INSTRUMENT_RECOGNITION = "INSTRUMENT_RECOGNITION"
    INSTRUMENT_REDEMPTION = "INSTRUMENT_REDEMPTION"
    INSTRUMENT_EXPIRATION = "INSTRUMENT_EXPIRATION"
    INSTRUMENT_REVERSAL = "INSTRUMENT_REVERSAL"
    PERIOD_CLOSING = "PERIOD_CLOSING"
    OPENING_BALANCE = "OPENING_BALANCE"
    MANUAL = "MANUAL"


class SettlementType(str, Enum):
    """Means of settlement presented in a sale event payload."""

    CASH = "CASH"
    CARD = "CARD"
    BANK_TRANSFER = "BANK_TRANSFER"
    PAYMENT_PROCESSOR = "PAYMENT_PROCESSOR"
    ON_CREDIT = "ON_CREDIT"
    LOYALTY_POINTS = "LOYALTY_POINTS"
    COUPON = "COUPON"
    VOUCHER = "VOUCHER"
    GIFT_CARD = "GIFT_CARD"
    STORE_CREDIT = "STORE_CREDIT"
    PROMOTIONAL_BALANCE = "PROMOTIONAL_BALANCE"


class CashFlowCategory(str, Enum):
    OPERATING = "OPERATING"
    INVESTING = "INVESTING"
    FINANCING = "FINANCING"
    NONE = "NONE"
