"""Repository ports for the finance bounded context.

Protocols only — implementations live in
``backend/infrastructure/db/repositories/finance/``. Every id is a UUIDv7
string; every amount crossing a port is a ``Money`` value object.
"""

from __future__ import annotations

from datetime import date
from typing import Protocol

from backend.domain.finance.entities.account import Account
from backend.domain.finance.entities.bank_statement import BankStatement
from backend.domain.finance.entities.budget import Budget
from backend.domain.finance.entities.commercial_obligation import CommercialObligation
from backend.domain.finance.entities.financial_document import FinancialDocument
from backend.domain.finance.entities.fiscal_period import FiscalPeriod
from backend.domain.finance.entities.fixed_asset import FixedAsset
from backend.domain.finance.entities.journal import Journal
from backend.domain.finance.entities.journal_entry import JournalEntry
from backend.domain.finance.entities.payable import Payable, SupplierPayment
from backend.domain.finance.entities.posting_profile import PostingProfile
from backend.domain.finance.entities.receivable import Collection, Receivable
from backend.domain.finance.entities.reconciliation import Reconciliation
from backend.domain.finance.entities.treasury_account import TreasuryAccount
from backend.domain.finance.enums import (
    CommercialInstrumentType,
    JournalType,
    PostingPurpose,
)


class AccountRepositoryPort(Protocol):
    def save(self, account: Account) -> None: ...
    def get(self, account_id: str) -> Account | None: ...
    def get_by_code(self, code: str) -> Account | None: ...
    def list_active(self) -> list[Account]: ...
    def list_all(self) -> list[Account]: ...


class JournalRepositoryPort(Protocol):
    def save(self, journal: Journal) -> None: ...
    def get(self, journal_id: str) -> Journal | None: ...
    def get_by_type(self, journal_type: JournalType) -> Journal | None: ...
    def list_all(self) -> list[Journal]: ...
    def next_entry_number(self, journal: Journal) -> str: ...


class JournalEntryRepositoryPort(Protocol):
    def save(self, entry: JournalEntry) -> None: ...
    def update_status(self, entry: JournalEntry) -> None: ...
    def get(self, entry_id: str) -> JournalEntry | None: ...
    def find_by_posting_reference(
        self, source_module: str, source_document_id: str, posting_purpose: PostingPurpose,
    ) -> JournalEntry | None: ...
    def find_by_operation_id(self, operation_id: str) -> JournalEntry | None: ...
    def exists_unbalanced(self) -> bool: ...


class FiscalPeriodRepositoryPort(Protocol):
    def save(self, period: FiscalPeriod) -> None: ...
    def update(self, period: FiscalPeriod) -> None: ...
    def get(self, period_id: str) -> FiscalPeriod | None: ...
    def find_for_date(self, value: date) -> FiscalPeriod | None: ...
    def find_by_code(self, year: int, month: int) -> FiscalPeriod | None: ...
    def list_all(self) -> list[FiscalPeriod]: ...


class FinancialDocumentRepositoryPort(Protocol):
    def save(self, document: FinancialDocument) -> None: ...
    def update(self, document: FinancialDocument) -> None: ...
    def get(self, document_id: str) -> FinancialDocument | None: ...
    def find_by_source(self, source_module: str, source_document_id: str) -> list[FinancialDocument]: ...
    def find_by_operation_id(self, operation_id: str) -> FinancialDocument | None: ...


class ReceivableRepositoryPort(Protocol):
    def save(self, receivable: Receivable) -> None: ...
    def update(self, receivable: Receivable) -> None: ...
    def get(self, receivable_id: str) -> Receivable | None: ...
    def find_by_document(self, financial_document_id: str) -> Receivable | None: ...
    def find_by_operation_id(self, operation_id: str) -> Receivable | None: ...
    def list_open_by_customer(self, customer_id: str) -> list[Receivable]: ...
    def list_open(self) -> list[Receivable]: ...


class CollectionRepositoryPort(Protocol):
    def save(self, collection: Collection) -> None: ...
    def get(self, collection_id: str) -> Collection | None: ...
    def find_by_operation_id(self, operation_id: str) -> Collection | None: ...
    def list_by_receivable(self, receivable_id: str) -> list[Collection]: ...


class PayableRepositoryPort(Protocol):
    def save(self, payable: Payable) -> None: ...
    def update(self, payable: Payable) -> None: ...
    def get(self, payable_id: str) -> Payable | None: ...
    def find_by_operation_id(self, operation_id: str) -> Payable | None: ...
    def list_open_by_supplier(self, supplier_id: str) -> list[Payable]: ...
    def list_open(self) -> list[Payable]: ...


class SupplierPaymentRepositoryPort(Protocol):
    def save(self, payment: SupplierPayment) -> None: ...
    def update(self, payment: SupplierPayment) -> None: ...
    def get(self, payment_id: str) -> SupplierPayment | None: ...
    def find_by_operation_id(self, operation_id: str) -> SupplierPayment | None: ...
    def list_by_payable(self, payable_id: str) -> list[SupplierPayment]: ...
    def list_pending_authorization(self) -> list[SupplierPayment]: ...


class TreasuryRepositoryPort(Protocol):
    def save(self, account: TreasuryAccount) -> None: ...
    def update(self, account: TreasuryAccount) -> None: ...
    def get(self, treasury_account_id: str) -> TreasuryAccount | None: ...
    def list_active(self) -> list[TreasuryAccount]: ...
    def save_statement(self, statement: BankStatement) -> None: ...
    def get_statement(self, statement_id: str) -> BankStatement | None: ...
    def find_statement_by_operation_id(self, operation_id: str) -> BankStatement | None: ...


class ReconciliationRepositoryPort(Protocol):
    def save(self, reconciliation: Reconciliation) -> None: ...
    def update(self, reconciliation: Reconciliation) -> None: ...
    def get(self, reconciliation_id: str) -> Reconciliation | None: ...
    def find_by_operation_id(self, operation_id: str) -> Reconciliation | None: ...
    def list_open(self) -> list[Reconciliation]: ...


class BudgetRepositoryPort(Protocol):
    def save(self, budget: Budget) -> None: ...
    def update(self, budget: Budget) -> None: ...
    def get(self, budget_id: str) -> Budget | None: ...
    def find_by_operation_id(self, operation_id: str) -> Budget | None: ...
    def find_approved_for_year(self, fiscal_year: int, branch_id: str | None = None) -> Budget | None: ...
    def list_all(self) -> list[Budget]: ...


class FixedAssetRepositoryPort(Protocol):
    def save(self, asset: FixedAsset) -> None: ...
    def update(self, asset: FixedAsset) -> None: ...
    def get(self, asset_id: str) -> FixedAsset | None: ...
    def find_by_operation_id(self, operation_id: str) -> FixedAsset | None: ...
    def list_capitalized(self) -> list[FixedAsset]: ...
    def list_all(self) -> list[FixedAsset]: ...


class PostingProfileRepositoryPort(Protocol):
    def save(self, profile: PostingProfile) -> None: ...
    def update(self, profile: PostingProfile) -> None: ...
    def get(self, profile_id: str) -> PostingProfile | None: ...
    def find_effective(
        self,
        profile_key: str,
        on_date: date,
        *,
        instrument_type: CommercialInstrumentType | None = None,
        program_id: str | None = None,
        campaign_id: str | None = None,
        branch_id: str | None = None,
        currency_code: str | None = None,
        funding_party: str | None = None,
    ) -> PostingProfile | None: ...
    def list_all(self) -> list[PostingProfile]: ...


class CommercialObligationRepositoryPort(Protocol):
    def save(self, obligation: CommercialObligation) -> None: ...
    def update(self, obligation: CommercialObligation) -> None: ...
    def get(self, obligation_id: str) -> CommercialObligation | None: ...
    def find_by_instrument(
        self, instrument_type: CommercialInstrumentType, source_instrument_id: str,
    ) -> CommercialObligation | None: ...
    def find_by_operation_id(self, operation_id: str) -> CommercialObligation | None: ...
    def list_open(self, instrument_type: CommercialInstrumentType | None = None) -> list[CommercialObligation]: ...


class ProcessedEventRepositoryPort(Protocol):
    """Idempotency registry for consumed operational events."""

    def was_processed(self, event_id: str) -> bool: ...
    def mark_processed(self, event_id: str, event_name: str, operation_id: str) -> None: ...


class OutboxRepositoryPort(Protocol):
    """Transactional outbox for events Finance publishes."""

    def enqueue(self, event_id: str, event_name: str, payload_json: str, operation_id: str) -> None: ...
    def list_pending(self, limit: int = 100) -> list[dict]: ...
    def mark_dispatched(self, outbox_id: str) -> None: ...
