"""Canonical enums for Meat Processing (§7, §13, §17, §20, §21, §22, §26, §28)."""

from enum import Enum


class ProcessType(str, Enum):
    CUTTING = "CUTTING"
    DISASSEMBLY = "DISASSEMBLY"
    DEBONING = "DEBONING"
    TRIMMING = "TRIMMING"
    PORTIONING = "PORTIONING"
    GRINDING = "GRINDING"
    MIXING = "MIXING"
    MARINATION = "MARINATION"
    FORMULATION = "FORMULATION"
    PACKAGING = "PACKAGING"
    REPACKAGING = "REPACKAGING"
    LABELING = "LABELING"
    FREEZING = "FREEZING"
    THAWING = "THAWING"
    CHILLING = "CHILLING"
    COOKING_FUTURE = "COOKING_FUTURE"
    SMOKING_FUTURE = "SMOKING_FUTURE"
    CURING_FUTURE = "CURING_FUTURE"
    SAUSAGE_PRODUCTION_FUTURE = "SAUSAGE_PRODUCTION_FUTURE"
    DRYING_FUTURE = "DRYING_FUTURE"
    SLAUGHTER_FUTURE = "SLAUGHTER_FUTURE"
    BLEEDING_FUTURE = "BLEEDING_FUTURE"
    SCALDING_FUTURE = "SCALDING_FUTURE"
    DEFEATHERING_FUTURE = "DEFEATHERING_FUTURE"
    EVISCERATION_FUTURE = "EVISCERATION_FUTURE"
    CARCASS_CLASSIFICATION_FUTURE = "CARCASS_CLASSIFICATION_FUTURE"
    POST_MORTEM_PROCESSING_FUTURE = "POST_MORTEM_PROCESSING_FUTURE"


class ProcessingOrderStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    MATERIALS_PENDING = "MATERIALS_PENDING"
    READY = "READY"
    RELEASED = "RELEASED"
    IN_PROGRESS = "IN_PROGRESS"
    PAUSED = "PAUSED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    PENDING_QUALITY = "PENDING_QUALITY"
    PENDING_RECONCILIATION = "PENDING_RECONCILIATION"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    REVERSED = "REVERSED"


class ProcessingBatchStatus(str, Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ExecutionStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class ConsumptionStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_POSTING = "PENDING_POSTING"
    POSTED = "POSTED"
    REVERSED = "REVERSED"


class WeighingType(str, Enum):
    INPUT = "INPUT"
    INTERMEDIATE = "INTERMEDIATE"
    OUTPUT = "OUTPUT"
    CO_PRODUCT = "CO_PRODUCT"
    BY_PRODUCT = "BY_PRODUCT"
    WASTE = "WASTE"
    REWORK = "REWORK"
    CARCASS_FUTURE = "CARCASS_FUTURE"


class OutputType(str, Enum):
    MAIN_PRODUCT = "MAIN_PRODUCT"
    CO_PRODUCT = "CO_PRODUCT"
    BY_PRODUCT = "BY_PRODUCT"
    SEMI_FINISHED = "SEMI_FINISHED"
    WORK_IN_PROGRESS = "WORK_IN_PROGRESS"
    REWORKABLE = "REWORKABLE"
    WASTE = "WASTE"
    LOSS = "LOSS"


class OutputQualityStatus(str, Enum):
    PENDING_INSPECTION = "PENDING_INSPECTION"
    QUARANTINED = "QUARANTINED"
    RELEASED = "RELEASED"
    REJECTED = "REJECTED"
    REWORK_REQUIRED = "REWORK_REQUIRED"
    CONDEMNED = "CONDEMNED"


class YieldStatus(str, Enum):
    WITHIN_TOLERANCE = "WITHIN_TOLERANCE"
    WARNING = "WARNING"
    OUT_OF_TOLERANCE = "OUT_OF_TOLERANCE"
    CRITICAL = "CRITICAL"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"


class PlanSourceType(str, Enum):
    """§11 — where a ProductionPlanLine's demand came from."""
    MANUAL = "MANUAL"
    FORECAST = "FORECAST"
    CUSTOMER_ORDER = "CUSTOMER_ORDER"
    MINIMUM_STOCK = "MINIMUM_STOCK"
    REPLENISHMENT = "REPLENISHMENT"
    SALES_PLAN = "SALES_PLAN"
    REWORK = "REWORK"
    INTERNAL_REQUIREMENT = "INTERNAL_REQUIREMENT"


class ProductionPlanStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    PARTIALLY_CONVERTED = "PARTIALLY_CONVERTED"
    CONVERTED = "CONVERTED"
    CANCELLED = "CANCELLED"


class MaterialRequirementStatus(str, Enum):
    """§16 — requerido / reservado / asignado / consumido / cancelado."""
    REQUIRED = "REQUIRED"
    RESERVED = "RESERVED"
    ALLOCATED = "ALLOCATED"
    CONSUMED = "CONSUMED"
    CANCELLED = "CANCELLED"


class OperatorRole(str, Enum):
    """§32 — roles operativos asignables a una orden."""
    SUPERVISOR = "SUPERVISOR"
    OPERATOR = "OPERATOR"
    WEIGHER = "WEIGHER"
    CUTTER = "CUTTER"
    PACKER = "PACKER"
    QUALITY_OBSERVER = "QUALITY_OBSERVER"
    LINE_LEADER = "LINE_LEADER"


class IncidentType(str, Enum):
    """§30 — tipos de incidencia operativa."""
    EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE"
    MATERIAL_SHORTAGE = "MATERIAL_SHORTAGE"
    QUALITY_ISSUE = "QUALITY_ISSUE"
    TEMPERATURE_DEVIATION = "TEMPERATURE_DEVIATION"
    WEIGHT_VARIANCE = "WEIGHT_VARIANCE"
    OPERATOR_ERROR = "OPERATOR_ERROR"
    RECIPE_ERROR = "RECIPE_ERROR"
    PACKAGING_FAILURE = "PACKAGING_FAILURE"
    POWER_FAILURE = "POWER_FAILURE"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    SAFETY_EVENT = "SAFETY_EVENT"
    OTHER = "OTHER"


class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ReworkOrigin(str, Enum):
    """§29 — de dónde surge la necesidad de reprocesar."""
    QUALITY_DECISION = "QUALITY_DECISION"
    PROCESSING_INCIDENT = "PROCESSING_INCIDENT"
    OUTPUT_VARIANCE = "OUTPUT_VARIANCE"
    PACKAGING_FAILURE = "PACKAGING_FAILURE"
    CUSTOMER_RETURN_AUTHORIZED = "CUSTOMER_RETURN_AUTHORIZED"


class ReworkOrderStatus(str, Enum):
    """§29 — Producto bloqueado → Crear → Aprobar → Ejecutar → Completar → Cerrar."""
    CREATED = "CREATED"
    APPROVED = "APPROVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class EquipmentStatus(str, Enum):
    """§19/§33 — condición física del equipo, independiente de si está
    asignado a una orden ahora mismo (eso lo rastrea EquipmentAssignment)."""
    AVAILABLE = "AVAILABLE"
    MAINTENANCE = "MAINTENANCE"
    RETIRED = "RETIRED"