"""Granular Cash Register permission codes.

Caja uses the same canonical ``MODULO.accion`` vocabulary as Compras,
Inventario and ``core.security.permission_catalog``. These values are stored
directly in ``rol_permisos`` and checked through ``SessionContext.tiene_permiso``;
there is no legacy translation layer.
"""

from __future__ import annotations


class CashPermissions:
    ACCESS = "CAJA.ver"
    VIEW_OWN_BRANCH = "CAJA.ver.sucursal_propia"
    VIEW_ASSIGNED_BRANCHES = "CAJA.ver.sucursales_asignadas"
    VIEW_ALL_BRANCHES = "CAJA.ver.todas_sucursales"
    VIEW_SENSITIVE_AMOUNTS = "CAJA.ver.importes_sensibles"
    AUDIT_VIEW = "CAJA.ver.auditoria"
    EXPORT = "CAJA.exportar"
    REGISTER_VIEW = "CAJA.caja.ver"
    REGISTER_CREATE = "CAJA.caja.crear"
    REGISTER_EDIT = "CAJA.caja.editar"
    REGISTER_MANAGE = "CAJA.caja.editar"
    REGISTER_ACTIVATE = "CAJA.caja.activar"
    REGISTER_BLOCK = "CAJA.caja.bloquear"
    REGISTER_RETIRE = "CAJA.caja.retirar"
    DRAWER_VIEW = "CAJA.cajon.ver"
    DRAWER_MANAGE = "CAJA.cajon.gestionar"
    DRAWER_OPEN = "CAJA.cajon.abrir"
    DRAWER_OPEN_WITHOUT_SALE = "CAJA.cajon.abrir_sin_venta"
    TERMINAL_VIEW = "CAJA.terminal.ver"
    TERMINAL_MANAGE = "CAJA.terminal.gestionar"
    TERMINAL_OPERATE = "CAJA.terminal.operar"
    SHIFT_VIEW = "CAJA.turno.ver"
    SHIFT_OPEN = "CAJA.turno.abrir"
    SHIFT_SUSPEND = "CAJA.turno.suspender"
    SHIFT_RESUME = "CAJA.turno.reanudar"
    SHIFT_PREPARE_CLOSE = "CAJA.turno.pre_cerrar"
    SHIFT_CLOSE = "CAJA.turno.cerrar"
    SHIFT_FORCE_CLOSE = "CAJA.turno.forzar_cierre"
    SHIFT_REASSIGN = "CAJA.turno.reasignar"
    MOVEMENT_VIEW = "CAJA.movimiento.ver"
    MOVEMENT_INCOME = "CAJA.movimiento.ingreso"
    MOVEMENT_WITHDRAWAL = "CAJA.movimiento.retiro"
    MOVEMENT_SAFE_DROP = "CAJA.movimiento.safe_drop"
    MOVEMENT_REVERSE = "CAJA.movimiento.reversar"
    MOVEMENT_AUTHORIZE_OVER_LIMIT = "CAJA.movimiento.autorizar_exceso"
    BLIND_COUNT_VIEW = "CAJA.conteo.ver"
    BLIND_COUNT_START = "CAJA.conteo.iniciar"
    BLIND_COUNT_CAPTURE = "CAJA.conteo.capturar"
    BLIND_COUNT_CONFIRM = "CAJA.conteo.confirmar"
    BLIND_COUNT_REVEAL_EXPECTED = "CAJA.conteo.ver_esperado"
    BLIND_COUNT_CANCEL = "CAJA.conteo.cancelar"
    BLIND_COUNT_OVERRIDE = "CAJA.conteo.sobrescribir"
    X_CUT_VIEW = "CAJA.corte_x.ver"
    X_CUT_GENERATE = "CAJA.corte_x.generar"
    X_CUT_PRINT = "CAJA.corte_x.imprimir"
    X_CUT_REPRINT = "CAJA.corte_x.reimprimir"
    Z_CUT_VIEW = "CAJA.corte_z.ver"
    Z_CUT_GENERATE = "CAJA.corte_z.generar"
    Z_CUT_REVIEW = "CAJA.corte_z.revisar"
    Z_CUT_PRINT = "CAJA.corte_z.imprimir"
    Z_CUT_REPRINT = "CAJA.corte_z.reimprimir"
    DIFFERENCE_VIEW = "CAJA.diferencia.ver"
    DIFFERENCE_EXPLAIN = "CAJA.diferencia.explicar"
    DIFFERENCE_REVIEW = "CAJA.diferencia.revisar"
    DIFFERENCE_RESOLVE = "CAJA.diferencia.resolver"
    DIFFERENCE_WRITE_OFF = "CAJA.diferencia.castigar"
    SAFE_DROP_VIEW = "CAJA.retiro_seguridad.ver"
    SAFE_DROP_CREATE = "CAJA.retiro_seguridad.crear"
    SAFE_DROP_AUTHORIZE = "CAJA.retiro_seguridad.autorizar"
    HANDOVER_VIEW = "CAJA.entrega.ver"
    HANDOVER_PREPARE = "CAJA.entrega.preparar"
    HANDOVER_DELIVER = "CAJA.entrega.entregar"
    HANDOVER_RECEIVE = "CAJA.entrega.recibir"
    HANDOVER_DISPUTE = "CAJA.entrega.disputar"
    HANDOVER_CANCEL = "CAJA.entrega.cancelar"
    DEPOSIT_VIEW = "CAJA.deposito.ver"
    DEPOSIT_PREPARE = "CAJA.deposito.preparar"
    DEPOSIT_CANCEL = "CAJA.deposito.cancelar"
    PAYMENT_VIEW = "CAJA.pago.ver"
    PAYMENT_REGISTER = "CAJA.pago.registrar"
    PAYMENT_REVERSE = "CAJA.pago.reversar"
    PAYMENT_METHOD_VIEW = "CAJA.medio_pago.ver"
    PAYMENT_METHOD_MANAGE = "CAJA.medio_pago.gestionar"
    PAYMENT_TERMINAL_VIEW = "CAJA.terminal_pago.ver"
    PAYMENT_TERMINAL_MANAGE = "CAJA.terminal_pago.gestionar"
    PAYMENT_TERMINAL_RECONCILE_OPERATION = "CAJA.terminal_pago.conciliar_operacion"
    REFUND_VIEW = "CAJA.reembolso.ver"
    REFUND_REQUEST = "CAJA.reembolso.solicitar"
    REFUND_EXECUTE = "CAJA.reembolso.ejecutar"
    REFUND_AUTHORIZE = "CAJA.reembolso.autorizar"
    REFUND_OVERRIDE = "CAJA.reembolso.sobrescribir"
    DRAWER_EVENT_VIEW = "CAJA.evento_cajon.ver"
    HARDWARE_VIEW = "CAJA.hardware.ver"
    HARDWARE_DIAGNOSE = "CAJA.hardware.diagnosticar"
    HARDWARE_MANAGE = "CAJA.hardware.gestionar"
    PRINT = "CAJA.imprimir"
    REPRINT = "CAJA.reimprimir"
    SETTINGS_VIEW = "CAJA.configuracion.ver"
    SETTINGS_MANAGE = "CAJA.configuracion.editar"
    NOTIFICATIONS_VIEW = "CAJA.notificacion.ver"
    NOTIFICATIONS_MANAGE = "CAJA.notificacion.gestionar"
    WHATSAPP_MANAGE = "CAJA.whatsapp.gestionar"
    SYNC_VIEW = "CAJA.sync.ver"
    SYNC_MANAGE = "CAJA.sync.gestionar"


ALL_CASH_PERMISSIONS = frozenset(
    value for name, value in vars(CashPermissions).items()
    if name.isupper() and isinstance(value, str)
)
