"""Single permission-to-capability map for Caja UI."""

from __future__ import annotations

from collections.abc import Callable

from backend.application.cash_register.permissions import CashPermissions
from frontend.desktop.modules.cash_register.view_models import CashCapabilities


def resolve_cash_capabilities(can: Callable[[str], bool]) -> CashCapabilities:
    P = CashPermissions
    return CashCapabilities(
        module_view=can(P.ACCESS),
        register_view=can(P.REGISTER_VIEW),
        register_create=can(P.REGISTER_CREATE),
        register_edit=can(P.REGISTER_EDIT),
        register_activate=can(P.REGISTER_ACTIVATE),
        register_block=can(P.REGISTER_BLOCK),
        drawer_view=can(P.DRAWER_VIEW),
        drawer_manage=can(P.DRAWER_MANAGE),
        drawer_open=can(P.DRAWER_OPEN),
        drawer_open_without_sale=can(P.DRAWER_OPEN_WITHOUT_SALE),
        terminal_view=can(P.TERMINAL_VIEW),
        terminal_manage=can(P.TERMINAL_MANAGE),
        terminal_operate=can(P.TERMINAL_OPERATE),
        shift_view=can(P.SHIFT_VIEW),
        shift_open=can(P.SHIFT_OPEN),
        shift_suspend=can(P.SHIFT_SUSPEND),
        shift_resume=can(P.SHIFT_RESUME),
        shift_prepare_close=can(P.SHIFT_PREPARE_CLOSE),
        shift_close=can(P.SHIFT_CLOSE),
        shift_force_close=can(P.SHIFT_FORCE_CLOSE),
        shift_reassign=can(P.SHIFT_REASSIGN),
        movement_view=can(P.MOVEMENT_VIEW),
        movement_income=can(P.MOVEMENT_INCOME),
        movement_withdrawal=can(P.MOVEMENT_WITHDRAWAL),
        safe_drop_create=can(P.MOVEMENT_SAFE_DROP),
        movement_reverse=can(P.MOVEMENT_REVERSE),
        movement_authorize_over_limit=can(P.MOVEMENT_AUTHORIZE_OVER_LIMIT),
        count_view=can(P.BLIND_COUNT_VIEW),
        count_start=can(P.BLIND_COUNT_START),
        count_capture=can(P.BLIND_COUNT_CAPTURE),
        count_confirm=can(P.BLIND_COUNT_CONFIRM),
        count_reveal_expected=can(P.BLIND_COUNT_REVEAL_EXPECTED),
        count_cancel=can(P.BLIND_COUNT_CANCEL),
        count_override=can(P.BLIND_COUNT_OVERRIDE),
        x_cut_view=can(P.X_CUT_VIEW),
        x_cut_generate=can(P.X_CUT_GENERATE),
        x_cut_print=can(P.X_CUT_PRINT),
        x_cut_reprint=can(P.X_CUT_REPRINT),
        z_cut_view=can(P.Z_CUT_VIEW),
        z_cut_generate=can(P.Z_CUT_GENERATE),
        z_cut_review=can(P.Z_CUT_REVIEW),
        z_cut_print=can(P.Z_CUT_PRINT),
        z_cut_reprint=can(P.Z_CUT_REPRINT),
        difference_view=can(P.DIFFERENCE_VIEW),
        difference_explain=can(P.DIFFERENCE_EXPLAIN),
        difference_review=can(P.DIFFERENCE_REVIEW),
        difference_resolve=can(P.DIFFERENCE_RESOLVE),
        handover_view=can(P.HANDOVER_VIEW),
        handover_prepare=can(P.HANDOVER_PREPARE),
        handover_deliver=can(P.HANDOVER_DELIVER),
        handover_receive=can(P.HANDOVER_RECEIVE),
        handover_dispute=can(P.HANDOVER_DISPUTE),
        deposit_view=can(P.DEPOSIT_VIEW),
        deposit_prepare=can(P.DEPOSIT_PREPARE),
        payment_view=can(P.PAYMENT_VIEW),
        payment_method_view=can(P.PAYMENT_METHOD_VIEW),
        payment_method_manage=can(P.PAYMENT_METHOD_MANAGE),
        payment_terminal_view=can(P.PAYMENT_TERMINAL_VIEW),
        payment_terminal_manage=can(P.PAYMENT_TERMINAL_MANAGE),
        refund_view=can(P.REFUND_VIEW),
        refund_request=can(P.REFUND_REQUEST),
        refund_execute=can(P.REFUND_EXECUTE),
        refund_authorize=can(P.REFUND_AUTHORIZE),
        drawer_event_view=can(P.DRAWER_EVENT_VIEW),
        hardware_view=can(P.HARDWARE_VIEW),
        hardware_diagnose=can(P.HARDWARE_DIAGNOSE),
        hardware_manage=can(P.HARDWARE_MANAGE),
        notification_view=can(P.NOTIFICATIONS_VIEW),
        notification_manage=can(P.NOTIFICATIONS_MANAGE),
        audit_view=can(P.AUDIT_VIEW),
        settings_view=can(P.SETTINGS_VIEW),
        settings_manage=can(P.SETTINGS_MANAGE),
        sync_view=can(P.SYNC_VIEW),
        sync_manage=can(P.SYNC_MANAGE),
    )
