"""Closed vocabularies for the transfers bounded context."""
from enum import Enum


class TransferStatus(str, Enum):
    DRAFT = "DRAFT"; PENDING_APPROVAL = "PENDING_APPROVAL"; APPROVED = "APPROVED"
    RESERVATION_PENDING = "RESERVATION_PENDING"; RESERVED = "RESERVED"; PICKING = "PICKING"
    PARTIALLY_PICKED = "PARTIALLY_PICKED"; PICKED = "PICKED"; READY_TO_DISPATCH = "READY_TO_DISPATCH"
    PARTIALLY_DISPATCHED = "PARTIALLY_DISPATCHED"; IN_TRANSIT = "IN_TRANSIT"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"; RECEIVED = "RECEIVED"
    WITH_DIFFERENCES = "WITH_DIFFERENCES"; PENDING_RESOLUTION = "PENDING_RESOLUTION"
    RETURN_IN_PROGRESS = "RETURN_IN_PROGRESS"; CLOSED = "CLOSED"; REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"; REVERSED = "REVERSED"


class TransferType(str, Enum):
    BRANCH_TO_BRANCH = "BRANCH_TO_BRANCH"; WAREHOUSE_TO_WAREHOUSE = "WAREHOUSE_TO_WAREHOUSE"
    LOCATION_TO_LOCATION = "LOCATION_TO_LOCATION"; CENTRAL_TO_BRANCH = "CENTRAL_TO_BRANCH"
    BRANCH_TO_CENTRAL = "BRANCH_TO_CENTRAL"; PLANT_TO_WAREHOUSE = "PLANT_TO_WAREHOUSE"
    WAREHOUSE_TO_PLANT = "WAREHOUSE_TO_PLANT"; STORE_TO_STORE = "STORE_TO_STORE"
    QUARANTINE_TRANSFER = "QUARANTINE_TRANSFER"; RETURN_TO_ORIGIN = "RETURN_TO_ORIGIN"
    REPLENISHMENT_TRANSFER = "REPLENISHMENT_TRANSFER"; CUSTOMER_ORDER_TRANSFER = "CUSTOMER_ORDER_TRANSFER"
    PRODUCTION_SUPPLY_TRANSFER = "PRODUCTION_SUPPLY_TRANSFER"; EMERGENCY_TRANSFER = "EMERGENCY_TRANSFER"
    CROSS_DOCK_FUTURE = "CROSS_DOCK_FUTURE"; CONSIGNMENT_FUTURE = "CONSIGNMENT_FUTURE"


class TransferNodeType(str, Enum):
    BRANCH = "BRANCH"; WAREHOUSE = "WAREHOUSE"; LOCATION = "LOCATION"; PLANT = "PLANT"
    CENTRAL_WAREHOUSE = "CENTRAL_WAREHOUSE"; QUARANTINE_AREA = "QUARANTINE_AREA"
    PRODUCTION_AREA = "PRODUCTION_AREA"; TRANSIT_NODE = "TRANSIT_NODE"
    EXTERNAL_CUSTODY_FUTURE = "EXTERNAL_CUSTODY_FUTURE"


class DifferenceType(str, Enum):
    SHORT_QUANTITY = "SHORT_QUANTITY"; OVER_QUANTITY = "OVER_QUANTITY"; WEIGHT_VARIANCE = "WEIGHT_VARIANCE"
    WRONG_PRODUCT = "WRONG_PRODUCT"; WRONG_LOT = "WRONG_LOT"; DAMAGED = "DAMAGED"
    TEMPERATURE_VARIANCE = "TEMPERATURE_VARIANCE"; EXPIRED = "EXPIRED"; QUALITY_FAILURE = "QUALITY_FAILURE"
    PACKAGE_MISSING = "PACKAGE_MISSING"; SEAL_BROKEN = "SEAL_BROKEN"; LOST_IN_TRANSIT = "LOST_IN_TRANSIT"
    DOCUMENT_MISMATCH = "DOCUMENT_MISMATCH"


class DifferenceStatus(str, Enum):
    DETECTED = "DETECTED"; PENDING_REVIEW = "PENDING_REVIEW"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"; ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"; CLAIMED = "CLAIMED"; RESOLVED = "RESOLVED"; CLOSED = "CLOSED"


class DifferenceResolutionType(str, Enum):
    ACCEPT_SHORTAGE = "ACCEPT_SHORTAGE"; ACCEPT_OVERAGE = "ACCEPT_OVERAGE"
    RETURN_TO_ORIGIN = "RETURN_TO_ORIGIN"; SEND_REPLACEMENT = "SEND_REPLACEMENT"
    QUALITY_QUARANTINE = "QUALITY_QUARANTINE"; CREATE_LOSS_CASE = "CREATE_LOSS_CASE"
    CREATE_CARRIER_CLAIM = "CREATE_CARRIER_CLAIM"; CREATE_SUPPLIER_CLAIM = "CREATE_SUPPLIER_CLAIM"
    ADJUST_DOCUMENT = "ADJUST_DOCUMENT"; RECOUNT = "RECOUNT"; REWEIGH = "REWEIGH"
    OTHER_AUTHORIZED = "OTHER_AUTHORIZED"


class ColdChainStatus(str, Enum):
    COMPLIANT = "COMPLIANT"; WARNING = "WARNING"; OUT_OF_RANGE = "OUT_OF_RANGE"
    PENDING_QUALITY = "PENDING_QUALITY"; BLOCKED = "BLOCKED"


class ReceiptQualityStatus(str, Enum):
    AVAILABLE = "AVAILABLE"; PENDING_INSPECTION = "PENDING_INSPECTION"
    QUARANTINED = "QUARANTINED"; QUALITY_BLOCKED = "QUALITY_BLOCKED"; REJECTED = "REJECTED"


class TransferReturnReason(str, Enum):
    DESTINATION_REJECTION = "DESTINATION_REJECTION"; QUALITY_REJECTION = "QUALITY_REJECTION"
    WRONG_PRODUCT = "WRONG_PRODUCT"; OVER_SHIPMENT = "OVER_SHIPMENT"; DAMAGED = "DAMAGED"
    TEMPERATURE_FAILURE = "TEMPERATURE_FAILURE"; BUSINESS_CANCELLATION = "BUSINESS_CANCELLATION"


class TransferReturnStatus(str, Enum):
    REQUESTED = "REQUESTED"; APPROVED = "APPROVED"; DISPATCHED = "DISPATCHED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"; COMPLETED = "COMPLETED"; REJECTED = "REJECTED"
