"""Ports keep workflow independent of SQLite and of Inventory internals."""
from decimal import Decimal
from typing import Protocol
from .entities.stock_transfer import (
    StockTransfer, TransferDifference, TransferDifferenceResolution, TransferReceipt,
)
from .entities.transfer_package import TransferPackage
from .entities.transfer_shipment import TransferCustodyEvent, TransferShipment
from .entities.blind_receipt_count import BlindReceiptCount
from .entities.transfer_return import TransferReturn, TransferReturnCustodyEvent
from .entities.transfer_suggestion import TransferSuggestion
from .policies.lot_allocation_policy import TransferLotAllocation


class StockTransferRepository(Protocol):
    def get(self, transfer_id: str) -> StockTransfer | None: ...
    def save(self, transfer: StockTransfer) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_operation(self, *, transfer_id: str, operation_id: str, operation_type: str) -> None: ...


class TransferPackageRepository(Protocol):
    def save(self, package: TransferPackage) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_operation(self, *, package_id: str, transfer_id: str, operation_id: str,
                         operation_type: str) -> None: ...


class TransferShipmentRepository(Protocol):
    def get(self, shipment_id: str) -> TransferShipment | None: ...
    def save(self, shipment: TransferShipment, custody_event: TransferCustodyEvent) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_operation(self, *, shipment_id: str, transfer_id: str, operation_id: str,
                         operation_type: str) -> None: ...


class TransferReceiptRepository(Protocol):
    def save(self, receipt: TransferReceipt,
             differences: tuple[TransferDifference, ...]) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def received_totals(self, shipment_id: str) -> dict[str, tuple[Decimal, Decimal]]: ...
    def record_operation(self, *, receipt_id: str, transfer_id: str, operation_id: str,
                         operation_type: str, device_id: str | None,
                         local_sequence: int | None, sync_status: str) -> None: ...


class BlindReceiptCountRepository(Protocol):
    def get(self, count_id: str) -> BlindReceiptCount | None: ...
    def save(self, count: BlindReceiptCount) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_operation(self, *, count_id: str, transfer_id: str, operation_id: str,
                         operation_type: str, actor_id: str) -> None: ...


class TransferDifferenceRepository(Protocol):
    def get(self, difference_id: str) -> TransferDifference | None: ...
    def belongs_to_transfer(self, difference_id: str, transfer_id: str) -> bool: ...
    def save_all(self, transfer_id: str, differences: tuple[TransferDifference, ...]) -> None: ...
    def save_resolution(self, difference: TransferDifference,
                        resolution: TransferDifferenceResolution) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_operation(self, *, difference_id: str, transfer_id: str,
                         operation_id: str, operation_type: str, actor_id: str) -> None: ...


class TransferReturnRepository(Protocol):
    def get(self, return_id: str) -> TransferReturn | None: ...
    def save(self, transfer_return: TransferReturn,
             custody_event: TransferReturnCustodyEvent | None = None) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_operation(self, *, return_id: str, transfer_id: str,
                         operation_id: str, operation_type: str, actor_id: str) -> None: ...


class TransferSuggestionRepository(Protocol):
    def save_all(self, suggestions: tuple[TransferSuggestion, ...]) -> None: ...
    def operation_exists(self, operation_id: str) -> bool: ...
    def record_generation(self, *, generation_id: str, operation_id: str, source_channel: str,
                          source_reference_id: str | None, actor_id: str) -> None: ...


class InventoryTransferGateway(Protocol):
    def reserve(self, *, transfer: StockTransfer, operation_id: str, actor_id: str,
                allocations: tuple[TransferLotAllocation, ...] = ()) -> None: ...
    def dispatch(self, *, transfer: StockTransfer, operation_id: str, actor_id: str) -> None: ...
    def receive(self, *, transfer: StockTransfer, receipt: TransferReceipt,
                operation_id: str, actor_id: str) -> None: ...
    def dispatch_return(self, *, transfer_return: TransferReturn,
                        operation_id: str, actor_id: str) -> None: ...
    def receive_return(self, *, transfer_return: TransferReturn,
                       operation_id: str, actor_id: str) -> None: ...
