"""Repository ports for the CRM (relationship) bounded context (§10).

Protocols only — implementations live in
``backend/infrastructure/db/repositories/crm/``. Every id is a UUIDv7
string. Mirrors backend/domain/customers/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.crm.entities.crm_activity import CRMActivity
from backend.domain.crm.entities.crm_note import CRMNote
from backend.domain.crm.entities.crm_reminder import CRMReminder
from backend.domain.crm.entities.crm_task import CRMTask
from backend.domain.crm.entities.customer_ownership import CustomerOwnership
from backend.domain.crm.entities.customer_portfolio import CustomerPortfolio
from backend.domain.crm.entities.customer_segment import CustomerSegment
from backend.domain.crm.entities.customer_segment_membership import CustomerSegmentMembership
from backend.domain.crm.entities.customer_tag import CustomerTag
from backend.domain.crm.entities.customer_tag_assignment import CustomerTagAssignment
from backend.domain.crm.entities.lead import Lead
from backend.domain.crm.entities.lead_qualification import LeadQualification
from backend.domain.crm.entities.opportunity import Opportunity
from backend.domain.crm.entities.opportunity_product_interest import OpportunityProductInterest
from backend.domain.crm.entities.opportunity_stage_history import OpportunityStageHistory
from backend.domain.crm.entities.portfolio_assignment import PortfolioAssignment
from backend.domain.crm.entities.sales_territory import SalesTerritory
from backend.domain.crm.entities.stage_definition import CRMStageDefinition
from backend.domain.crm.value_objects.lead_code import LeadCode
from backend.domain.crm.value_objects.opportunity_code import OpportunityCode


class LeadRepositoryPort(Protocol):
    def next_code(self) -> LeadCode: ...
    def save(self, lead: Lead, *, operation_id: str | None = None) -> None: ...
    def update(self, lead: Lead) -> None: ...
    def get(self, lead_id: str) -> Lead | None: ...
    def get_by_code(self, code: str) -> Lead | None: ...
    def get_by_operation_id(self, operation_id: str) -> Lead | None: ...
    def find_duplicate_rows(self) -> list[dict]: ...
    def list_owned_by(self, owner_user_ids: tuple[str, ...], *,
                       limit: int = 200, offset: int = 0) -> list[Lead]: ...


class LeadQualificationRepositoryPort(Protocol):
    def save(self, qualification: LeadQualification) -> None: ...
    def list_for_lead(self, lead_id: str) -> list[LeadQualification]: ...


class OpportunityRepositoryPort(Protocol):
    def next_code(self) -> OpportunityCode: ...
    def save(self, opportunity: Opportunity, *, operation_id: str | None = None) -> None: ...
    def update(self, opportunity: Opportunity) -> None: ...
    def get(self, opportunity_id: str) -> Opportunity | None: ...
    def get_by_code(self, code: str) -> Opportunity | None: ...
    def get_by_operation_id(self, operation_id: str) -> Opportunity | None: ...
    def list_owned_by(self, owner_user_ids: tuple[str, ...], *,
                       limit: int = 200, offset: int = 0) -> list[Opportunity]: ...
    def list_open_owned_by(self, owner_user_ids: tuple[str, ...], *,
                            limit: int = 500, offset: int = 0) -> list[Opportunity]: ...
    def list_for_customer(self, customer_id: str, *,
                          limit: int = 200, offset: int = 0) -> list[Opportunity]: ...


class CRMStageDefinitionRepositoryPort(Protocol):
    def save(self, stage: CRMStageDefinition) -> None: ...
    def get(self, stage_id: str) -> CRMStageDefinition | None: ...
    def get_by_code(self, code: str) -> CRMStageDefinition | None: ...
    def list_active_ordered(self) -> list[CRMStageDefinition]: ...
    def get_won_stage(self) -> CRMStageDefinition | None: ...
    def get_lost_stage(self) -> CRMStageDefinition | None: ...
    def get_default_initial_stage(self) -> CRMStageDefinition | None: ...


class OpportunityStageHistoryRepositoryPort(Protocol):
    def save(self, history: OpportunityStageHistory) -> None: ...
    def list_for_opportunity(self, opportunity_id: str) -> list[OpportunityStageHistory]: ...


class OpportunityProductInterestRepositoryPort(Protocol):
    def save(self, interest: OpportunityProductInterest) -> None: ...
    def list_for_opportunity(self, opportunity_id: str) -> list[OpportunityProductInterest]: ...


class CRMActivityRepositoryPort(Protocol):
    def save(self, activity: CRMActivity, *, operation_id: str | None = None) -> None: ...
    def update(self, activity: CRMActivity) -> None: ...
    def get(self, activity_id: str) -> CRMActivity | None: ...
    def get_by_operation_id(self, operation_id: str) -> CRMActivity | None: ...
    def list_for_related_entity(self, related_entity_type: str,
                                 related_entity_id: str) -> list[CRMActivity]: ...
    def list_assigned_to(self, user_id: str) -> list[CRMActivity]: ...


class CRMTaskRepositoryPort(Protocol):
    def save(self, task: CRMTask, *, operation_id: str | None = None) -> None: ...
    def update(self, task: CRMTask) -> None: ...
    def get(self, task_id: str) -> CRMTask | None: ...
    def get_by_operation_id(self, operation_id: str) -> CRMTask | None: ...
    def list_for_related_entity(self, related_entity_type: str,
                                 related_entity_id: str) -> list[CRMTask]: ...
    def list_assigned_to(self, user_id: str) -> list[CRMTask]: ...


class CRMNoteRepositoryPort(Protocol):
    def save(self, note: CRMNote) -> None: ...
    def update(self, note: CRMNote) -> None: ...
    def delete(self, note_id: str) -> None: ...
    def get(self, note_id: str) -> CRMNote | None: ...
    def list_for_related_entity(self, related_entity_type: str,
                                 related_entity_id: str) -> list[CRMNote]: ...


class CRMReminderRepositoryPort(Protocol):
    def save(self, reminder: CRMReminder) -> None: ...
    def list_for_task(self, task_id: str) -> list[CRMReminder]: ...
    def list_for_activity(self, activity_id: str) -> list[CRMReminder]: ...


class SalesTerritoryRepositoryPort(Protocol):
    def save(self, territory: SalesTerritory) -> None: ...
    def update(self, territory: SalesTerritory) -> None: ...
    def get(self, territory_id: str) -> SalesTerritory | None: ...
    def get_by_code(self, code: str) -> SalesTerritory | None: ...
    def list_active(self) -> list[SalesTerritory]: ...


class CustomerPortfolioRepositoryPort(Protocol):
    def save(self, portfolio: CustomerPortfolio) -> None: ...
    def update(self, portfolio: CustomerPortfolio) -> None: ...
    def get(self, portfolio_id: str) -> CustomerPortfolio | None: ...
    def get_by_code(self, code: str) -> CustomerPortfolio | None: ...
    def list_active(self) -> list[CustomerPortfolio]: ...


class CustomerOwnershipRepositoryPort(Protocol):
    def save(self, ownership: CustomerOwnership, *, operation_id: str | None = None) -> None: ...
    def get_latest(self, customer_id: str, ownership_type: str) -> CustomerOwnership | None: ...
    def list_for_customer(self, customer_id: str) -> list[CustomerOwnership]: ...


class PortfolioAssignmentRepositoryPort(Protocol):
    def save(self, assignment: PortfolioAssignment, *,
             operation_id: str | None = None) -> None: ...
    def get_latest(self, customer_id: str) -> PortfolioAssignment | None: ...
    def list_for_customer(self, customer_id: str) -> list[PortfolioAssignment]: ...
    def list_for_portfolio(self, portfolio_id: str) -> list[PortfolioAssignment]: ...


class CustomerSegmentRepositoryPort(Protocol):
    def save(self, segment: CustomerSegment) -> None: ...
    def update(self, segment: CustomerSegment) -> None: ...
    def get(self, segment_id: str) -> CustomerSegment | None: ...
    def get_by_code(self, code: str) -> CustomerSegment | None: ...
    def list_active(self) -> list[CustomerSegment]: ...


class CustomerSegmentMembershipRepositoryPort(Protocol):
    def save(self, membership: CustomerSegmentMembership, *,
             operation_id: str | None = None) -> None: ...
    def update(self, membership: CustomerSegmentMembership) -> None: ...
    def get(self, membership_id: str) -> CustomerSegmentMembership | None: ...
    def get_active(self, customer_id: str, segment_id: str) -> CustomerSegmentMembership | None: ...
    def list_active_for_customer(self, customer_id: str) -> list[CustomerSegmentMembership]: ...
    def list_for_segment(self, segment_id: str) -> list[CustomerSegmentMembership]: ...


class CustomerTagRepositoryPort(Protocol):
    def save(self, tag: CustomerTag) -> None: ...
    def update(self, tag: CustomerTag) -> None: ...
    def get(self, tag_id: str) -> CustomerTag | None: ...
    def get_by_code(self, code: str) -> CustomerTag | None: ...
    def list_active(self) -> list[CustomerTag]: ...


class CustomerTagAssignmentRepositoryPort(Protocol):
    def save(self, assignment: CustomerTagAssignment, *,
             operation_id: str | None = None) -> None: ...
    def update(self, assignment: CustomerTagAssignment) -> None: ...
    def get(self, assignment_id: str) -> CustomerTagAssignment | None: ...
    def get_active(self, customer_id: str, tag_id: str) -> CustomerTagAssignment | None: ...
    def list_active_for_customer(self, customer_id: str) -> list[CustomerTagAssignment]: ...
    def list_for_tag(self, tag_id: str) -> list[CustomerTagAssignment]: ...
