"""CRM-1 (§11 REGLA CERO) — every CRM identity is generated by backend.shared.ids.

There is exactly one generator (``backend/shared/ids.py::new_uuid``). No CRM
repository may mint its own id via ``uuid4()``, ``randomblob()`` or a bespoke
helper. This is a positive requirement, so it only activates once repository
code exists under the canonical CRM roots (CRM-3+); until then it is skipped
with an explicit pointer rather than reporting a false "pass" for a rule
nothing has had a chance to violate or satisfy yet.

The canonical-import check is at the *package* level, not per file: an
aggregate repository (e.g. ``CustomerRepository.save()``) legitimately
``INSERT``s an entity whose ``id`` the domain layer already minted via
``Customer.create()`` calling ``new_uuid()`` — that repository file never
needs its own import of ``backend.shared.ids``, and requiring one per file
would just make people add a dead import to appease the scanner. What must
hold is: (a) no file anywhere in the CRM infra layer reaches for a forbidden
source, and (b) `new_uuid` is demonstrably the generator this bounded
context uses somewhere in its own persistence code (e.g. the audit/outbox
repositories that mint their own log-row ids).
"""

from __future__ import annotations

import re

import pytest

from .customers_crm_guardrails import CRM_INFRA_REPO_ROOTS, crm_py_files, relative

_FORBIDDEN_ID_SOURCE = re.compile(r"\buuid4\s*\(|\brandomblob\s*\(", re.IGNORECASE)
_CANONICAL_IMPORT = "backend.shared.ids"


def test_customers_crm_repositories_use_canonical_uuid_generator():
    repo_files = crm_py_files(CRM_INFRA_REPO_ROOTS)
    if not repo_files:
        pytest.skip(
            "No CRM repository code exists yet (CRM-3 creates it under "
            "backend/infrastructure/db/repositories/{customers,crm,...}/). "
            "This guardrail activates automatically once that code lands."
        )

    offenders = [
        f"{relative(path)}: uuid4()/randomblob() used for identity"
        for path in repo_files
        if _FORBIDDEN_ID_SOURCE.search(path.read_text(encoding="utf-8"))
    ]
    assert not offenders, (
        "CRM repositories must mint ids exclusively via "
        f"`from {_CANONICAL_IMPORT} import new_uuid`:\n" + "\n".join(offenders)
    )

    uses_canonical_generator = any(
        _CANONICAL_IMPORT in path.read_text(encoding="utf-8") for path in repo_files
    )
    assert uses_canonical_generator, (
        f"No file under the CRM infra repository layer imports {_CANONICAL_IMPORT} — "
        "REGLA CERO requires the canonical generator to be demonstrably in use "
        "somewhere in this bounded context's persistence code."
    )
