"""Repository ports for the Customer Display bounded context — SET-17.
Protocols only — implementations land in
``backend/infrastructure/db/repositories/customer_display/``. Every id is
a UUIDv7 string. Mirrors backend/domain/document_output/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.customer_display.entities.advertising_slot import AdvertisingSlot
from backend.domain.customer_display.entities.campaign_placement import CampaignPlacement
from backend.domain.customer_display.entities.content import Content
from backend.domain.customer_display.entities.content_campaign import ContentCampaign
from backend.domain.customer_display.entities.content_impression import ContentImpression
from backend.domain.customer_display.entities.customer_display import CustomerDisplay
from backend.domain.customer_display.entities.display_layout import DisplayLayout
from backend.domain.customer_display.enums import CustomerDisplayMode


class CustomerDisplayRepositoryPort(Protocol):
    def save(self, display: CustomerDisplay) -> None: ...
    def get(self, display_id: str) -> CustomerDisplay | None: ...
    def list_by_workstation(self, workstation_id: str) -> list[CustomerDisplay]: ...
    def list_active(self) -> list[CustomerDisplay]: ...


class DisplayLayoutRepositoryPort(Protocol):
    def save(self, layout: DisplayLayout) -> None: ...
    def get(self, layout_id: str) -> DisplayLayout | None: ...
    def list_by_mode(self, mode: CustomerDisplayMode) -> list[DisplayLayout]: ...
    def get_active_for_mode(self, mode: CustomerDisplayMode) -> DisplayLayout | None: ...


class ContentRepositoryPort(Protocol):
    def save(self, content: Content) -> None: ...
    def get(self, content_id: str) -> Content | None: ...
    def list_active(self) -> list[Content]: ...


class ContentCampaignRepositoryPort(Protocol):
    def save(self, campaign: ContentCampaign) -> None: ...
    def get(self, campaign_id: str) -> ContentCampaign | None: ...
    def list_by_status(self, status: str) -> list[ContentCampaign]: ...


class AdvertisingSlotRepositoryPort(Protocol):
    def save(self, slot: AdvertisingSlot) -> None: ...
    def get(self, slot_id: str) -> AdvertisingSlot | None: ...
    def get_by_code(self, code: str) -> AdvertisingSlot | None: ...
    def list_by_mode(self, mode: CustomerDisplayMode) -> list[AdvertisingSlot]: ...


class CampaignPlacementRepositoryPort(Protocol):
    def save(self, placement: CampaignPlacement) -> None: ...
    def get(self, placement_id: str) -> CampaignPlacement | None: ...
    def get_active_for_slot(self, slot_id: str) -> CampaignPlacement | None: ...
    def list_for_campaign(self, campaign_id: str) -> list[CampaignPlacement]: ...


class ContentImpressionRepositoryPort(Protocol):
    def save(self, impression: ContentImpression) -> None: ...
    def list_for_placement(self, placement_id: str) -> list[ContentImpression]: ...
