"""Repository ports for the Customer Service (atención al cliente) bounded
context (§10). Protocols only — implementations live in
``backend/infrastructure/db/repositories/customer_service/``. Every id is a
UUIDv7 string. Mirrors backend/domain/crm/repository_ports.py.
"""

from __future__ import annotations

from typing import Protocol

from backend.domain.customer_service.entities.customer_service_case import CustomerServiceCase
from backend.domain.customer_service.entities.service_case_category import ServiceCaseCategory
from backend.domain.customer_service.entities.service_case_escalation import (
    ServiceCaseEscalation,
)
from backend.domain.customer_service.entities.service_case_resolution import (
    ServiceCaseResolution,
)
from backend.domain.customer_service.entities.service_level_policy import ServiceLevelPolicy
from backend.domain.customer_service.entities.sla_instance import SLAInstance
from backend.domain.customer_service.value_objects.service_case_code import ServiceCaseCode


class ServiceCaseRepositoryPort(Protocol):
    def next_code(self) -> ServiceCaseCode: ...
    def save(self, case: CustomerServiceCase, *, operation_id: str | None = None) -> None: ...
    def update(self, case: CustomerServiceCase) -> None: ...
    def get(self, case_id: str) -> CustomerServiceCase | None: ...
    def get_by_code(self, code: str) -> CustomerServiceCase | None: ...
    def get_by_operation_id(self, operation_id: str) -> CustomerServiceCase | None: ...
    def list_owned_by(self, owner_user_ids: tuple[str, ...], *,
                       limit: int = 200, offset: int = 0) -> list[CustomerServiceCase]: ...
    def list_open_owned_by(self, owner_user_ids: tuple[str, ...], *,
                            limit: int = 500, offset: int = 0) -> list[CustomerServiceCase]: ...


class ServiceCaseCategoryRepositoryPort(Protocol):
    def save(self, category: ServiceCaseCategory) -> None: ...
    def get(self, category_id: str) -> ServiceCaseCategory | None: ...
    def list_active(self) -> list[ServiceCaseCategory]: ...


class ServiceCaseResolutionRepositoryPort(Protocol):
    def save(self, resolution: ServiceCaseResolution) -> None: ...
    def get_for_case(self, case_id: str) -> ServiceCaseResolution | None: ...


class ServiceCaseEscalationRepositoryPort(Protocol):
    def save(self, escalation: ServiceCaseEscalation) -> None: ...
    def list_for_case(self, case_id: str) -> list[ServiceCaseEscalation]: ...


class ServiceLevelPolicyRepositoryPort(Protocol):
    def save(self, policy: ServiceLevelPolicy) -> None: ...
    def get(self, policy_id: str) -> ServiceLevelPolicy | None: ...
    def list_active(self) -> list[ServiceLevelPolicy]: ...


class SLAInstanceRepositoryPort(Protocol):
    def save(self, instance: SLAInstance) -> None: ...
    def update(self, instance: SLAInstance) -> None: ...
    def get_for_case(self, case_id: str) -> SLAInstance | None: ...
    def list_open(self, *, limit: int = 500, offset: int = 0) -> list[SLAInstance]: ...
