from enum import Enum


class ContainerCategory(str, Enum):
    MASTER_CONTAINER = "MASTER_CONTAINER"
    TRAILER_CONTAINER = "TRAILER_CONTAINER"
    PALLET = "PALLET"
    CAGE = "CAGE"
    CRATE = "CRATE"
    PLASTIC_BOX = "PLASTIC_BOX"
    CARDBOARD_BOX = "CARDBOARD_BOX"
    TOTE = "TOTE"
    COOLER = "COOLER"
    TRAY = "TRAY"
    BAG = "BAG"
    BIN = "BIN"


class ContainerOwnerType(str, Enum):
    COMPANY = "COMPANY"
    SUPPLIER = "SUPPLIER"
    THIRD_PARTY = "THIRD_PARTY"
    RENTED = "RENTED"
    DISPOSABLE = "DISPOSABLE"


class ContainerStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ASSIGNED = "ASSIGNED"
    LOADING = "LOADING"
    SEALED = "SEALED"
    IN_TRANSIT = "IN_TRANSIT"
    AT_DESTINATION = "AT_DESTINATION"
    IN_INSPECTION = "IN_INSPECTION"
    DAMAGED = "DAMAGED"
    LOST = "LOST"
    QUARANTINED = "QUARANTINED"
    CLEANING = "CLEANING"
    MAINTENANCE = "MAINTENANCE"
    RELEASED = "RELEASED"
    RETIRED = "RETIRED"


class ShipmentStatus(str, Enum):
    DRAFT = "DRAFT"
    LOADING = "LOADING"
    READY_TO_SEAL = "READY_TO_SEAL"
    SEALED = "SEALED"
    DISPATCHED = "DISPATCHED"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    RECEIVING = "RECEIVING"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"


class ShipmentNodeStatus(str, Enum):
    EXPECTED = "EXPECTED"
    LOADING = "LOADING"
    SEALED = "SEALED"
    ARRIVED = "ARRIVED"
    OPENED = "OPENED"
    COUNTED = "COUNTED"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_ACCEPTED = "PARTIALLY_ACCEPTED"
    REJECTED = "REJECTED"
    MISSING = "MISSING"
    DAMAGED = "DAMAGED"
    QUARANTINED = "QUARANTINED"
    RELEASED = "RELEASED"


class SourceDocumentType(str, Enum):
    PURCHASE_ORDER = "PURCHASE_ORDER"
    DIRECT_PURCHASE = "DIRECT_PURCHASE"
    PURCHASE_REQUISITION = "PURCHASE_REQUISITION"
    TRANSFER_ORDER = "TRANSFER_ORDER"
    SUPPLIER_RETURN = "SUPPLIER_RETURN"
    CUSTOMER_DELIVERY = "CUSTOMER_DELIVERY"
    PRODUCTION_ORDER = "PRODUCTION_ORDER"


class CustodyAction(str, Enum):
    ASSIGNED = "ASSIGNED"
    TRANSFERRED = "TRANSFERRED"
    RELEASED = "RELEASED"
    RETURNED = "RETURNED"
    DAMAGED = "DAMAGED"
    LOST = "LOST"
